"""Silver landing tables: column order and NOT NULL set.

silver-merge-engine-migration Ticket 13. Originally generated from the
DuckDB engine's live DDL; since Ticket 17 deleted that engine this file is
hand-maintained, and tests/unit/test_silver_schema_snapshot.py holds it
equal to infra/snowflake/sql/bootstrap/11_silver_landing_schema.sql (table
set, column order, NOT NULL). `_record_landing_passthrough` raises on a row
missing a REQUIRED column, and the in-run lookup (ADR 0011) returns rows
shaped by COLUMNS. Scope: the tables that go through the passthrough, which
is also the set the landing DDL creates.
"""

from __future__ import annotations

from types import MappingProxyType

COLUMNS: MappingProxyType[str, tuple[str, ...]] = MappingProxyType({
    'sec_accounting_flag': (
        'cik',
        'accession_number',
        'fiscal_year',
        'period_end',
        'form_type',
        'auditor_name',
        'auditor_pcaob_id',
        'auditor_location',
        'icfr_attestation',
        'auditor_changed',
        'beneish_m_score',
        'altman_z_score',
        'piotroski_f_score',
        'parser_version',
        'ingested_at',
        'valid_from',
        'valid_to',
        'is_current',
    ),
    'sec_adv_disclosure_event': (
        'accession_number',
        'event_index',
        'disclosure_category',
        'event_date',
        'is_reported',
        'description',
        'parser_version',
        'last_sync_run_id',
    ),
    'sec_adv_filing': (
        'accession_number',
        'cik',
        'form',
        'adviser_name',
        'sec_file_number',
        'crd_number',
        'effective_date',
        'filing_status',
        'filing_action',
        'source_format',
        'parser_version',
        'last_sync_run_id',
        'mdm_entity_id',
    ),
    'sec_adv_firm_roster': (
        'adviser_crd_number',
        'dataset_period',
        'private_funds_reported',
        'private_fund_count_7b1',
        'any_hedge_funds',
        'hedge_fund_count',
        'any_pe_funds',
        'pe_fund_count',
        'total_gross_assets_private_funds',
        'private_fund_count_7b2',
        'source_sha256',
        'parser_version',
        'last_sync_run_id',
    ),
    'sec_adv_office': (
        'accession_number',
        'office_index',
        'office_name',
        'city',
        'state_or_country',
        'country',
        'is_headquarters',
        'parser_version',
        'last_sync_run_id',
    ),
    'sec_adv_private_fund': (
        'accession_number',
        'fund_index',
        'filing_id',
        'adviser_crd_number',
        'private_fund_id',
        'reference_id',
        'schedule_section',
        'reporting_role',
        'filing_action',
        'fund_name',
        'fund_type',
        'jurisdiction',
        'aum_amount',
        'effective_date',
        'source_dataset_period',
        'source_sha256',
        'parser_version',
        'last_sync_run_id',
        'mdm_entity_id',
    ),
    'sec_auditor_report_evidence': (
        'accession_number',
        'registrant_cik',
        'form_type',
        'document_name',
        'audited_period_end',
        'report_date',
        'principal_firm_name',
        'principal_firm_location',
        'pcaob_firm_id',
        'evidence_source',
        'raw_locator',
        'source_sha256',
        'evidence_fingerprint',
        'form_ap_filing_id',
        'original_form_ap_filing_id',
        'latest_amendment',
        'parser_version',
        'last_sync_run_id',
    ),
    'sec_company': (
        'cik',
        'entity_name',
        'entity_type',
        'sic',
        'sic_description',
        'state_of_incorporation',
        'state_of_incorporation_desc',
        'fiscal_year_end',
        'ein',
        'description',
        'category',
        'first_sync_run_id',
        'last_sync_run_id',
        'last_synced_at',
        'mdm_entity_id',
    ),
    'sec_company_address': (
        'cik',
        'address_type',
        'street1',
        'street2',
        'city',
        'state_or_country',
        'zip_code',
        'country',
        'last_sync_run_id',
        'last_synced_at',
        'country_code',
    ),
    'sec_company_filing': (
        'accession_number',
        'cik',
        'form',
        'filing_date',
        'report_date',
        'acceptance_datetime',
        'act',
        'file_number',
        'film_number',
        'items',
        'size',
        'is_xbrl',
        'is_inline_xbrl',
        'primary_document',
        'primary_doc_desc',
        'last_sync_run_id',
        'last_synced_at',
    ),
    'sec_company_former_name': (
        'cik',
        'former_name',
        'date_changed',
        'ordinal',
        'last_sync_run_id',
    ),
    'sec_company_submission_file': (
        'cik',
        'file_name',
        'filing_count',
        'filing_from',
        'filing_to',
        'last_sync_run_id',
        'last_synced_at',
    ),
    'sec_company_ticker': (
        'cik',
        'ticker',
        'exchange',
        'source_name',
        'source_rank',
        'last_sync_run_id',
        'last_synced_at',
    ),
    'sec_current_filing_feed': (
        'accession_number',
        'cik',
        'form',
        'company_name',
        'filing_date',
        'accepted_at',
        'filing_href',
        'index_href',
        'summary',
        'source_url',
        'feed_published_at',
        'raw_object_id',
        'last_sync_run_id',
        'last_synced_at',
    ),
    'sec_earnings_release': (
        'cik',
        'accession_number',
        'filing_date',
        'fiscal_year',
        'fiscal_quarter',
        'period_end',
        'revenue_gaap',
        'net_income_gaap',
        'eps_gaap_diluted',
        'has_non_gaap',
        'has_guidance',
        'parser_version',
        'ingested_at',
    ),
    'sec_employment_event': (
        'accession_number',
        'event_index',
        'cik',
        'event_type',
        'person_name',
        'exec_role',
        'previous_role',
        'compensation_amount',
        'effective_date',
        'parser_version',
        'ingested_at',
    ),
    'sec_entity_facts_refresh_watermark': (
        'cik',
        'entity_facts_refreshed_at',
    ),
    'sec_executive_record': (
        'cik',
        'accession_number',
        'fiscal_year',
        'exec_name',
        'exec_role',
        'total_comp',
        'base_salary',
        'bonus',
        'stock_awards',
        'option_awards',
        'non_equity_incentive',
        'parser_version',
        'ingested_at',
    ),
    'sec_filing_attachment': (
        'accession_number',
        'sequence_number',
        'document_name',
        'document_type',
        'document_description',
        'document_url',
        'is_primary',
        'raw_object_id',
        'last_sync_run_id',
    ),
    'sec_filing_text': (
        'accession_number',
        'text_version',
        'source_document_name',
        'text_storage_path',
        'text_sha256',
        'char_count',
        'extracted_at',
    ),
    'sec_financial_derived': (
        'cik',
        'accession_number',
        'fiscal_year',
        'fiscal_period',
        'period_end',
        'form_type',
        'revenue',
        'gross_profit',
        'ebitda',
        'ebit',
        'net_income',
        'eps_diluted',
        'total_assets',
        'total_liabilities',
        'total_equity',
        'cash_and_equivalents',
        'total_debt',
        'current_assets',
        'current_liabilities',
        'accounts_receivable',
        'inventory',
        'selling_general_admin_expense',
        'retained_earnings',
        'depreciation_amortization',
        'property_plant_equipment_net',
        'shares_outstanding',
        'operating_cash_flow',
        'capex',
        'free_cash_flow',
        'gross_margin',
        'ebitda_margin',
        'net_margin',
        'roic',
        'roe',
        'roa',
        'parser_version',
        'ingested_at',
    ),
    'sec_financial_fact': (
        'cik',
        'accession_number',
        'fiscal_year',
        'fiscal_period',
        'period_end',
        'period_start',
        'form_type',
        'concept',
        'value',
        'unit',
        'decimals',
        'segment',
        'parser_version',
        'ingested_at',
        'valid_from',
        'valid_to',
        'is_current',
    ),
    'sec_fundamentals_processed_accession': (
        'mode',
        'accession_number',
        'processed_at',
    ),
    'sec_guidance_fact': (
        'fact_key',
        'cik',
        'ticker',
        'company_key',
        'accession_number',
        'metric',
        'period_type',
        'fiscal_year',
        'fiscal_quarter',
        'period_end',
        'value_low',
        'value_mid',
        'value_high',
        'unit',
        'currency',
        'is_non_gaap',
        'as_of',
        'source_system',
        'source_ref',
        'excerpt',
        'confidence',
        'parser_version',
        'ingested_at',
    ),
    'sec_guidance_fact_reject': (
        'cik',
        'accession_number',
        'metric',
        'reject_reason',
        'raw_payload',
        'parser_version',
        'ingested_at',
    ),
    'sec_ownership_derivative_txn': (
        'accession_number',
        'owner_index',
        'txn_index',
        'security_title',
        'transaction_date',
        'transaction_code',
        'transaction_shares',
        'transaction_price',
        'acquired_disposed_code',
        'shares_owned_after',
        'ownership_nature',
        'ownership_direct_indirect',
        'conversion_or_exercise_price',
        'exercise_date',
        'expiration_date',
        'underlying_security_title',
        'underlying_security_shares',
        'parser_version',
        'last_sync_run_id',
        'mdm_entity_id',
        'reporting_owner_count',
    ),
    'sec_ownership_non_derivative_txn': (
        'accession_number',
        'owner_index',
        'txn_index',
        'security_title',
        'transaction_date',
        'transaction_code',
        'transaction_shares',
        'transaction_price',
        'acquired_disposed_code',
        'shares_owned_after',
        'ownership_nature',
        'ownership_direct_indirect',
        'parser_version',
        'last_sync_run_id',
        'mdm_entity_id',
        'reporting_owner_count',
    ),
    'sec_ownership_reporting_owner': (
        'accession_number',
        'owner_index',
        'owner_cik',
        'owner_name',
        'is_director',
        'is_officer',
        'is_ten_percent_owner',
        'is_other',
        'officer_title',
        'parser_version',
        'last_sync_run_id',
        'mdm_entity_id',
        'owner_name_raw',
        'other_text',
        'filing_footnote_text',
        'filing_remarks',
        'address_is_care_of',
        'address_non_us',
        'owner_submissions_present',
        'owner_submissions_sha256',
        'owner_entity_type',
        'owner_sic',
        'owner_state_of_incorporation',
        'owner_ein',
        'owner_ticker_count',
        'owner_org',
        'owner_fiscal_year_end',
    ),
    'sec_pcaob_firm_identity': (
        'pcaob_firm_id',
        'canonical_name',
        'city',
        'state',
        'country',
        'status',
        'snapshot_uri',
        'snapshot_sha256',
        'last_sync_run_id',
    ),
    'sec_raw_object': (
        'raw_object_id',
        'source_type',
        'cik',
        'accession_number',
        'form',
        'source_url',
        'storage_path',
        'content_type',
        'content_encoding',
        'byte_size',
        'sha256',
        'fetched_at',
        'http_status',
        'source_last_modified',
        'source_etag',
    ),
    'sec_subsidiary_evidence': (
        'accession_number',
        'registrant_cik',
        'document_name',
        'document_type',
        'row_ordinal',
        'legal_name',
        'jurisdiction',
        'parent_scope',
        'immediate_parent_known',
        'effective_date',
        'row_locator',
        'source_sha256',
        'parser_version',
        'last_sync_run_id',
    ),
    'sec_thirteenf_filing': (
        'accession_number',
        'cik',
        'period_of_report',
        'filing_date',
        'form',
        'amendment_type',
        'confidential_omission',
        'effective_status',
        'superseded_by_accession',
        'parser_version',
        'ingested_at',
    ),
    'sec_thirteenf_holding': (
        'cik',
        'accession_number',
        'holding_index',
        'period_of_report',
        'cusip',
        'issuer_name',
        'security_title',
        'shares_held',
        'market_value',
        'security_class',
        'put_call',
        'discretion_type',
        'voting_auth_sole',
        'voting_auth_shared',
        'voting_auth_none',
        'parser_version',
        'ingested_at',
    ),
})

REQUIRED: MappingProxyType[str, tuple[str, ...]] = MappingProxyType({
    'sec_accounting_flag': (
        'cik',
        'accession_number',
        'fiscal_year',
        'form_type',
        'valid_from',
        'is_current',
    ),
    'sec_adv_disclosure_event': (
        'accession_number',
        'event_index',
    ),
    'sec_adv_filing': (
        'accession_number',
    ),
    'sec_adv_firm_roster': (
        'adviser_crd_number',
        'dataset_period',
    ),
    'sec_adv_office': (
        'accession_number',
        'office_index',
    ),
    'sec_adv_private_fund': (
        'accession_number',
        'fund_index',
    ),
    'sec_auditor_report_evidence': (
        'accession_number',
        'evidence_fingerprint',
    ),
    'sec_company': (
        'cik',
    ),
    'sec_company_address': (
        'cik',
        'address_type',
    ),
    'sec_company_filing': (
        'accession_number',
    ),
    'sec_company_former_name': (
        'cik',
        'ordinal',
    ),
    'sec_company_submission_file': (
        'cik',
        'file_name',
    ),
    'sec_company_ticker': (
        'cik',
        'ticker',
        'source_name',
    ),
    'sec_current_filing_feed': (
        'accession_number',
    ),
    'sec_earnings_release': (
        'cik',
        'accession_number',
        'filing_date',
        'has_non_gaap',
        'has_guidance',
    ),
    'sec_employment_event': (
        'accession_number',
        'event_index',
        'cik',
        'event_type',
        'person_name',
        'effective_date',
        'parser_version',
    ),
    'sec_entity_facts_refresh_watermark': (
        'cik',
    ),
    'sec_executive_record': (
        'cik',
        'accession_number',
        'fiscal_year',
        'exec_name',
    ),
    'sec_filing_attachment': (
        'accession_number',
        'document_name',
        'document_type',
        'document_url',
        'is_primary',
    ),
    'sec_filing_text': (
        'accession_number',
        'text_version',
        'source_document_name',
        'text_storage_path',
        'text_sha256',
        'char_count',
        'extracted_at',
    ),
    'sec_financial_derived': (
        'cik',
        'accession_number',
        'fiscal_year',
        'fiscal_period',
        'period_end',
        'form_type',
    ),
    'sec_financial_fact': (
        'cik',
        'accession_number',
        'fiscal_year',
        'fiscal_period',
        'period_end',
        'period_start',
        'form_type',
        'concept',
        'segment',
        'valid_from',
        'is_current',
    ),
    'sec_fundamentals_processed_accession': (
        'mode',
        'accession_number',
    ),
    'sec_guidance_fact': (
        'fact_key',
        'cik',
        'accession_number',
        'metric',
        'period_type',
        'fiscal_year',
        'fiscal_quarter',
        'is_non_gaap',
        'as_of',
        'source_system',
        'confidence',
    ),
    'sec_guidance_fact_reject': (
        'cik',
        'accession_number',
        'reject_reason',
    ),
    'sec_ownership_derivative_txn': (
        'accession_number',
        'owner_index',
        'txn_index',
    ),
    'sec_ownership_non_derivative_txn': (
        'accession_number',
        'owner_index',
        'txn_index',
    ),
    'sec_ownership_reporting_owner': (
        'accession_number',
        'owner_index',
    ),
    'sec_pcaob_firm_identity': (
        'pcaob_firm_id',
        'snapshot_sha256',
    ),
    'sec_raw_object': (
        'raw_object_id',
        'source_url',
        'storage_path',
        'sha256',
        'fetched_at',
        'http_status',
    ),
    'sec_subsidiary_evidence': (
        'accession_number',
        'document_name',
        'row_ordinal',
    ),
    'sec_thirteenf_filing': (
        'accession_number',
        'cik',
        'period_of_report',
        'filing_date',
        'form',
        'confidential_omission',
        'effective_status',
        'parser_version',
    ),
    'sec_thirteenf_holding': (
        'cik',
        'accession_number',
        'holding_index',
        'period_of_report',
    ),
})
