"""Command registry for warehouse CLI operations."""

from __future__ import annotations

from edgar_warehouse.application.commands import (
    acquire_identity_refresh_lease,
    bootstrap_batch,
    bootstrap_full,
    bootstrap_fundamentals,
    bootstrap_next,
    bootstrap,
    catch_up_daily_form_index,
    compute_identity_refresh_window,
    compute_windows,
    daily_incremental,
    fetch_adv_bulk,
    fetch_firm_roster,
    full_reconcile,
    gold_refresh,
    ingest_relationship_sources,
    load_daily_form_index_for_date,
    migrate_silver_shards,
    parse_adv_bronze,
    parse_ownership_bronze,
    reconcile_relationship_release,
    reduce_identity_refresh,
    release_identity_refresh_lease,
    seed_bronze_batches,
    seed_silver_batches,
    seed_universe,
    targeted_resync,
    validate_data_quality,
    verify_pipeline_run,
    write_run_summary,
)

COMMAND_REGISTRY = {
    "bootstrap-full": bootstrap_full.execute,
    "bootstrap": bootstrap.execute,
    "compute-windows": compute_windows.execute,
    "compute-identity-refresh-window": compute_identity_refresh_window.execute,
    "acquire-identity-refresh-lease": acquire_identity_refresh_lease.execute,
    "release-identity-refresh-lease": release_identity_refresh_lease.execute,
    "reduce-identity-refresh": reduce_identity_refresh.execute,
    "daily-incremental": daily_incremental.execute,
    "load-daily-form-index-for-date": load_daily_form_index_for_date.execute,
    "catch-up-daily-form-index": catch_up_daily_form_index.execute,
    "targeted-resync": targeted_resync.execute,
    "full-reconcile": full_reconcile.execute,
    "seed-universe": seed_universe.execute,
    "seed-silver-batches": seed_silver_batches.execute,
    "seed-bronze-batches": seed_bronze_batches.execute,
    "parse-adv-bronze": parse_adv_bronze.execute,
    "parse-ownership-bronze": parse_ownership_bronze.execute,
    "bootstrap-batch": bootstrap_batch.execute,
    "bootstrap-next": bootstrap_next.execute,
    "bootstrap-fundamentals": bootstrap_fundamentals.execute,   # Branch B (AD-05)
    "gold-refresh": gold_refresh.execute,
    "fetch-adv-bulk": fetch_adv_bulk.execute,
    "fetch-firm-roster": fetch_firm_roster.execute,
    "ingest-relationship-sources": ingest_relationship_sources.execute,
    "reconcile-relationship-release": reconcile_relationship_release.execute,
    "migrate-silver-shards": migrate_silver_shards.execute,
    "validate-data-quality": validate_data_quality.execute,
    "verify-pipeline-run": verify_pipeline_run.execute,
    "write-run-summary": write_run_summary.execute,
}
