-- Hand-maintained. Reflects edgar_warehouse.silver_store._DDL's sec_company_address table.
-- Originally generated by infra/scripts/generate_silver_dbt_models.py, deleted by
-- DuckDB Retirement Cutover Ticket 07 -- there is no regeneration step anymore;
-- edit this file directly when silver_store.py's schema changes.

{{ silver_model_config('SEC_COMPANY_ADDRESS') }}

select
    cik,
    address_type,
    street1,
    street2,
    city,
    state_or_country,
    zip_code,
    country,
    last_sync_run_id,
    last_synced_at
from {{ source('edgartools_silver_landing', 'SEC_COMPANY_ADDRESS') }}
qualify row_number() over (
    partition by cik, address_type
    order by parse_sequence desc
) = 1
  and {{ silver_not_retired('sec_company_address', "concat_ws('|', cik, address_type)") }}
