-- Auto-generated by infra/scripts/generate_silver_dbt_models.py -- do not hand-edit.
-- Reflects edgar_warehouse.silver_store._DDL's sec_pcaob_firm_identity table. Regenerate and diff
-- before re-applying if silver_store.py's schema has changed.

{{ silver_model_config('SEC_PCAOB_FIRM_IDENTITY') }}

select
    pcaob_firm_id,
    canonical_name,
    city,
    state,
    country,
    status,
    snapshot_uri,
    snapshot_sha256,
    last_sync_run_id
from {{ source('edgartools_silver_landing', 'SEC_PCAOB_FIRM_IDENTITY') }}
qualify row_number() over (
    partition by pcaob_firm_id, snapshot_sha256
    order by parse_sequence desc
) = 1
  and {{ silver_not_retired('sec_pcaob_firm_identity', "concat_ws('|', pcaob_firm_id, snapshot_sha256)") }}
