-- Hand-maintained. Reflects edgar_warehouse.silver_store._DDL's sec_pcaob_firm_identity table.
-- Originally generated by infra/scripts/generate_silver_dbt_models.py, deleted by
-- DuckDB Retirement Cutover Ticket 07 -- there is no regeneration step anymore;
-- edit this file directly when silver_store.py's schema changes.

{{ silver_model_config('SEC_PCAOB_FIRM_IDENTITY') }}

select
    pcaob_firm_id,
    canonical_name,
    city,
    state,
    country,
    status,
    snapshot_uri,
    snapshot_sha256,
    last_sync_run_id
from {{ source('edgartools_silver_landing', 'SEC_PCAOB_FIRM_IDENTITY') }}
qualify row_number() over (
    partition by pcaob_firm_id, snapshot_sha256
    order by parse_sequence desc
) = 1
  and {{ silver_not_retired('sec_pcaob_firm_identity', "concat_ws('|', pcaob_firm_id, snapshot_sha256)") }}
