-- Auto-generated by infra/scripts/generate_silver_dbt_models.py -- do not hand-edit.
-- Reflects edgar_warehouse.silver_store._DDL's sec_earnings_release table. Regenerate and diff
-- before re-applying if silver_store.py's schema has changed.

{{ silver_model_config('SEC_EARNINGS_RELEASE') }}

select
    cik,
    accession_number,
    filing_date,
    fiscal_year,
    fiscal_quarter,
    period_end,
    revenue_gaap,
    net_income_gaap,
    eps_gaap_diluted,
    has_non_gaap,
    has_guidance,
    parser_version,
    ingested_at
from {{ source('edgartools_silver_landing', 'SEC_EARNINGS_RELEASE') }}
qualify row_number() over (
    partition by cik, accession_number
    order by parse_sequence desc
) = 1
  and {{ silver_not_retired('sec_earnings_release', "concat_ws('|', cik, accession_number)") }}
