-- Hand-maintained. Reflects edgar_warehouse.silver_store._DDL's sec_executive_record table.
-- Originally generated by infra/scripts/generate_silver_dbt_models.py, deleted by
-- DuckDB Retirement Cutover Ticket 07 -- there is no regeneration step anymore;
-- edit this file directly when silver_store.py's schema changes.

{{ silver_model_config('SEC_EXECUTIVE_RECORD') }}

select
    cik,
    accession_number,
    fiscal_year,
    exec_name,
    exec_role,
    total_comp,
    base_salary,
    bonus,
    stock_awards,
    option_awards,
    non_equity_incentive,
    parser_version,
    ingested_at
from {{ source('edgartools_silver_landing', 'SEC_EXECUTIVE_RECORD') }}
qualify row_number() over (
    partition by cik, accession_number, exec_name
    order by parse_sequence desc
) = 1
  and {{ silver_not_retired('sec_executive_record', "concat_ws('|', cik, accession_number, exec_name)") }}
