-- Auto-generated by infra/scripts/generate_silver_dbt_models.py -- do not hand-edit.
-- Reflects edgar_warehouse.silver_store._DDL's sec_adv_disclosure_event table. Regenerate and diff
-- before re-applying if silver_store.py's schema has changed.

{{ silver_model_config('SEC_ADV_DISCLOSURE_EVENT') }}

select
    accession_number,
    event_index,
    disclosure_category,
    event_date,
    is_reported,
    description,
    parser_version,
    last_sync_run_id
from {{ source('edgartools_silver_landing', 'SEC_ADV_DISCLOSURE_EVENT') }}
qualify row_number() over (
    partition by accession_number, event_index
    order by parse_sequence desc
) = 1
