-- Auto-generated by infra/scripts/generate_silver_dbt_models.py -- do not hand-edit.
-- Reflects edgar_warehouse.silver_store._DDL's sec_employment_event table. Regenerate and diff
-- before re-applying if silver_store.py's schema has changed.

{{ silver_model_config('SEC_EMPLOYMENT_EVENT') }}

select
    accession_number,
    event_index,
    cik,
    event_type,
    person_name,
    exec_role,
    previous_role,
    compensation_amount,
    effective_date,
    parser_version,
    ingested_at
from {{ source('edgartools_silver_landing', 'SEC_EMPLOYMENT_EVENT') }}
qualify row_number() over (
    partition by accession_number, event_index
    order by parse_sequence desc
) = 1
  and {{ silver_not_retired('sec_employment_event', "concat_ws('|', accession_number, event_index)") }}
