-- Auto-generated by infra/scripts/generate_silver_dbt_models.py -- do not hand-edit.
-- Reflects edgar_warehouse.silver_store._DDL's sec_company_address table. Regenerate and diff
-- before re-applying if silver_store.py's schema has changed.

{{ silver_model_config('SEC_COMPANY_ADDRESS') }}

select
    cik,
    address_type,
    street1,
    street2,
    city,
    state_or_country,
    zip_code,
    country,
    last_sync_run_id,
    last_synced_at
from {{ source('edgartools_silver_landing', 'SEC_COMPANY_ADDRESS') }}
qualify row_number() over (
    partition by cik, address_type
    order by parse_sequence desc
) = 1
