-- Hand-maintained. Reflects the sec_guidance_fact_reject landing table (infra/snowflake/sql/bootstrap/11_silver_landing_schema.sql).
-- Originally generated by infra/scripts/generate_silver_dbt_models.py, deleted by
-- DuckDB Retirement Cutover Ticket 07 -- there is no regeneration step anymore;
-- edit this file directly when that landing table changes.

{{ config(alias='SEC_GUIDANCE_FACT_REJECT', materialized='view') }}

-- Quarantine log, no natural key -- every row is already final, so this
-- is a plain passthrough view, not a collapsed dynamic_table (Ticket 01's
-- Answer). parse_sequence is kept for audit ordering.
select *
from {{ source('edgartools_silver_landing', 'SEC_GUIDANCE_FACT_REJECT') }}
