-- Auto-generated by infra/scripts/generate_silver_dbt_models.py -- do not hand-edit.
-- Reflects edgar_warehouse.silver_store._DDL's sec_adv_office table. Regenerate and diff
-- before re-applying if silver_store.py's schema has changed.

{{ silver_model_config('SEC_ADV_OFFICE') }}

select
    accession_number,
    office_index,
    office_name,
    city,
    state_or_country,
    country,
    is_headquarters,
    parser_version,
    last_sync_run_id
from {{ source('edgartools_silver_landing', 'SEC_ADV_OFFICE') }}
qualify row_number() over (
    partition by accession_number, office_index
    order by parse_sequence desc
) = 1
  and {{ silver_not_retired('sec_adv_office', "concat_ws('|', accession_number, office_index)") }}
