-- Hand-maintained. Reflects edgar_warehouse.silver_store._DDL's sec_guidance_fact_reject table.
-- Originally generated by infra/scripts/generate_silver_dbt_models.py, deleted by
-- DuckDB Retirement Cutover Ticket 07 -- there is no regeneration step anymore;
-- edit this file directly when silver_store.py's schema changes.

{{ config(alias='SEC_GUIDANCE_FACT_REJECT', materialized='view') }}

-- Quarantine log, no natural key -- every row is already final, so this
-- is a plain passthrough view, not a collapsed dynamic_table (Ticket 01's
-- Answer). parse_sequence is kept for audit ordering.
select *
from {{ source('edgartools_silver_landing', 'SEC_GUIDANCE_FACT_REJECT') }}
