-- Hand-maintained. Reflects edgar_warehouse.silver_store._DDL's sec_company table.
-- Originally generated by infra/scripts/generate_silver_dbt_models.py, deleted by
-- DuckDB Retirement Cutover Ticket 07 -- there is no regeneration step anymore;
-- edit this file directly when silver_store.py's schema changes.

{{ silver_model_config('SEC_COMPANY') }}

select
    cik,
    entity_name,
    entity_type,
    sic,
    sic_description,
    state_of_incorporation,
    state_of_incorporation_desc,
    fiscal_year_end,
    ein,
    description,
    category,
    first_sync_run_id,
    last_sync_run_id,
    last_synced_at,
    mdm_entity_id
from {{ source('edgartools_silver_landing', 'SEC_COMPANY') }}
qualify row_number() over (
    partition by cik
    order by parse_sequence desc
) = 1
  and {{ silver_not_retired('sec_company', "concat_ws('|', cik)") }}
