-- Auto-generated by infra/scripts/generate_silver_dbt_models.py -- do not hand-edit.
-- Reflects edgar_warehouse.silver_store._DDL's sec_company table. Regenerate and diff
-- before re-applying if silver_store.py's schema has changed.

{{ silver_model_config('SEC_COMPANY') }}

select
    cik,
    entity_name,
    entity_type,
    sic,
    sic_description,
    state_of_incorporation,
    state_of_incorporation_desc,
    fiscal_year_end,
    ein,
    description,
    category,
    first_sync_run_id,
    last_sync_run_id,
    last_synced_at
from {{ source('edgartools_silver_landing', 'SEC_COMPANY') }}
qualify row_number() over (
    partition by cik
    order by parse_sequence desc
) = 1
