-- Auto-generated by infra/scripts/generate_silver_dbt_models.py -- do not hand-edit.
-- Reflects edgar_warehouse.silver_store._DDL's sec_guidance_fact_reject table. Regenerate and diff
-- before re-applying if silver_store.py's schema has changed.

{{ config(alias='SEC_GUIDANCE_FACT_REJECT', materialized='view') }}

-- Quarantine log, no natural key -- every row is already final, so this
-- is a plain passthrough view, not a collapsed dynamic_table (Ticket 01's
-- Answer). parse_sequence is kept for audit ordering.
select *
from {{ source('edgartools_silver_landing', 'SEC_GUIDANCE_FACT_REJECT') }}
