-- Auto-generated by infra/scripts/generate_silver_dbt_models.py -- do not hand-edit.
-- Reflects edgar_warehouse.silver_store._DDL's sec_current_filing_feed table. Regenerate and diff
-- before re-applying if silver_store.py's schema has changed.

{{ silver_model_config('SEC_CURRENT_FILING_FEED') }}

select
    accession_number,
    cik,
    form,
    company_name,
    filing_date,
    accepted_at,
    filing_href,
    index_href,
    summary,
    source_url,
    feed_published_at,
    raw_object_id,
    last_sync_run_id,
    last_synced_at
from {{ source('edgartools_silver_landing', 'SEC_CURRENT_FILING_FEED') }}
qualify row_number() over (
    partition by accession_number
    order by parse_sequence desc
) = 1
  and {{ silver_not_retired('sec_current_filing_feed', "concat_ws('|', accession_number)") }}
