-- Auto-generated by infra/scripts/generate_silver_dbt_models.py -- do not hand-edit.
-- Reflects edgar_warehouse.silver_store._DDL's sec_company_filing table. Regenerate and diff
-- before re-applying if silver_store.py's schema has changed.

{{ silver_model_config('SEC_COMPANY_FILING') }}

-- First-insert-wins (cik, act, file_number, film_number, items) from the earliest parse;
-- last-write-wins (form, filing_date, report_date, acceptance_datetime, size, is_xbrl, is_inline_xbrl, primary_document, primary_doc_desc, last_sync_run_id, last_synced_at) from the latest parse -- matches
-- silver_store.py's merge_company_filing-shaped two-pass upsert
-- exactly (see generate_silver_dbt_models.py's _SPLIT_TABLES for the citation).
with first_seen as (
    select
    accession_number,
    cik,
    act,
    file_number,
    film_number,
    items
    from {{ source('edgartools_silver_landing', 'SEC_COMPANY_FILING') }}
    qualify row_number() over (partition by accession_number order by parse_sequence asc) = 1
),
last_seen as (
    select
    accession_number,
    form,
    filing_date,
    report_date,
    acceptance_datetime,
    size,
    is_xbrl,
    is_inline_xbrl,
    primary_document,
    primary_doc_desc,
    last_sync_run_id,
    last_synced_at
    from {{ source('edgartools_silver_landing', 'SEC_COMPANY_FILING') }}
    qualify row_number() over (partition by accession_number order by parse_sequence desc) = 1
)
select
    f.accession_number,
    f.cik,
    f.act,
    f.file_number,
    f.film_number,
    f.items,
    l.form,
    l.filing_date,
    l.report_date,
    l.acceptance_datetime,
    l.size,
    l.is_xbrl,
    l.is_inline_xbrl,
    l.primary_document,
    l.primary_doc_desc,
    l.last_sync_run_id,
    l.last_synced_at
from first_seen f
join last_seen l
    on f.accession_number = l.accession_number
