-- Hand-maintained. Reflects edgar_warehouse.silver_store._DDL's sec_raw_object table.
-- Originally generated by infra/scripts/generate_silver_dbt_models.py, deleted by
-- DuckDB Retirement Cutover Ticket 07 -- there is no regeneration step anymore;
-- edit this file directly when silver_store.py's schema changes.

{{ silver_model_config('SEC_RAW_OBJECT') }}

select
    raw_object_id,
    source_type,
    cik,
    accession_number,
    form,
    source_url,
    storage_path,
    content_type,
    content_encoding,
    byte_size,
    sha256,
    fetched_at,
    http_status,
    source_last_modified,
    source_etag
from {{ source('edgartools_silver_landing', 'SEC_RAW_OBJECT') }}
qualify row_number() over (
    partition by raw_object_id
    order by parse_sequence desc
) = 1
  and {{ silver_not_retired('sec_raw_object', "concat_ws('|', raw_object_id)") }}
