-- Hand-maintained. Reflects the sec_employment_event landing table (infra/snowflake/sql/bootstrap/11_silver_landing_schema.sql).
-- Originally generated by infra/scripts/generate_silver_dbt_models.py, deleted by
-- DuckDB Retirement Cutover Ticket 07 -- there is no regeneration step anymore;
-- edit this file directly when that landing table changes.

{{ silver_model_config('SEC_EMPLOYMENT_EVENT') }}

select
    accession_number,
    event_index,
    cik,
    event_type,
    person_name,
    exec_role,
    previous_role,
    compensation_amount,
    effective_date,
    parser_version,
    ingested_at
from {{ source('edgartools_silver_landing', 'SEC_EMPLOYMENT_EVENT') }}
qualify row_number() over (
    partition by accession_number, event_index
    order by parse_sequence desc
) = 1
  and {{ silver_not_retired('sec_employment_event', "concat_ws('|', accession_number, event_index)") }}
