-- Hand-maintained. Reflects the sec_adv_filing landing table (infra/snowflake/sql/bootstrap/11_silver_landing_schema.sql).
-- Originally generated by infra/scripts/generate_silver_dbt_models.py, deleted by
-- DuckDB Retirement Cutover Ticket 07 -- there is no regeneration step anymore;
-- edit this file directly when that landing table changes.

{{ silver_model_config('SEC_ADV_FILING') }}

select
    accession_number,
    cik,
    form,
    adviser_name,
    sec_file_number,
    crd_number,
    effective_date,
    filing_status,
    filing_action,
    source_format,
    parser_version,
    last_sync_run_id,
    mdm_entity_id
from {{ source('edgartools_silver_landing', 'SEC_ADV_FILING') }}
qualify row_number() over (
    partition by accession_number
    order by parse_sequence desc
) = 1
  and {{ silver_not_retired('sec_adv_filing', "concat_ws('|', accession_number)") }}
