-- Hand-maintained. Reflects the sec_adv_firm_roster landing table (infra/snowflake/sql/bootstrap/11_silver_landing_schema.sql).
-- Originally generated by infra/scripts/generate_silver_dbt_models.py, deleted by
-- DuckDB Retirement Cutover Ticket 07 -- there is no regeneration step anymore;
-- edit this file directly when that landing table changes.

{{ silver_model_config('SEC_ADV_FIRM_ROSTER') }}

select
    adviser_crd_number,
    dataset_period,
    private_funds_reported,
    private_fund_count_7b1,
    any_hedge_funds,
    hedge_fund_count,
    any_pe_funds,
    pe_fund_count,
    total_gross_assets_private_funds,
    private_fund_count_7b2,
    source_sha256,
    parser_version,
    last_sync_run_id
from {{ source('edgartools_silver_landing', 'SEC_ADV_FIRM_ROSTER') }}
qualify row_number() over (
    partition by adviser_crd_number, dataset_period
    order by parse_sequence desc
) = 1
  and {{ silver_not_retired('sec_adv_firm_roster', "concat_ws('|', adviser_crd_number, dataset_period)") }}
