-- Hand-maintained. Reflects edgar_warehouse.silver_store._DDL's sec_subsidiary_evidence table.
-- Originally generated by infra/scripts/generate_silver_dbt_models.py, deleted by
-- DuckDB Retirement Cutover Ticket 07 -- there is no regeneration step anymore;
-- edit this file directly when silver_store.py's schema changes.

{{ silver_model_config('SEC_SUBSIDIARY_EVIDENCE') }}

select
    accession_number,
    registrant_cik,
    document_name,
    document_type,
    row_ordinal,
    legal_name,
    jurisdiction,
    parent_scope,
    immediate_parent_known,
    effective_date,
    row_locator,
    source_sha256,
    parser_version,
    last_sync_run_id
from {{ source('edgartools_silver_landing', 'SEC_SUBSIDIARY_EVIDENCE') }}
qualify row_number() over (
    partition by accession_number, document_name, row_ordinal
    order by parse_sequence desc
) = 1
  and {{ silver_not_retired('sec_subsidiary_evidence', "concat_ws('|', accession_number, document_name, row_ordinal)") }}
