-- Hand-maintained. Reflects the sec_ownership_reporting_owner landing table (infra/snowflake/sql/bootstrap/11_silver_landing_schema.sql).
-- Originally generated by infra/scripts/generate_silver_dbt_models.py, deleted by
-- DuckDB Retirement Cutover Ticket 07 -- there is no regeneration step anymore;
-- edit this file directly when that landing table changes.
--
-- Person Consumer Contract ticket 19 added the classification-evidence
-- columns (other_text .. owner_fiscal_year_end); see
-- infra/snowflake/sql/bootstrap/20_silver_landing_ownership_evidence.sql.

{{ silver_model_config('SEC_OWNERSHIP_REPORTING_OWNER') }}

-- Ticket 06: materializes the issuer's cik here, via a join to
-- sec_company_filing, so downstream consumers (gold, MDM) don't each have
-- to independently know this table needs an accession-number join to
-- resolve issuer CIK (sec_adv_filing.cik-is-NULL-for-ADV-data is the same
-- failure shape this is deliberately avoiding a repeat of).
with collapsed as (
select
    accession_number,
    owner_index,
    owner_cik,
    owner_name,
    is_director,
    is_officer,
    is_ten_percent_owner,
    is_other,
    officer_title,
    parser_version,
    last_sync_run_id,
    mdm_entity_id,
    owner_name_raw,
    other_text,
    filing_footnote_text,
    filing_remarks,
    address_is_care_of,
    address_non_us,
    owner_submissions_present,
    owner_submissions_sha256,
    owner_entity_type,
    owner_sic,
    owner_state_of_incorporation,
    owner_ein,
    owner_ticker_count,
    owner_org,
    owner_fiscal_year_end
from {{ source('edgartools_silver_landing', 'SEC_OWNERSHIP_REPORTING_OWNER') }}
qualify row_number() over (
    partition by accession_number, owner_index
    order by parse_sequence desc
) = 1
  and {{ silver_not_retired('sec_ownership_reporting_owner', "concat_ws('|', accession_number, owner_index)") }}
)
select
    collapsed.*,
    company_filing.cik
from collapsed
left join {{ ref('sec_company_filing') }} as company_filing
    on company_filing.accession_number = collapsed.accession_number
