-- Hand-maintained. Reflects edgar_warehouse.silver_store._DDL's sec_filing_text table.
-- Originally generated by infra/scripts/generate_silver_dbt_models.py, deleted by
-- DuckDB Retirement Cutover Ticket 07 -- there is no regeneration step anymore;
-- edit this file directly when silver_store.py's schema changes.

{{ silver_model_config('SEC_FILING_TEXT') }}

select
    accession_number,
    text_version,
    source_document_name,
    text_storage_path,
    text_sha256,
    char_count,
    extracted_at
from {{ source('edgartools_silver_landing', 'SEC_FILING_TEXT') }}
qualify row_number() over (
    partition by accession_number, text_version
    order by parse_sequence desc
) = 1
  and {{ silver_not_retired('sec_filing_text', "concat_ws('|', accession_number, text_version)") }}
