-- Auto-generated by infra/scripts/generate_silver_dbt_models.py -- do not hand-edit.
-- Reflects edgar_warehouse.silver_store._DDL's sec_financial_derived table. Regenerate and diff
-- before re-applying if silver_store.py's schema has changed.

{{ silver_model_config('SEC_FINANCIAL_DERIVED') }}

-- First-insert-wins (fiscal_year, form_type) from the earliest parse;
-- last-write-wins (revenue, gross_profit, ebitda, ebit, net_income, eps_diluted, total_assets, total_liabilities, total_equity, cash_and_equivalents, total_debt, current_assets, current_liabilities, accounts_receivable, inventory, selling_general_admin_expense, retained_earnings, depreciation_amortization, property_plant_equipment_net, shares_outstanding, operating_cash_flow, capex, free_cash_flow, gross_margin, ebitda_margin, net_margin, roic, roe, roa, parser_version, ingested_at) from the latest parse -- matches
-- silver_store.py's merge_financial_derived-shaped two-pass upsert
-- exactly (see generate_silver_dbt_models.py's _SPLIT_TABLES for the citation).
with first_seen as (
    select
    cik,
    accession_number,
    fiscal_period,
    period_end,
    fiscal_year,
    form_type
    from {{ source('edgartools_silver_landing', 'SEC_FINANCIAL_DERIVED') }}
    qualify row_number() over (partition by cik, accession_number, fiscal_period, period_end order by parse_sequence asc) = 1
),
last_seen as (
    select
    cik,
    accession_number,
    fiscal_period,
    period_end,
    revenue,
    gross_profit,
    ebitda,
    ebit,
    net_income,
    eps_diluted,
    total_assets,
    total_liabilities,
    total_equity,
    cash_and_equivalents,
    total_debt,
    current_assets,
    current_liabilities,
    accounts_receivable,
    inventory,
    selling_general_admin_expense,
    retained_earnings,
    depreciation_amortization,
    property_plant_equipment_net,
    shares_outstanding,
    operating_cash_flow,
    capex,
    free_cash_flow,
    gross_margin,
    ebitda_margin,
    net_margin,
    roic,
    roe,
    roa,
    parser_version,
    ingested_at
    from {{ source('edgartools_silver_landing', 'SEC_FINANCIAL_DERIVED') }}
    qualify row_number() over (partition by cik, accession_number, fiscal_period, period_end order by parse_sequence desc) = 1
)
select
    f.cik,
    f.accession_number,
    f.fiscal_period,
    f.period_end,
    f.fiscal_year,
    f.form_type,
    l.revenue,
    l.gross_profit,
    l.ebitda,
    l.ebit,
    l.net_income,
    l.eps_diluted,
    l.total_assets,
    l.total_liabilities,
    l.total_equity,
    l.cash_and_equivalents,
    l.total_debt,
    l.current_assets,
    l.current_liabilities,
    l.accounts_receivable,
    l.inventory,
    l.selling_general_admin_expense,
    l.retained_earnings,
    l.depreciation_amortization,
    l.property_plant_equipment_net,
    l.shares_outstanding,
    l.operating_cash_flow,
    l.capex,
    l.free_cash_flow,
    l.gross_margin,
    l.ebitda_margin,
    l.net_margin,
    l.roic,
    l.roe,
    l.roa,
    l.parser_version,
    l.ingested_at
from first_seen f
join last_seen l
    on f.cik = l.cik and f.accession_number = l.accession_number and f.fiscal_period = l.fiscal_period and f.period_end = l.period_end
