-- Auto-generated by infra/scripts/generate_silver_dbt_models.py -- do not hand-edit.
-- Reflects edgar_warehouse.silver_store._DDL's sec_raw_object table. Regenerate and diff
-- before re-applying if silver_store.py's schema has changed.

{{ silver_model_config('SEC_RAW_OBJECT') }}

select
    raw_object_id,
    source_type,
    cik,
    accession_number,
    form,
    source_url,
    storage_path,
    content_type,
    content_encoding,
    byte_size,
    sha256,
    fetched_at,
    http_status,
    source_last_modified,
    source_etag
from {{ source('edgartools_silver_landing', 'SEC_RAW_OBJECT') }}
qualify row_number() over (
    partition by raw_object_id
    order by parse_sequence desc
) = 1
