-- Hand-maintained. Reflects edgar_warehouse.silver_store._DDL's sec_accounting_flag table.
-- Originally generated by infra/scripts/generate_silver_dbt_models.py, deleted by
-- DuckDB Retirement Cutover Ticket 07 -- there is no regeneration step anymore;
-- edit this file directly when silver_store.py's schema changes.

{{ silver_model_config('SEC_ACCOUNTING_FLAG') }}

-- altman_z_score, beneish_m_score, piotroski_f_score: last non-null wins, not last row wins --
-- silver_store.py's merge_accounting_flags uses COALESCE(excluded.X, sec_accounting_flag.X)
-- for these three forensic score columns specifically, so an incoming NULL never clobbers an
-- existing score.
select
    cik,
    accession_number,
    fiscal_year,
    period_end,
    form_type,
    auditor_name,
    auditor_pcaob_id,
    auditor_location,
    icfr_attestation,
    auditor_changed,
    last_value(beneish_m_score ignore nulls) over (partition by cik, accession_number order by parse_sequence) as beneish_m_score,
    last_value(altman_z_score ignore nulls) over (partition by cik, accession_number order by parse_sequence) as altman_z_score,
    last_value(piotroski_f_score ignore nulls) over (partition by cik, accession_number order by parse_sequence) as piotroski_f_score,
    parser_version,
    ingested_at,
    valid_from,
    valid_to,
    is_current
from {{ source('edgartools_silver_landing', 'SEC_ACCOUNTING_FLAG') }}
qualify row_number() over (
    partition by cik, accession_number
    order by parse_sequence desc
) = 1
  and {{ silver_not_retired('sec_accounting_flag', "concat_ws('|', cik, accession_number)") }}
