-- Auto-generated by infra/scripts/generate_silver_dbt_models.py -- do not hand-edit.
-- Reflects edgar_warehouse.silver_store._DDL's sec_company_former_name table. Regenerate and diff
-- before re-applying if silver_store.py's schema has changed.

{{ silver_model_config('SEC_COMPANY_FORMER_NAME') }}

select
    cik,
    former_name,
    date_changed,
    ordinal,
    last_sync_run_id
from {{ source('edgartools_silver_landing', 'SEC_COMPANY_FORMER_NAME') }}
qualify row_number() over (
    partition by cik, ordinal
    order by parse_sequence desc
) = 1
