-- Auto-generated by infra/scripts/generate_silver_dbt_models.py -- do not hand-edit.
-- Reflects edgar_warehouse.silver_store._DDL's sec_auditor_report_evidence table. Regenerate and diff
-- before re-applying if silver_store.py's schema has changed.

{{ silver_model_config('SEC_AUDITOR_REPORT_EVIDENCE') }}

select
    accession_number,
    registrant_cik,
    form_type,
    document_name,
    audited_period_end,
    report_date,
    principal_firm_name,
    principal_firm_location,
    pcaob_firm_id,
    evidence_source,
    raw_locator,
    source_sha256,
    evidence_fingerprint,
    form_ap_filing_id,
    original_form_ap_filing_id,
    latest_amendment,
    parser_version,
    last_sync_run_id
from {{ source('edgartools_silver_landing', 'SEC_AUDITOR_REPORT_EVIDENCE') }}
qualify row_number() over (
    partition by accession_number, evidence_fingerprint
    order by parse_sequence desc
) = 1
  and {{ silver_not_retired('sec_auditor_report_evidence', "concat_ws('|', accession_number, evidence_fingerprint)") }}
