-- Hand-maintained. Reflects edgar_warehouse.silver_store._DDL's sec_company_ticker table.
-- Originally generated by infra/scripts/generate_silver_dbt_models.py, deleted by
-- DuckDB Retirement Cutover Ticket 07 -- there is no regeneration step anymore;
-- edit this file directly when silver_store.py's schema changes.

{{ silver_model_config('SEC_COMPANY_TICKER') }}

select
    cik,
    ticker,
    exchange,
    source_name,
    source_rank,
    last_sync_run_id,
    last_synced_at
from {{ source('edgartools_silver_landing', 'SEC_COMPANY_TICKER') }}
qualify row_number() over (
    partition by cik, ticker, source_name
    order by parse_sequence desc
) = 1
  and {{ silver_not_retired('sec_company_ticker', "concat_ws('|', cik, ticker, source_name)") }}
