-- Auto-generated by infra/scripts/generate_silver_dbt_models.py -- do not hand-edit.
-- Reflects edgar_warehouse.silver_store._DDL's sec_ownership_derivative_txn table. Regenerate and diff
-- before re-applying if silver_store.py's schema has changed.

{{ silver_model_config('SEC_OWNERSHIP_DERIVATIVE_TXN') }}

-- Ticket 06: materializes the issuer's cik here, via a join to
-- sec_company_filing, so downstream consumers (gold, MDM) don't each have
-- to independently know this table needs an accession-number join to
-- resolve issuer CIK (sec_adv_filing.cik-is-NULL-for-ADV-data is the same
-- failure shape this is deliberately avoiding a repeat of).
with collapsed as (
-- mdm_entity_id: last non-null wins, not last row wins --
-- see generate_silver_dbt_models.py's _COALESCE_PRESERVING_COLUMNS for the citation.
select
    accession_number,
    owner_index,
    txn_index,
    security_title,
    transaction_date,
    transaction_code,
    transaction_shares,
    transaction_price,
    acquired_disposed_code,
    shares_owned_after,
    ownership_nature,
    ownership_direct_indirect,
    conversion_or_exercise_price,
    exercise_date,
    expiration_date,
    underlying_security_title,
    underlying_security_shares,
    parser_version,
    last_sync_run_id,
    last_value(mdm_entity_id ignore nulls) over (partition by accession_number, owner_index, txn_index order by parse_sequence) as mdm_entity_id
from {{ source('edgartools_silver_landing', 'SEC_OWNERSHIP_DERIVATIVE_TXN') }}
qualify row_number() over (
    partition by accession_number, owner_index, txn_index
    order by parse_sequence desc
) = 1
)
select
    collapsed.*,
    company_filing.cik
from collapsed
left join {{ ref('sec_company_filing') }} as company_filing
    on company_filing.accession_number = collapsed.accession_number
