-- Auto-generated by infra/scripts/generate_silver_dbt_models.py -- do not hand-edit.
-- Reflects edgar_warehouse.silver_store._DDL's sec_guidance_fact table. Regenerate and diff
-- before re-applying if silver_store.py's schema has changed.

{{ silver_model_config('SEC_GUIDANCE_FACT') }}

select
    fact_key,
    cik,
    ticker,
    company_key,
    accession_number,
    metric,
    period_type,
    fiscal_year,
    fiscal_quarter,
    period_end,
    value_low,
    value_mid,
    value_high,
    unit,
    currency,
    is_non_gaap,
    as_of,
    source_system,
    source_ref,
    excerpt,
    confidence,
    parser_version,
    ingested_at
from {{ source('edgartools_silver_landing', 'SEC_GUIDANCE_FACT') }}
qualify row_number() over (
    partition by cik, metric, fiscal_year, fiscal_quarter, as_of, accession_number, is_non_gaap, source_system
    order by parse_sequence desc
) = 1
