-- Hand-maintained. Reflects the sec_thirteenf_holding landing table (infra/snowflake/sql/bootstrap/11_silver_landing_schema.sql).
-- Originally generated by infra/scripts/generate_silver_dbt_models.py, deleted by
-- DuckDB Retirement Cutover Ticket 07 -- there is no regeneration step anymore;
-- edit this file directly when that landing table changes.

{{ silver_model_config('SEC_THIRTEENF_HOLDING') }}

select
    cik,
    accession_number,
    holding_index,
    period_of_report,
    cusip,
    issuer_name,
    security_title,
    shares_held,
    market_value,
    security_class,
    put_call,
    discretion_type,
    voting_auth_sole,
    voting_auth_shared,
    voting_auth_none,
    parser_version,
    ingested_at
from {{ source('edgartools_silver_landing', 'SEC_THIRTEENF_HOLDING') }}
qualify row_number() over (
    partition by cik, accession_number, holding_index
    order by parse_sequence desc
) = 1
  and {{ silver_not_retired('sec_thirteenf_holding', "concat_ws('|', cik, accession_number, holding_index)") }}
