-- Auto-generated by infra/scripts/generate_silver_dbt_models.py -- do not hand-edit.
-- Reflects edgar_warehouse.silver_store._DDL's sec_company_submission_file table. Regenerate and diff
-- before re-applying if silver_store.py's schema has changed.

{{ silver_model_config('SEC_COMPANY_SUBMISSION_FILE') }}

select
    cik,
    file_name,
    filing_count,
    filing_from,
    filing_to,
    last_sync_run_id,
    last_synced_at
from {{ source('edgartools_silver_landing', 'SEC_COMPANY_SUBMISSION_FILE') }}
qualify row_number() over (
    partition by cik, file_name
    order by parse_sequence desc
) = 1
  and {{ silver_not_retired('sec_company_submission_file', "concat_ws('|', cik, file_name)") }}
