-- Hand-maintained. Reflects the sec_thirteenf_filing landing table (infra/snowflake/sql/bootstrap/11_silver_landing_schema.sql).
-- Originally generated by infra/scripts/generate_silver_dbt_models.py, deleted by
-- DuckDB Retirement Cutover Ticket 07 -- there is no regeneration step anymore;
-- edit this file directly when that landing table changes.

{{ silver_model_config('SEC_THIRTEENF_FILING') }}

select
    accession_number,
    cik,
    period_of_report,
    filing_date,
    form,
    amendment_type,
    confidential_omission,
    effective_status,
    superseded_by_accession,
    parser_version,
    ingested_at
from {{ source('edgartools_silver_landing', 'SEC_THIRTEENF_FILING') }}
qualify row_number() over (
    partition by accession_number
    order by parse_sequence desc
) = 1
  and {{ silver_not_retired('sec_thirteenf_filing', "concat_ws('|', accession_number)") }}
