-- Hand-maintained. Reflects the sec_current_filing_feed landing table (infra/snowflake/sql/bootstrap/11_silver_landing_schema.sql).
-- Originally generated by infra/scripts/generate_silver_dbt_models.py, deleted by
-- DuckDB Retirement Cutover Ticket 07 -- there is no regeneration step anymore;
-- edit this file directly when that landing table changes.

{{ silver_model_config('SEC_CURRENT_FILING_FEED') }}

select
    accession_number,
    cik,
    form,
    company_name,
    filing_date,
    accepted_at,
    filing_href,
    index_href,
    summary,
    source_url,
    feed_published_at,
    raw_object_id,
    last_sync_run_id,
    last_synced_at
from {{ source('edgartools_silver_landing', 'SEC_CURRENT_FILING_FEED') }}
qualify row_number() over (
    partition by accession_number
    order by parse_sequence desc
) = 1
  and {{ silver_not_retired('sec_current_filing_feed', "concat_ws('|', accession_number)") }}
