-- Hand-maintained. Reflects the sec_executive_record landing table (infra/snowflake/sql/bootstrap/11_silver_landing_schema.sql).
-- Originally generated by infra/scripts/generate_silver_dbt_models.py, deleted by
-- DuckDB Retirement Cutover Ticket 07 -- there is no regeneration step anymore;
-- edit this file directly when that landing table changes.
--
-- Deploy note (Person Consumer Contract ticket 23): the collapse key below
-- is a SQL-body change. `dbt run` will not redeploy a dynamic table for a
-- body-only change -- run
--   dbt run --select sec_executive_record executive_records --full-refresh
-- after the parser re-export lands, silver before gold.

{{ silver_model_config('SEC_EXECUTIVE_RECORD') }}

select
    cik,
    accession_number,
    fiscal_year,
    exec_name,
    exec_role,
    total_comp,
    base_salary,
    bonus,
    stock_awards,
    option_awards,
    non_equity_incentive,
    parser_version,
    ingested_at
from {{ source('edgartools_silver_landing', 'SEC_EXECUTIVE_RECORD') }}
-- Collapse key mirrors the landing dedupe key (silver_schema.py REQUIRED set:
-- cik, accession_number, fiscal_year, exec_name). A Summary Compensation
-- Table lists three fiscal years per executive; omitting fiscal_year here
-- kept only one of them once the parser started emitting the correct name on
-- every row (Person Consumer Contract ticket 23).
qualify row_number() over (
    partition by cik, accession_number, fiscal_year, exec_name
    order by parse_sequence desc
) = 1
  and {{ silver_not_retired('sec_executive_record', "concat_ws('|', cik, accession_number, fiscal_year, exec_name)") }}
