-- Hand-maintained. Reflects edgar_warehouse.silver_store._DDL's sec_guidance_fact table.
-- Originally generated by infra/scripts/generate_silver_dbt_models.py, deleted by
-- DuckDB Retirement Cutover Ticket 07 -- there is no regeneration step anymore;
-- edit this file directly when silver_store.py's schema changes.

{{ silver_model_config('SEC_GUIDANCE_FACT') }}

select
    fact_key,
    cik,
    ticker,
    company_key,
    accession_number,
    metric,
    period_type,
    fiscal_year,
    fiscal_quarter,
    period_end,
    value_low,
    value_mid,
    value_high,
    unit,
    currency,
    is_non_gaap,
    as_of,
    source_system,
    source_ref,
    excerpt,
    confidence,
    parser_version,
    ingested_at
from {{ source('edgartools_silver_landing', 'SEC_GUIDANCE_FACT') }}
qualify row_number() over (
    partition by cik, metric, fiscal_year, fiscal_quarter, as_of, accession_number, is_non_gaap, source_system
    order by parse_sequence desc
) = 1
  and {{ silver_not_retired('sec_guidance_fact', "concat_ws('|', cik, metric, fiscal_year, fiscal_quarter, as_of, accession_number, is_non_gaap, source_system)") }}
