-- Hand-maintained. Reflects the sec_auditor_report_evidence landing table (infra/snowflake/sql/bootstrap/11_silver_landing_schema.sql).
-- Originally generated by infra/scripts/generate_silver_dbt_models.py, deleted by
-- DuckDB Retirement Cutover Ticket 07 -- there is no regeneration step anymore;
-- edit this file directly when that landing table changes.

{{ silver_model_config('SEC_AUDITOR_REPORT_EVIDENCE') }}

select
    accession_number,
    registrant_cik,
    form_type,
    document_name,
    audited_period_end,
    report_date,
    principal_firm_name,
    principal_firm_location,
    pcaob_firm_id,
    evidence_source,
    raw_locator,
    source_sha256,
    evidence_fingerprint,
    form_ap_filing_id,
    original_form_ap_filing_id,
    latest_amendment,
    parser_version,
    last_sync_run_id
from {{ source('edgartools_silver_landing', 'SEC_AUDITOR_REPORT_EVIDENCE') }}
qualify row_number() over (
    partition by accession_number, evidence_fingerprint
    order by parse_sequence desc
) = 1
  and {{ silver_not_retired('sec_auditor_report_evidence', "concat_ws('|', accession_number, evidence_fingerprint)") }}
