-- Auto-generated by infra/scripts/generate_silver_dbt_models.py -- do not hand-edit.
-- Reflects edgar_warehouse.silver_store._DDL's sec_filing_text table. Regenerate and diff
-- before re-applying if silver_store.py's schema has changed.

{{ silver_model_config('SEC_FILING_TEXT') }}

select
    accession_number,
    text_version,
    source_document_name,
    text_storage_path,
    text_sha256,
    char_count,
    extracted_at
from {{ source('edgartools_silver_landing', 'SEC_FILING_TEXT') }}
qualify row_number() over (
    partition by accession_number, text_version
    order by parse_sequence desc
) = 1
