-- Hand-maintained. Reflects the sec_adv_disclosure_event landing table (infra/snowflake/sql/bootstrap/11_silver_landing_schema.sql).
-- Originally generated by infra/scripts/generate_silver_dbt_models.py, deleted by
-- DuckDB Retirement Cutover Ticket 07 -- there is no regeneration step anymore;
-- edit this file directly when that landing table changes.

{{ silver_model_config('SEC_ADV_DISCLOSURE_EVENT') }}

select
    accession_number,
    event_index,
    disclosure_category,
    event_date,
    is_reported,
    description,
    parser_version,
    last_sync_run_id
from {{ source('edgartools_silver_landing', 'SEC_ADV_DISCLOSURE_EVENT') }}
qualify row_number() over (
    partition by accession_number, event_index
    order by parse_sequence desc
) = 1
  and {{ silver_not_retired('sec_adv_disclosure_event', "concat_ws('|', accession_number, event_index)") }}
