-- Hand-maintained. Reflects the sec_company_former_name landing table (infra/snowflake/sql/bootstrap/11_silver_landing_schema.sql).
-- Originally generated by infra/scripts/generate_silver_dbt_models.py, deleted by
-- DuckDB Retirement Cutover Ticket 07 -- there is no regeneration step anymore;
-- edit this file directly when that landing table changes.

{{ silver_model_config('SEC_COMPANY_FORMER_NAME') }}

select
    cik,
    former_name,
    date_changed,
    ordinal,
    last_sync_run_id
from {{ source('edgartools_silver_landing', 'SEC_COMPANY_FORMER_NAME') }}
qualify row_number() over (
    partition by cik, ordinal
    order by parse_sequence desc
) = 1
  and {{ silver_not_retired('sec_company_former_name', "concat_ws('|', cik, ordinal)") }}
