-- Auto-generated by infra/scripts/generate_silver_dbt_models.py -- do not hand-edit.
-- Reflects edgar_warehouse.silver_store._DDL's sec_thirteenf_holding table. Regenerate and diff
-- before re-applying if silver_store.py's schema has changed.

{{ silver_model_config('SEC_THIRTEENF_HOLDING') }}

select
    cik,
    accession_number,
    holding_index,
    period_of_report,
    cusip,
    issuer_name,
    security_title,
    shares_held,
    market_value,
    security_class,
    put_call,
    discretion_type,
    voting_auth_sole,
    voting_auth_shared,
    voting_auth_none,
    parser_version,
    ingested_at
from {{ source('edgartools_silver_landing', 'SEC_THIRTEENF_HOLDING') }}
qualify row_number() over (
    partition by cik, accession_number, holding_index
    order by parse_sequence desc
) = 1
  and {{ silver_not_retired('sec_thirteenf_holding', "concat_ws('|', cik, accession_number, holding_index)") }}
