-- Hand-maintained. Reflects edgar_warehouse.silver_store._DDL's sec_adv_private_fund table.
-- Originally generated by infra/scripts/generate_silver_dbt_models.py, deleted by
-- DuckDB Retirement Cutover Ticket 07 -- there is no regeneration step anymore;
-- edit this file directly when silver_store.py's schema changes.

{{ silver_model_config('SEC_ADV_PRIVATE_FUND') }}

select
    accession_number,
    fund_index,
    filing_id,
    adviser_crd_number,
    private_fund_id,
    reference_id,
    schedule_section,
    reporting_role,
    filing_action,
    fund_name,
    fund_type,
    jurisdiction,
    aum_amount,
    effective_date,
    source_dataset_period,
    source_sha256,
    parser_version,
    last_sync_run_id,
    mdm_entity_id
from {{ source('edgartools_silver_landing', 'SEC_ADV_PRIVATE_FUND') }}
qualify row_number() over (
    partition by accession_number, fund_index
    order by parse_sequence desc
) = 1
  and {{ silver_not_retired('sec_adv_private_fund', "concat_ws('|', accession_number, fund_index)") }}
