-- Hand-maintained. Reflects edgar_warehouse.silver_store._DDL's sec_filing_attachment table.
-- Originally generated by infra/scripts/generate_silver_dbt_models.py, deleted by
-- DuckDB Retirement Cutover Ticket 07 -- there is no regeneration step anymore;
-- edit this file directly when silver_store.py's schema changes.

{{ silver_model_config('SEC_FILING_ATTACHMENT') }}

select
    accession_number,
    sequence_number,
    document_name,
    document_type,
    document_description,
    document_url,
    is_primary,
    raw_object_id,
    last_sync_run_id
from {{ source('edgartools_silver_landing', 'SEC_FILING_ATTACHMENT') }}
qualify row_number() over (
    partition by accession_number, document_name
    order by parse_sequence desc
) = 1
  and {{ silver_not_retired('sec_filing_attachment', "concat_ws('|', accession_number, document_name)") }}
