-- Hand-maintained. Reflects edgar_warehouse.silver_store._DDL's sec_financial_fact table.
-- Originally generated by infra/scripts/generate_silver_dbt_models.py, deleted by
-- DuckDB Retirement Cutover Ticket 07 -- there is no regeneration step anymore;
-- edit this file directly when silver_store.py's schema changes.

{{ silver_model_config('SEC_FINANCIAL_FACT') }}

-- First-insert-wins (fiscal_year, form_type, unit) from the earliest parse;
-- last-write-wins (value, decimals, parser_version, ingested_at, valid_from, valid_to, is_current) from the latest parse -- matches
-- silver_store.py's merge_financial_facts two-pass upsert exactly: its UPDATE SET clause
-- covers value/decimals/parser_version (+ ingested_at, not staged data) plus Ticket 33's
-- is_current/valid_to (mutable, deliberately excluded from the immutable set below).
-- fiscal_year/form_type/unit are never in that UPDATE SET (immutable, first-insert-wins).
-- valid_from is re-stamped last-write-wins by merge_financial_facts's landing_export.record
-- call as a deliberate simplification for this collapse only -- also correctly excluded
-- from the immutable set.
with first_seen as (
    select
    cik,
    accession_number,
    concept,
    fiscal_period,
    segment,
    period_end,
    period_start,
    fiscal_year,
    form_type,
    unit
    from {{ source('edgartools_silver_landing', 'SEC_FINANCIAL_FACT') }}
    qualify row_number() over (partition by cik, accession_number, concept, fiscal_period, segment, period_end, period_start order by parse_sequence asc) = 1
),
last_seen as (
    select
    cik,
    accession_number,
    concept,
    fiscal_period,
    segment,
    period_end,
    period_start,
    value,
    decimals,
    parser_version,
    ingested_at,
    valid_from,
    valid_to,
    is_current
    from {{ source('edgartools_silver_landing', 'SEC_FINANCIAL_FACT') }}
    qualify row_number() over (partition by cik, accession_number, concept, fiscal_period, segment, period_end, period_start order by parse_sequence desc) = 1
      and {{ silver_not_retired('sec_financial_fact', "concat_ws('|', cik, accession_number, concept, fiscal_period, segment, period_end, period_start)") }}
)
select
    f.cik,
    f.accession_number,
    f.concept,
    f.fiscal_period,
    f.segment,
    f.period_end,
    f.period_start,
    f.fiscal_year,
    f.form_type,
    f.unit,
    l.value,
    l.decimals,
    l.parser_version,
    l.ingested_at,
    l.valid_from,
    l.valid_to,
    l.is_current
from first_seen f
join last_seen l
    on f.cik = l.cik and f.accession_number = l.accession_number and f.concept = l.concept and f.fiscal_period = l.fiscal_period and f.segment = l.segment and f.period_end = l.period_end and f.period_start = l.period_start
