-- Hand-maintained. Reflects edgar_warehouse.silver_store._DDL's sec_company_submission_file table.
-- Originally generated by infra/scripts/generate_silver_dbt_models.py, deleted by
-- DuckDB Retirement Cutover Ticket 07 -- there is no regeneration step anymore;
-- edit this file directly when silver_store.py's schema changes.

{{ silver_model_config('SEC_COMPANY_SUBMISSION_FILE') }}

select
    cik,
    file_name,
    filing_count,
    filing_from,
    filing_to,
    last_sync_run_id,
    last_synced_at
from {{ source('edgartools_silver_landing', 'SEC_COMPANY_SUBMISSION_FILE') }}
qualify row_number() over (
    partition by cik, file_name
    order by parse_sequence desc
) = 1
  and {{ silver_not_retired('sec_company_submission_file', "concat_ws('|', cik, file_name)") }}
