-- Auto-generated by infra/scripts/generate_silver_dbt_models.py -- do not hand-edit.
-- Reflects edgar_warehouse.silver_store._DDL's sec_adv_filing table. Regenerate and diff
-- before re-applying if silver_store.py's schema has changed.

{{ silver_model_config('SEC_ADV_FILING') }}

select
    accession_number,
    cik,
    form,
    adviser_name,
    sec_file_number,
    crd_number,
    effective_date,
    filing_status,
    filing_action,
    source_format,
    parser_version,
    last_sync_run_id
from {{ source('edgartools_silver_landing', 'SEC_ADV_FILING') }}
qualify row_number() over (
    partition by accession_number
    order by parse_sequence desc
) = 1
