-- Auto-generated by infra/scripts/generate_silver_dbt_models.py -- do not hand-edit.
-- Reflects edgar_warehouse.silver_store._DDL's sec_thirteenf_filing table. Regenerate and diff
-- before re-applying if silver_store.py's schema has changed.

{{ silver_model_config('SEC_THIRTEENF_FILING') }}

select
    accession_number,
    cik,
    period_of_report,
    filing_date,
    form,
    amendment_type,
    confidential_omission,
    effective_status,
    superseded_by_accession,
    parser_version,
    ingested_at
from {{ source('edgartools_silver_landing', 'SEC_THIRTEENF_FILING') }}
qualify row_number() over (
    partition by accession_number
    order by parse_sequence desc
) = 1
