-- Auto-generated by infra/scripts/generate_silver_dbt_models.py -- do not hand-edit.
-- Reflects edgar_warehouse.silver_store._DDL's sec_ownership_reporting_owner table. Regenerate and diff
-- before re-applying if silver_store.py's schema has changed.

{{ silver_model_config('SEC_OWNERSHIP_REPORTING_OWNER') }}

-- Ticket 06: materializes the issuer's cik here, via a join to
-- sec_company_filing, so downstream consumers (gold, MDM) don't each have
-- to independently know this table needs an accession-number join to
-- resolve issuer CIK (sec_adv_filing.cik-is-NULL-for-ADV-data is the same
-- failure shape this is deliberately avoiding a repeat of).
with collapsed as (
select
    accession_number,
    owner_index,
    owner_cik,
    owner_name,
    is_director,
    is_officer,
    is_ten_percent_owner,
    is_other,
    officer_title,
    parser_version,
    last_sync_run_id,
    mdm_entity_id
from {{ source('edgartools_silver_landing', 'SEC_OWNERSHIP_REPORTING_OWNER') }}
qualify row_number() over (
    partition by accession_number, owner_index
    order by parse_sequence desc
) = 1
  and {{ silver_not_retired('sec_ownership_reporting_owner', "concat_ws('|', accession_number, owner_index)") }}
)
select
    collapsed.*,
    company_filing.cik
from collapsed
left join {{ ref('sec_company_filing') }} as company_filing
    on company_filing.accession_number = collapsed.accession_number
