-- Hand-maintained. Reflects the sec_adv_office landing table (infra/snowflake/sql/bootstrap/11_silver_landing_schema.sql).
-- Originally generated by infra/scripts/generate_silver_dbt_models.py, deleted by
-- DuckDB Retirement Cutover Ticket 07 -- there is no regeneration step anymore;
-- edit this file directly when that landing table changes.

{{ silver_model_config('SEC_ADV_OFFICE') }}

select
    accession_number,
    office_index,
    office_name,
    city,
    state_or_country,
    country,
    is_headquarters,
    parser_version,
    last_sync_run_id
from {{ source('edgartools_silver_landing', 'SEC_ADV_OFFICE') }}
qualify row_number() over (
    partition by accession_number, office_index
    order by parse_sequence desc
) = 1
  and {{ silver_not_retired('sec_adv_office', "concat_ws('|', accession_number, office_index)") }}
