-- Auto-generated by infra/scripts/generate_silver_dbt_models.py -- do not hand-edit.
-- Reflects edgar_warehouse.silver_store._DDL's sec_accounting_flag table. Regenerate and diff
-- before re-applying if silver_store.py's schema has changed.

{{ silver_model_config('SEC_ACCOUNTING_FLAG') }}

select
    cik,
    accession_number,
    fiscal_year,
    period_end,
    form_type,
    auditor_name,
    auditor_pcaob_id,
    auditor_location,
    icfr_attestation,
    auditor_changed,
    beneish_m_score,
    altman_z_score,
    piotroski_f_score,
    parser_version,
    ingested_at
from {{ source('edgartools_silver_landing', 'SEC_ACCOUNTING_FLAG') }}
qualify row_number() over (
    partition by cik, accession_number
    order by parse_sequence desc
) = 1
