-- Hand-maintained. Reflects the sec_earnings_release landing table (infra/snowflake/sql/bootstrap/11_silver_landing_schema.sql).
-- Originally generated by infra/scripts/generate_silver_dbt_models.py, deleted by
-- DuckDB Retirement Cutover Ticket 07 -- there is no regeneration step anymore;
-- edit this file directly when that landing table changes.

{{ silver_model_config('SEC_EARNINGS_RELEASE') }}

select
    cik,
    accession_number,
    filing_date,
    fiscal_year,
    fiscal_quarter,
    period_end,
    revenue_gaap,
    net_income_gaap,
    eps_gaap_diluted,
    has_non_gaap,
    has_guidance,
    parser_version,
    ingested_at
from {{ source('edgartools_silver_landing', 'SEC_EARNINGS_RELEASE') }}
qualify row_number() over (
    partition by cik, accession_number
    order by parse_sequence desc
) = 1
  and {{ silver_not_retired('sec_earnings_release', "concat_ws('|', cik, accession_number)") }}
