-- Auto-generated by infra/scripts/generate_silver_dbt_models.py -- do not hand-edit.
-- Reflects edgar_warehouse.silver_store._DDL's sec_filing_attachment table. Regenerate and diff
-- before re-applying if silver_store.py's schema has changed.

{{ silver_model_config('SEC_FILING_ATTACHMENT') }}

select
    accession_number,
    sequence_number,
    document_name,
    document_type,
    document_description,
    document_url,
    is_primary,
    raw_object_id,
    last_sync_run_id
from {{ source('edgartools_silver_landing', 'SEC_FILING_ATTACHMENT') }}
qualify row_number() over (
    partition by accession_number, document_name
    order by parse_sequence desc
) = 1
