-- Snowflake MDM mirror schema (EDGARTOOLS_PROD.MDM) bootstrap.
--
-- Generated by infra/scripts/generate_mdm_mirror_ddl.py -- regenerate with:
--   MDM_DATABASE_URL=sqlite:///:memory: uv run python \
--       infra/scripts/generate_mdm_mirror_ddl.py > infra/snowflake/sql/bootstrap/09_mdm_mirror_schema.sql
--
-- This file is committed as a readable snapshot; the generator (reading
-- edgar_warehouse.mdm.database's SQLAlchemy models) is the source of truth.
-- Regenerate and diff before re-applying if the MDM models have changed.
--
-- Root cause this file exists to fix: EDGARTOOLS_PROD.MDM (the mirror
-- edgar_warehouse.mdm.export._build_snowflake_mirror_writer writes to, and
-- mdm publish-relationships reads from -- see docs/prod-mdm-snowflake-graph-first-load.md)
-- was originally created by a one-off, uncommitted manual shell session on
-- 2026-06-22. It had no script, so when the platform's Snowflake account was
-- rebuilt for the go-live cutover, this step -- unlike every other piece
-- (gold, source, loader role, dashboards, Neo4j app), all Terraform/scripted
-- -- had nothing to re-run. The schema came back empty (created 2026-08-07 by
-- ACCOUNTADMIN, zero tables) and `mdm publish` failed with "Object
-- 'EDGARTOOLS_PROD.MDM.MDM_ENTITY' does not exist or not authorized."
--
-- Run once per environment (idempotent, safe to re-run):
--   snow sql --connection edgartools-prod -f infra/snowflake/sql/bootstrap/09_mdm_mirror_schema.sql
--
-- Every statement is CREATE ... IF NOT EXISTS or an additive GRANT (no
-- REVOKE, no DROP, no OWNERSHIP transfer -- see CLAUDE.md's
-- "manifest-pipeline ownership" incident for why GRANT OWNERSHIP ... REVOKE
-- CURRENT GRANTS silently strips unrelated grants).
--
-- Ticket 30 (change-propagation map) follow-up, 2026-08-26: this schema is
-- self-contained (nothing here grants on an object outside it), so it runs
-- under the dedicated EDGARTOOLS_PROD_INSTALLER role
-- (infra/snowflake/sql/bootstrap/19_installer_role.sql) instead of
-- ACCOUNTADMIN -- see that file for the scope this role does and does not
-- cover. Must run after 19_installer_role.sql.

USE ROLE EDGARTOOLS_PROD_INSTALLER;
USE DATABASE EDGARTOOLS_PROD;
CREATE SCHEMA IF NOT EXISTS MDM;
USE SCHEMA MDM;

CREATE TABLE IF NOT EXISTS mdm_entity (
	entity_id VARCHAR(36) NOT NULL,
	entity_type TEXT NOT NULL,
	is_quarantined BOOLEAN DEFAULT FALSE NOT NULL,
	resolution_method TEXT,
	confidence FLOAT,
	valid_from TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP() NOT NULL,
	valid_to TIMESTAMP WITH TIME ZONE,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP() NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP() NOT NULL,
	version INTEGER DEFAULT 1 NOT NULL,
	PRIMARY KEY (entity_id),
	CONSTRAINT ck_mdm_entity_type CHECK (entity_type IN ('company','adviser','person','security','fund','audit_firm'))
);

CREATE TABLE IF NOT EXISTS mdm_entity_type_definition (
	entity_type TEXT NOT NULL,
	neo4j_label TEXT NOT NULL,
	domain_table TEXT NOT NULL,
	api_path_prefix TEXT NOT NULL,
	primary_id_field TEXT NOT NULL,
	display_name TEXT NOT NULL,
	is_active BOOLEAN DEFAULT TRUE NOT NULL,
	PRIMARY KEY (entity_type),
	UNIQUE (neo4j_label)
);

CREATE TABLE IF NOT EXISTS mdm_field_survivorship (
	rule_id VARCHAR(36) NOT NULL,
	entity_type TEXT NOT NULL,
	field_name TEXT NOT NULL,
	rule_type TEXT NOT NULL,
	source_system TEXT,
	preferred_source_order VARIANT,
	notes TEXT,
	is_active BOOLEAN DEFAULT TRUE NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP() NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP() NOT NULL,
	PRIMARY KEY (rule_id),
	CONSTRAINT ck_field_survivorship_rule_type CHECK (rule_type IN ('source_priority','most_recent','immutable','highest_source_rank','custom')),
	CONSTRAINT uq_field_survivorship UNIQUE (entity_type, field_name)
);

CREATE TABLE IF NOT EXISTS mdm_match_threshold (
	rule_id VARCHAR(36) NOT NULL,
	entity_type TEXT NOT NULL,
	match_method TEXT NOT NULL,
	auto_merge_min FLOAT NOT NULL,
	review_min FLOAT NOT NULL,
	is_active BOOLEAN DEFAULT TRUE NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP() NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP() NOT NULL,
	PRIMARY KEY (rule_id),
	CONSTRAINT ck_match_threshold_method CHECK (match_method IN ('cik_exact','fuzzy_name','ml_splink')),
	CONSTRAINT uq_match_threshold UNIQUE (entity_type, match_method)
);

CREATE TABLE IF NOT EXISTS mdm_normalization_rule (
	rule_id VARCHAR(36) NOT NULL,
	rule_type TEXT NOT NULL,
	input_value TEXT NOT NULL,
	canonical_value TEXT NOT NULL,
	entity_type TEXT,
	is_active BOOLEAN DEFAULT TRUE NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP() NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP() NOT NULL,
	PRIMARY KEY (rule_id),
	CONSTRAINT ck_normalization_rule_type CHECK (rule_type IN ('legal_suffix','title_alias','address_abbr','state_code','country_code')),
	CONSTRAINT uq_normalization_rule UNIQUE (rule_type, input_value)
);

CREATE TABLE IF NOT EXISTS mdm_source_priority (
	rule_id VARCHAR(36) NOT NULL,
	entity_type TEXT NOT NULL,
	source_system TEXT NOT NULL,
	priority INTEGER NOT NULL,
	is_active BOOLEAN DEFAULT TRUE NOT NULL,
	description TEXT,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP() NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP() NOT NULL,
	PRIMARY KEY (rule_id),
	CONSTRAINT uq_source_priority UNIQUE (entity_type, source_system)
);

CREATE TABLE IF NOT EXISTS mdm_adviser (
	entity_id VARCHAR(36) NOT NULL,
	cik BIGINT,
	crd_number TEXT,
	sec_file_number TEXT,
	canonical_name TEXT NOT NULL,
	adviser_type TEXT,
	hq_city TEXT,
	hq_state TEXT,
	aum_total NUMERIC,
	fund_count INTEGER,
	linked_company_entity_id VARCHAR(36),
	valid_from TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP() NOT NULL,
	valid_to TIMESTAMP WITH TIME ZONE,
	PRIMARY KEY (entity_id),
	FOREIGN KEY(entity_id) REFERENCES mdm_entity (entity_id),
	UNIQUE (crd_number),
	FOREIGN KEY(linked_company_entity_id) REFERENCES mdm_entity (entity_id)
);

CREATE TABLE IF NOT EXISTS mdm_change_log (
	change_id VARCHAR(36) NOT NULL,
	entity_id VARCHAR(36) NOT NULL,
	entity_type TEXT NOT NULL,
	changed_fields VARIANT,
	run_id TEXT,
	changed_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP() NOT NULL,
	exported_at TIMESTAMP WITH TIME ZONE,
	PRIMARY KEY (change_id),
	FOREIGN KEY(entity_id) REFERENCES mdm_entity (entity_id)
);

CREATE TABLE IF NOT EXISTS mdm_company (
	entity_id VARCHAR(36) NOT NULL,
	cik BIGINT,
	canonical_name TEXT NOT NULL,
	ein TEXT,
	sic_code TEXT,
	sic_description TEXT,
	state_of_incorporation TEXT,
	fiscal_year_end TEXT,
	ticker TEXT,
	primary_ticker TEXT,
	primary_exchange TEXT,
	tracking_status TEXT,
	parent_company_entity_id VARCHAR(36),
	valid_from TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP() NOT NULL,
	valid_to TIMESTAMP WITH TIME ZONE,
	PRIMARY KEY (entity_id),
	FOREIGN KEY(entity_id) REFERENCES mdm_entity (entity_id),
	UNIQUE (cik),
	FOREIGN KEY(parent_company_entity_id) REFERENCES mdm_entity (entity_id)
);

CREATE TABLE IF NOT EXISTS mdm_entity_attribute_stage (
	stage_id VARCHAR(36) NOT NULL,
	entity_id VARCHAR(36) NOT NULL,
	source_system TEXT NOT NULL,
	source_id TEXT NOT NULL,
	field_name TEXT NOT NULL,
	field_value TEXT,
	global_priority INTEGER NOT NULL,
	effective_date DATE,
	was_selected BOOLEAN DEFAULT FALSE NOT NULL,
	loaded_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP() NOT NULL,
	PRIMARY KEY (stage_id),
	FOREIGN KEY(entity_id) REFERENCES mdm_entity (entity_id)
);

CREATE TABLE IF NOT EXISTS mdm_fund (
	entity_id VARCHAR(36) NOT NULL,
	adviser_entity_id VARCHAR(36),
	private_fund_id TEXT,
	canonical_name TEXT NOT NULL,
	fund_type TEXT,
	jurisdiction TEXT,
	aum_amount NUMERIC,
	aum_as_of_date DATE,
	valid_from TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP() NOT NULL,
	valid_to TIMESTAMP WITH TIME ZONE,
	PRIMARY KEY (entity_id),
	FOREIGN KEY(entity_id) REFERENCES mdm_entity (entity_id),
	UNIQUE (private_fund_id),
	FOREIGN KEY(adviser_entity_id) REFERENCES mdm_entity (entity_id)
);

CREATE TABLE IF NOT EXISTS mdm_match_review (
	review_id VARCHAR(36) NOT NULL,
	entity_id_a VARCHAR(36) NOT NULL,
	entity_id_b VARCHAR(36) NOT NULL,
	match_score FLOAT NOT NULL,
	match_evidence VARIANT,
	status TEXT DEFAULT 'pending' NOT NULL,
	reviewed_by TEXT,
	reviewed_at TIMESTAMP WITH TIME ZONE,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP() NOT NULL,
	PRIMARY KEY (review_id),
	CONSTRAINT ck_match_review_status CHECK (status IN ('pending','accepted','rejected','quarantined')),
	FOREIGN KEY(entity_id_a) REFERENCES mdm_entity (entity_id),
	FOREIGN KEY(entity_id_b) REFERENCES mdm_entity (entity_id)
);

CREATE TABLE IF NOT EXISTS mdm_person (
	entity_id VARCHAR(36) NOT NULL,
	owner_cik BIGINT,
	canonical_name TEXT NOT NULL,
	name_variants VARIANT,
	primary_role TEXT,
	role_titles VARIANT,
	affiliated_company_count INTEGER DEFAULT 0 NOT NULL,
	valid_from TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP() NOT NULL,
	valid_to TIMESTAMP WITH TIME ZONE,
	PRIMARY KEY (entity_id),
	FOREIGN KEY(entity_id) REFERENCES mdm_entity (entity_id)
);

CREATE TABLE IF NOT EXISTS mdm_relationship_type (
	rel_type_id VARCHAR(36) NOT NULL,
	rel_type_name TEXT NOT NULL,
	source_node_type TEXT NOT NULL,
	target_node_type TEXT NOT NULL,
	direction TEXT NOT NULL,
	is_temporal BOOLEAN DEFAULT TRUE NOT NULL,
	dedup_key_fields VARIANT,
	merge_strategy TEXT DEFAULT 'extend_temporal' NOT NULL,
	description TEXT,
	is_active BOOLEAN DEFAULT TRUE NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP(),
	PRIMARY KEY (rel_type_id),
	UNIQUE (rel_type_name),
	CONSTRAINT ck_rel_type_direction CHECK (direction IN ('outbound','inbound','both')),
	CONSTRAINT ck_rel_type_merge_strategy CHECK (merge_strategy IN ('extend_temporal','always_insert','replace')),
	FOREIGN KEY(source_node_type) REFERENCES mdm_entity_type_definition (entity_type),
	FOREIGN KEY(target_node_type) REFERENCES mdm_entity_type_definition (entity_type)
);

CREATE TABLE IF NOT EXISTS mdm_security (
	entity_id VARCHAR(36) NOT NULL,
	issuer_entity_id VARCHAR(36),
	canonical_title TEXT NOT NULL,
	security_type TEXT,
	security_class TEXT,
	cusip TEXT,
	isin TEXT,
	valid_from TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP() NOT NULL,
	valid_to TIMESTAMP WITH TIME ZONE,
	PRIMARY KEY (entity_id),
	FOREIGN KEY(entity_id) REFERENCES mdm_entity (entity_id),
	FOREIGN KEY(issuer_entity_id) REFERENCES mdm_entity (entity_id)
);

CREATE TABLE IF NOT EXISTS mdm_source_ref (
	entity_id VARCHAR(36) NOT NULL,
	source_system TEXT NOT NULL,
	source_id TEXT NOT NULL,
	source_priority INTEGER NOT NULL,
	confidence FLOAT,
	matched_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP() NOT NULL,
	PRIMARY KEY (entity_id, source_system, source_id),
	FOREIGN KEY(entity_id) REFERENCES mdm_entity (entity_id)
);

CREATE TABLE IF NOT EXISTS mdm_relationship_instance (
	instance_id VARCHAR(36) NOT NULL,
	relationship_id VARCHAR(36) NOT NULL,
	rel_type_id VARCHAR(36) NOT NULL,
	source_entity_id VARCHAR(36) NOT NULL,
	target_entity_id VARCHAR(36) NOT NULL,
	properties VARIANT,
	effective_from DATE,
	effective_to DATE,
	valid_from_date DATE,
	valid_to_date DATE,
	date_provenance TEXT DEFAULT 'unknown' NOT NULL,
	relationship_kind TEXT DEFAULT 'direct' NOT NULL,
	source_system TEXT,
	source_accession TEXT,
	run_id TEXT,
	source_evidence VARIANT,
	superseded_by_version_id VARCHAR(36),
	quarantined BOOLEAN DEFAULT FALSE NOT NULL,
	quarantine_reason TEXT,
	graph_synced_at TIMESTAMP WITH TIME ZONE,
	is_active BOOLEAN DEFAULT TRUE NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP(),
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP(),
	PRIMARY KEY (instance_id),
	CONSTRAINT ck_rel_instance_valid_interval CHECK (valid_from_date IS NULL OR valid_to_date IS NULL OR valid_to_date > valid_from_date),
	CONSTRAINT ck_rel_instance_date_provenance CHECK (date_provenance IN ('reported','filing_date_proxy','unknown')),
	CONSTRAINT ck_rel_instance_relationship_kind CHECK (relationship_kind IN ('direct','derived')),
	FOREIGN KEY(rel_type_id) REFERENCES mdm_relationship_type (rel_type_id),
	FOREIGN KEY(source_entity_id) REFERENCES mdm_entity (entity_id),
	FOREIGN KEY(target_entity_id) REFERENCES mdm_entity (entity_id),
	FOREIGN KEY(superseded_by_version_id) REFERENCES mdm_relationship_instance (instance_id)
);

CREATE TABLE IF NOT EXISTS mdm_relationship_property_def (
	prop_def_id VARCHAR(36) NOT NULL,
	rel_type_id VARCHAR(36) NOT NULL,
	property_name TEXT NOT NULL,
	data_type TEXT NOT NULL,
	is_required BOOLEAN DEFAULT FALSE NOT NULL,
	default_value TEXT,
	description TEXT,
	PRIMARY KEY (prop_def_id),
	CONSTRAINT ck_prop_def_data_type CHECK (data_type IN ('text','float','date','boolean','integer')),
	CONSTRAINT uq_prop_def UNIQUE (rel_type_id, property_name),
	FOREIGN KEY(rel_type_id) REFERENCES mdm_relationship_type (rel_type_id)
);

CREATE TABLE IF NOT EXISTS mdm_relationship_source_mapping (
	mapping_id VARCHAR(36) NOT NULL,
	rel_type_id VARCHAR(36) NOT NULL,
	source_system TEXT NOT NULL,
	source_table TEXT NOT NULL,
	source_entity_field TEXT NOT NULL,
	target_entity_field TEXT NOT NULL,
	source_entity_type TEXT NOT NULL,
	target_entity_type TEXT NOT NULL,
	property_mapping VARIANT NOT NULL,
	effective_from_field TEXT,
	effective_to_field TEXT,
	filter_condition VARIANT,
	is_active BOOLEAN DEFAULT TRUE NOT NULL,
	description TEXT,
	PRIMARY KEY (mapping_id),
	CONSTRAINT uq_rel_source_mapping UNIQUE (rel_type_id, source_system, source_table),
	FOREIGN KEY(rel_type_id) REFERENCES mdm_relationship_type (rel_type_id),
	FOREIGN KEY(source_entity_type) REFERENCES mdm_entity_type_definition (entity_type),
	FOREIGN KEY(target_entity_type) REFERENCES mdm_entity_type_definition (entity_type)
);

ALTER TABLE mdm_change_log ADD COLUMN IF NOT EXISTS run_id TEXT;
ALTER TABLE mdm_relationship_instance ADD COLUMN IF NOT EXISTS run_id TEXT;

-- Grant the loader role (the role edgar_warehouse.mdm.export.py's
-- mirror_writer actually authenticates as) DML + future-table access.
GRANT USAGE ON SCHEMA EDGARTOOLS_PROD.MDM TO ROLE EDGARTOOLS_PROD_LOADER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA EDGARTOOLS_PROD.MDM TO ROLE EDGARTOOLS_PROD_LOADER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA EDGARTOOLS_PROD.MDM TO ROLE EDGARTOOLS_PROD_LOADER;
