-- Snowflake silver landing schema (EDGARTOOLS_PROD.EDGARTOOLS_SILVER_LANDING) bootstrap.
--
-- Generated by infra/scripts/generate_silver_landing_ddl.py -- regenerate with:
--   uv run python infra/scripts/generate_silver_landing_ddl.py \
--       > infra/snowflake/sql/bootstrap/11_silver_landing_schema.sql
--
-- This file is committed as a readable snapshot; the generator (reflecting
-- edgar_warehouse.silver_store._DDL via in-memory DuckDB introspection -- see
-- the generator's own module docstring for why that mechanism, not
-- SQLAlchemy reflection, is used here) is the source of truth. Regenerate
-- and diff before re-applying if silver_store.py's schema has changed.
--
-- Root cause this file exists to prevent, named per the migration map's
-- standing requirement (not generic caution): the MDM Snowflake mirror
-- schema was silently lost on a prior account cutover because it was
-- provisioned by a one-off, uncommitted manual shell session with no script
-- to re-run (CLAUDE.md, "MDM Snowflake mirror schema lost on cutover"). This
-- file is the silver-landing-zone equivalent of
-- infra/snowflake/sql/bootstrap/09_mdm_mirror_schema.sql, written before
-- this migration's first real provisioning step is ever run by hand, so the
-- same failure shape cannot repeat here.
--
-- Full design context: .scratch/silver-snowflake-migration/map.md,
-- Tickets 01 (model structure), 02 (parse_sequence/concurrency), and 05
-- (this ticket -- ownership/grants).
--
-- Run once per environment (idempotent, safe to re-run):
--   snow sql --connection edgartools-prod -f infra/snowflake/sql/bootstrap/11_silver_landing_schema.sql
--
-- Every statement is CREATE ... IF NOT EXISTS or an additive GRANT (no
-- REVOKE, no DROP, no OWNERSHIP transfer -- see CLAUDE.md's
-- "Manifest-pipeline ownership + cursor-syntax incident" for why
-- GRANT OWNERSHIP ... REVOKE CURRENT GRANTS silently strips unrelated
-- grants). Ownership: the schema, sequence, and every table are created
-- under ACCOUNTADMIN and then granted to EDGARTOOLS_PROD_LOADER -- the
-- platform's single existing dedicated pipeline-object owner, already
-- holding gold's 20 dynamic tables, the MDM mirror's 19 tables, and the
-- graph schema. Reused deliberately rather than minting a new role, per
-- this ticket's decision: a second pipeline-object owner would repeat the
-- exact ownership fragmentation the loader-role policy was created to
-- eliminate.
--
-- Deliberately narrower grant than the MDM mirror's SELECT/INSERT/UPDATE/
-- DELETE: only SELECT + INSERT. Landing is append-only by design (silver-
-- snowflake-migration map, Ticket 01) -- granting UPDATE/DELETE would be a
-- standing capability with no legitimate caller, not an oversight.
--
-- Excluded from this schema: pipeline_run_lease. It is dual-listed in
-- edgar_warehouse.silver_protection.PROTECTED_TABLE_REGISTRY, but only
-- because it needed to survive the OLD whole-file candidate/canonical merge
-- -- a mechanism Ticket 02 retired outright. It's cross-execution lease
-- state (sec_fetch_active), not domain data, and it isn't append-only (a
-- lease's whole point is a mutable current status) -- it stays exactly
-- where it is today (silver_store.py's local DuckDB), unaffected by this
-- migration.
--
-- Included beyond the registry: sec_guidance_fact_reject. It's real domain
-- data (a quarantine log) that Ticket 01's Answer said explicitly stays
-- append/log-shaped in silver too, but it was never in
-- PROTECTED_TABLE_REGISTRY to begin with -- that registry was scoped to the
-- OLD cross-writer merge eligibility, and this table was deliberately
-- excluded from THAT (it has no natural key to merge on). Scoping this
-- generator strictly by registry membership silently missed it; caught
-- while building the downstream dbt silver-model generator and fixed here.

USE ROLE ACCOUNTADMIN;
USE DATABASE EDGARTOOLS_PROD;
CREATE SCHEMA IF NOT EXISTS EDGARTOOLS_SILVER_LANDING;
USE SCHEMA EDGARTOOLS_SILVER_LANDING;

-- Single shared sequence: row-level parse_sequence assignment, safe under any
-- concurrency (Snowflake's metadata layer coordinates allocation globally --
-- silver-snowflake-migration map, Ticket 02's decision). One sequence across
-- every landing table, not one per table -- the window-function collapse that
-- reads this later partitions by business key per table already, so a single
-- monotonically increasing value remains a valid ordering marker regardless of
-- which table a row belongs to.
CREATE SEQUENCE IF NOT EXISTS PARSE_SEQ START = 1 INCREMENT = 1;

CREATE TABLE IF NOT EXISTS sec_accounting_flag (
    cik BIGINT NOT NULL,
    accession_number TEXT NOT NULL,
    fiscal_year INTEGER NOT NULL,
    period_end DATE,
    form_type TEXT NOT NULL,
    auditor_name TEXT,
    auditor_pcaob_id TEXT,
    auditor_location TEXT,
    icfr_attestation BOOLEAN,
    auditor_changed BOOLEAN,
    beneish_m_score DOUBLE,
    altman_z_score DOUBLE,
    piotroski_f_score INTEGER,
    parser_version TEXT,
    ingested_at TIMESTAMP_TZ,
    parse_sequence BIGINT DEFAULT PARSE_SEQ.NEXTVAL
    , PRIMARY KEY (parse_sequence)
);
ALTER TABLE sec_accounting_flag ALTER COLUMN parse_sequence DROP NOT NULL;

CREATE TABLE IF NOT EXISTS sec_adv_disclosure_event (
    accession_number TEXT NOT NULL,
    event_index SMALLINT NOT NULL,
    disclosure_category TEXT,
    event_date DATE,
    is_reported BOOLEAN,
    description TEXT,
    parser_version TEXT,
    last_sync_run_id TEXT,
    parse_sequence BIGINT DEFAULT PARSE_SEQ.NEXTVAL
    , PRIMARY KEY (parse_sequence)
);
ALTER TABLE sec_adv_disclosure_event ALTER COLUMN parse_sequence DROP NOT NULL;

CREATE TABLE IF NOT EXISTS sec_adv_filing (
    accession_number TEXT NOT NULL,
    cik BIGINT,
    form TEXT,
    adviser_name TEXT,
    sec_file_number TEXT,
    crd_number TEXT,
    effective_date DATE,
    filing_status TEXT,
    filing_action TEXT,
    source_format TEXT,
    parser_version TEXT,
    last_sync_run_id TEXT,
    mdm_entity_id TEXT,
    parse_sequence BIGINT DEFAULT PARSE_SEQ.NEXTVAL
    , PRIMARY KEY (parse_sequence)
);
ALTER TABLE sec_adv_filing ALTER COLUMN parse_sequence DROP NOT NULL;

CREATE TABLE IF NOT EXISTS sec_adv_firm_roster (
    adviser_crd_number TEXT NOT NULL,
    dataset_period TEXT NOT NULL,
    private_funds_reported BOOLEAN,
    private_fund_count_7b1 BIGINT,
    any_hedge_funds BOOLEAN,
    hedge_fund_count BIGINT,
    any_pe_funds BOOLEAN,
    pe_fund_count BIGINT,
    total_gross_assets_private_funds NUMBER(28,2),
    private_fund_count_7b2 BIGINT,
    source_sha256 TEXT,
    parser_version TEXT,
    last_sync_run_id TEXT,
    parse_sequence BIGINT DEFAULT PARSE_SEQ.NEXTVAL
    , PRIMARY KEY (parse_sequence)
);
ALTER TABLE sec_adv_firm_roster ALTER COLUMN parse_sequence DROP NOT NULL;

CREATE TABLE IF NOT EXISTS sec_adv_office (
    accession_number TEXT NOT NULL,
    office_index SMALLINT NOT NULL,
    office_name TEXT,
    city TEXT,
    state_or_country TEXT,
    country TEXT,
    is_headquarters BOOLEAN,
    parser_version TEXT,
    last_sync_run_id TEXT,
    parse_sequence BIGINT DEFAULT PARSE_SEQ.NEXTVAL
    , PRIMARY KEY (parse_sequence)
);
ALTER TABLE sec_adv_office ALTER COLUMN parse_sequence DROP NOT NULL;

CREATE TABLE IF NOT EXISTS sec_adv_private_fund (
    accession_number TEXT NOT NULL,
    fund_index BIGINT NOT NULL,
    filing_id TEXT,
    adviser_crd_number TEXT,
    private_fund_id TEXT,
    reference_id TEXT,
    schedule_section TEXT,
    reporting_role TEXT,
    filing_action TEXT,
    fund_name TEXT,
    fund_type TEXT,
    jurisdiction TEXT,
    aum_amount NUMBER(28,2),
    effective_date DATE,
    source_dataset_period TEXT,
    source_sha256 TEXT,
    parser_version TEXT,
    last_sync_run_id TEXT,
    mdm_entity_id TEXT,
    parse_sequence BIGINT DEFAULT PARSE_SEQ.NEXTVAL
    , PRIMARY KEY (parse_sequence)
);
ALTER TABLE sec_adv_private_fund ALTER COLUMN parse_sequence DROP NOT NULL;

CREATE TABLE IF NOT EXISTS sec_auditor_report_evidence (
    accession_number TEXT NOT NULL,
    registrant_cik BIGINT,
    form_type TEXT,
    document_name TEXT,
    audited_period_end DATE,
    report_date DATE,
    principal_firm_name TEXT,
    principal_firm_location TEXT,
    pcaob_firm_id TEXT,
    evidence_source TEXT,
    raw_locator TEXT,
    source_sha256 TEXT,
    evidence_fingerprint TEXT NOT NULL,
    form_ap_filing_id TEXT,
    original_form_ap_filing_id TEXT,
    latest_amendment BOOLEAN,
    parser_version TEXT,
    last_sync_run_id TEXT,
    parse_sequence BIGINT DEFAULT PARSE_SEQ.NEXTVAL
    , PRIMARY KEY (parse_sequence)
);
ALTER TABLE sec_auditor_report_evidence ALTER COLUMN parse_sequence DROP NOT NULL;

CREATE TABLE IF NOT EXISTS sec_company (
    cik BIGINT NOT NULL,
    entity_name TEXT,
    entity_type TEXT,
    sic TEXT,
    sic_description TEXT,
    state_of_incorporation TEXT,
    state_of_incorporation_desc TEXT,
    fiscal_year_end TEXT,
    ein TEXT,
    description TEXT,
    category TEXT,
    first_sync_run_id TEXT,
    last_sync_run_id TEXT,
    last_synced_at TIMESTAMP_TZ,
    mdm_entity_id TEXT,
    parse_sequence BIGINT DEFAULT PARSE_SEQ.NEXTVAL
    , PRIMARY KEY (parse_sequence)
);
ALTER TABLE sec_company ALTER COLUMN parse_sequence DROP NOT NULL;

CREATE TABLE IF NOT EXISTS sec_company_address (
    cik BIGINT NOT NULL,
    address_type TEXT NOT NULL,
    street1 TEXT,
    street2 TEXT,
    city TEXT,
    state_or_country TEXT,
    zip_code TEXT,
    country TEXT,
    last_sync_run_id TEXT,
    last_synced_at TIMESTAMP_TZ,
    parse_sequence BIGINT DEFAULT PARSE_SEQ.NEXTVAL
    , PRIMARY KEY (parse_sequence)
);
ALTER TABLE sec_company_address ALTER COLUMN parse_sequence DROP NOT NULL;

CREATE TABLE IF NOT EXISTS sec_company_filing (
    accession_number TEXT NOT NULL,
    cik BIGINT,
    form TEXT,
    filing_date DATE,
    report_date DATE,
    acceptance_datetime TEXT,
    act TEXT,
    file_number TEXT,
    film_number TEXT,
    items TEXT,
    size BIGINT,
    is_xbrl BOOLEAN,
    is_inline_xbrl BOOLEAN,
    primary_document TEXT,
    primary_doc_desc TEXT,
    last_sync_run_id TEXT,
    last_synced_at TIMESTAMP_TZ,
    parse_sequence BIGINT DEFAULT PARSE_SEQ.NEXTVAL
    , PRIMARY KEY (parse_sequence)
);
ALTER TABLE sec_company_filing ALTER COLUMN parse_sequence DROP NOT NULL;

CREATE TABLE IF NOT EXISTS sec_company_former_name (
    cik BIGINT NOT NULL,
    former_name TEXT,
    date_changed DATE,
    ordinal INTEGER NOT NULL,
    last_sync_run_id TEXT,
    parse_sequence BIGINT DEFAULT PARSE_SEQ.NEXTVAL
    , PRIMARY KEY (parse_sequence)
);
ALTER TABLE sec_company_former_name ALTER COLUMN parse_sequence DROP NOT NULL;

CREATE TABLE IF NOT EXISTS sec_company_submission_file (
    cik BIGINT NOT NULL,
    file_name TEXT NOT NULL,
    filing_count INTEGER,
    filing_from DATE,
    filing_to DATE,
    last_sync_run_id TEXT,
    last_synced_at TIMESTAMP_TZ,
    parse_sequence BIGINT DEFAULT PARSE_SEQ.NEXTVAL
    , PRIMARY KEY (parse_sequence)
);
ALTER TABLE sec_company_submission_file ALTER COLUMN parse_sequence DROP NOT NULL;

CREATE TABLE IF NOT EXISTS sec_company_ticker (
    cik BIGINT NOT NULL,
    ticker TEXT NOT NULL,
    exchange TEXT,
    source_name TEXT NOT NULL,
    source_rank INTEGER,
    last_sync_run_id TEXT,
    last_synced_at TIMESTAMP_TZ,
    parse_sequence BIGINT DEFAULT PARSE_SEQ.NEXTVAL
    , PRIMARY KEY (parse_sequence)
);
ALTER TABLE sec_company_ticker ALTER COLUMN parse_sequence DROP NOT NULL;

CREATE TABLE IF NOT EXISTS sec_current_filing_feed (
    accession_number TEXT NOT NULL,
    cik BIGINT,
    form TEXT,
    company_name TEXT,
    filing_date DATE,
    accepted_at TIMESTAMP_TZ,
    filing_href TEXT,
    index_href TEXT,
    summary TEXT,
    source_url TEXT,
    feed_published_at TIMESTAMP_TZ,
    raw_object_id TEXT,
    last_sync_run_id TEXT,
    last_synced_at TIMESTAMP_TZ,
    parse_sequence BIGINT DEFAULT PARSE_SEQ.NEXTVAL
    , PRIMARY KEY (parse_sequence)
);
ALTER TABLE sec_current_filing_feed ALTER COLUMN parse_sequence DROP NOT NULL;

CREATE TABLE IF NOT EXISTS sec_earnings_release (
    cik BIGINT NOT NULL,
    accession_number TEXT NOT NULL,
    filing_date DATE NOT NULL,
    fiscal_year INTEGER,
    fiscal_quarter INTEGER,
    period_end DATE,
    revenue_gaap DOUBLE,
    net_income_gaap DOUBLE,
    eps_gaap_diluted DOUBLE,
    has_non_gaap BOOLEAN NOT NULL,
    has_guidance BOOLEAN NOT NULL,
    parser_version TEXT,
    ingested_at TIMESTAMP_TZ,
    parse_sequence BIGINT DEFAULT PARSE_SEQ.NEXTVAL
    , PRIMARY KEY (parse_sequence)
);
ALTER TABLE sec_earnings_release ALTER COLUMN parse_sequence DROP NOT NULL;

CREATE TABLE IF NOT EXISTS sec_employment_event (
    accession_number TEXT NOT NULL,
    event_index BIGINT NOT NULL,
    cik BIGINT NOT NULL,
    event_type TEXT NOT NULL,
    person_name TEXT NOT NULL,
    exec_role TEXT,
    previous_role TEXT,
    compensation_amount DOUBLE,
    effective_date DATE NOT NULL,
    parser_version TEXT NOT NULL,
    ingested_at TIMESTAMP_TZ,
    parse_sequence BIGINT DEFAULT PARSE_SEQ.NEXTVAL
    , PRIMARY KEY (parse_sequence)
);
ALTER TABLE sec_employment_event ALTER COLUMN parse_sequence DROP NOT NULL;

CREATE TABLE IF NOT EXISTS sec_executive_record (
    cik BIGINT NOT NULL,
    accession_number TEXT NOT NULL,
    fiscal_year INTEGER NOT NULL,
    exec_name TEXT NOT NULL,
    exec_role TEXT,
    total_comp DOUBLE,
    base_salary DOUBLE,
    bonus DOUBLE,
    stock_awards DOUBLE,
    option_awards DOUBLE,
    non_equity_incentive DOUBLE,
    parser_version TEXT,
    ingested_at TIMESTAMP_TZ,
    parse_sequence BIGINT DEFAULT PARSE_SEQ.NEXTVAL
    , PRIMARY KEY (parse_sequence)
);
ALTER TABLE sec_executive_record ALTER COLUMN parse_sequence DROP NOT NULL;

CREATE TABLE IF NOT EXISTS sec_filing_attachment (
    accession_number TEXT NOT NULL,
    sequence_number TEXT,
    document_name TEXT NOT NULL,
    document_type TEXT NOT NULL,
    document_description TEXT,
    document_url TEXT NOT NULL,
    is_primary BOOLEAN NOT NULL,
    raw_object_id TEXT,
    last_sync_run_id TEXT,
    parse_sequence BIGINT DEFAULT PARSE_SEQ.NEXTVAL
    , PRIMARY KEY (parse_sequence)
);
ALTER TABLE sec_filing_attachment ALTER COLUMN parse_sequence DROP NOT NULL;

CREATE TABLE IF NOT EXISTS sec_filing_text (
    accession_number TEXT NOT NULL,
    text_version TEXT NOT NULL,
    source_document_name TEXT NOT NULL,
    text_storage_path TEXT NOT NULL,
    text_sha256 TEXT NOT NULL,
    char_count INTEGER NOT NULL,
    extracted_at TIMESTAMP_TZ NOT NULL,
    parse_sequence BIGINT DEFAULT PARSE_SEQ.NEXTVAL
    , PRIMARY KEY (parse_sequence)
);
ALTER TABLE sec_filing_text ALTER COLUMN parse_sequence DROP NOT NULL;

CREATE TABLE IF NOT EXISTS sec_financial_derived (
    cik BIGINT NOT NULL,
    accession_number TEXT NOT NULL,
    fiscal_year INTEGER NOT NULL,
    fiscal_period TEXT NOT NULL,
    period_end DATE NOT NULL,
    form_type TEXT NOT NULL,
    revenue DOUBLE,
    gross_profit DOUBLE,
    ebitda DOUBLE,
    ebit DOUBLE,
    net_income DOUBLE,
    eps_diluted DOUBLE,
    total_assets DOUBLE,
    total_liabilities DOUBLE,
    total_equity DOUBLE,
    cash_and_equivalents DOUBLE,
    total_debt DOUBLE,
    current_assets DOUBLE,
    current_liabilities DOUBLE,
    accounts_receivable DOUBLE,
    inventory DOUBLE,
    selling_general_admin_expense DOUBLE,
    retained_earnings DOUBLE,
    depreciation_amortization DOUBLE,
    property_plant_equipment_net DOUBLE,
    shares_outstanding DOUBLE,
    operating_cash_flow DOUBLE,
    capex DOUBLE,
    free_cash_flow DOUBLE,
    gross_margin DOUBLE,
    ebitda_margin DOUBLE,
    net_margin DOUBLE,
    roic DOUBLE,
    roe DOUBLE,
    roa DOUBLE,
    parser_version TEXT,
    ingested_at TIMESTAMP_TZ,
    parse_sequence BIGINT DEFAULT PARSE_SEQ.NEXTVAL
    , PRIMARY KEY (parse_sequence)
);
ALTER TABLE sec_financial_derived ALTER COLUMN parse_sequence DROP NOT NULL;

CREATE TABLE IF NOT EXISTS sec_financial_fact (
    cik BIGINT NOT NULL,
    accession_number TEXT NOT NULL,
    fiscal_year INTEGER NOT NULL,
    fiscal_period TEXT NOT NULL,
    period_end DATE NOT NULL,
    period_start DATE NOT NULL,
    form_type TEXT NOT NULL,
    concept TEXT NOT NULL,
    value DOUBLE,
    unit TEXT,
    decimals INTEGER,
    segment TEXT NOT NULL,
    parser_version TEXT,
    ingested_at TIMESTAMP_TZ,
    parse_sequence BIGINT DEFAULT PARSE_SEQ.NEXTVAL
    , PRIMARY KEY (parse_sequence)
);
ALTER TABLE sec_financial_fact ALTER COLUMN parse_sequence DROP NOT NULL;

CREATE TABLE IF NOT EXISTS sec_guidance_fact (
    fact_key BIGINT NOT NULL,
    cik BIGINT NOT NULL,
    ticker TEXT,
    company_key BIGINT,
    accession_number TEXT NOT NULL,
    metric TEXT NOT NULL,
    period_type TEXT NOT NULL,
    fiscal_year INTEGER NOT NULL,
    fiscal_quarter INTEGER NOT NULL,
    period_end DATE,
    value_low DOUBLE,
    value_mid DOUBLE,
    value_high DOUBLE,
    unit TEXT,
    currency TEXT,
    is_non_gaap BOOLEAN NOT NULL,
    as_of DATE NOT NULL,
    source_system TEXT NOT NULL,
    source_ref TEXT,
    excerpt TEXT,
    confidence TEXT NOT NULL,
    parser_version TEXT,
    ingested_at TIMESTAMP_TZ,
    parse_sequence BIGINT DEFAULT PARSE_SEQ.NEXTVAL
    , PRIMARY KEY (parse_sequence)
);
ALTER TABLE sec_guidance_fact ALTER COLUMN parse_sequence DROP NOT NULL;

CREATE TABLE IF NOT EXISTS sec_guidance_fact_reject (
    cik BIGINT NOT NULL,
    accession_number TEXT NOT NULL,
    metric TEXT,
    reject_reason TEXT NOT NULL,
    raw_payload TEXT,
    parser_version TEXT,
    ingested_at TIMESTAMP_TZ,
    parse_sequence BIGINT DEFAULT PARSE_SEQ.NEXTVAL
    , PRIMARY KEY (parse_sequence)
);
ALTER TABLE sec_guidance_fact_reject ALTER COLUMN parse_sequence DROP NOT NULL;

CREATE TABLE IF NOT EXISTS sec_ownership_derivative_txn (
    accession_number TEXT NOT NULL,
    owner_index SMALLINT NOT NULL,
    txn_index SMALLINT NOT NULL,
    security_title TEXT,
    transaction_date DATE,
    transaction_code TEXT,
    transaction_shares NUMBER(28,8),
    transaction_price NUMBER(28,8),
    acquired_disposed_code TEXT,
    shares_owned_after NUMBER(28,8),
    ownership_nature TEXT,
    ownership_direct_indirect TEXT,
    conversion_or_exercise_price NUMBER(28,8),
    exercise_date DATE,
    expiration_date DATE,
    underlying_security_title TEXT,
    underlying_security_shares NUMBER(28,8),
    parser_version TEXT,
    last_sync_run_id TEXT,
    mdm_entity_id TEXT,
    parse_sequence BIGINT DEFAULT PARSE_SEQ.NEXTVAL
    , PRIMARY KEY (parse_sequence)
);
ALTER TABLE sec_ownership_derivative_txn ALTER COLUMN parse_sequence DROP NOT NULL;

CREATE TABLE IF NOT EXISTS sec_ownership_non_derivative_txn (
    accession_number TEXT NOT NULL,
    owner_index SMALLINT NOT NULL,
    txn_index SMALLINT NOT NULL,
    security_title TEXT,
    transaction_date DATE,
    transaction_code TEXT,
    transaction_shares NUMBER(28,8),
    transaction_price NUMBER(28,8),
    acquired_disposed_code TEXT,
    shares_owned_after NUMBER(28,8),
    ownership_nature TEXT,
    ownership_direct_indirect TEXT,
    parser_version TEXT,
    last_sync_run_id TEXT,
    mdm_entity_id TEXT,
    parse_sequence BIGINT DEFAULT PARSE_SEQ.NEXTVAL
    , PRIMARY KEY (parse_sequence)
);
ALTER TABLE sec_ownership_non_derivative_txn ALTER COLUMN parse_sequence DROP NOT NULL;

CREATE TABLE IF NOT EXISTS sec_ownership_reporting_owner (
    accession_number TEXT NOT NULL,
    owner_index SMALLINT NOT NULL,
    owner_cik BIGINT,
    owner_name TEXT,
    is_director BOOLEAN,
    is_officer BOOLEAN,
    is_ten_percent_owner BOOLEAN,
    is_other BOOLEAN,
    officer_title TEXT,
    parser_version TEXT,
    last_sync_run_id TEXT,
    mdm_entity_id TEXT,
    parse_sequence BIGINT DEFAULT PARSE_SEQ.NEXTVAL
    , PRIMARY KEY (parse_sequence)
);
ALTER TABLE sec_ownership_reporting_owner ALTER COLUMN parse_sequence DROP NOT NULL;

CREATE TABLE IF NOT EXISTS sec_pcaob_firm_identity (
    pcaob_firm_id TEXT NOT NULL,
    canonical_name TEXT,
    city TEXT,
    state TEXT,
    country TEXT,
    status TEXT,
    snapshot_uri TEXT,
    snapshot_sha256 TEXT NOT NULL,
    last_sync_run_id TEXT,
    parse_sequence BIGINT DEFAULT PARSE_SEQ.NEXTVAL
    , PRIMARY KEY (parse_sequence)
);
ALTER TABLE sec_pcaob_firm_identity ALTER COLUMN parse_sequence DROP NOT NULL;

CREATE TABLE IF NOT EXISTS sec_raw_object (
    raw_object_id TEXT NOT NULL,
    source_type TEXT,
    cik BIGINT,
    accession_number TEXT,
    form TEXT,
    source_url TEXT NOT NULL,
    storage_path TEXT NOT NULL,
    content_type TEXT,
    content_encoding TEXT,
    byte_size BIGINT,
    sha256 TEXT NOT NULL,
    fetched_at TIMESTAMP_TZ NOT NULL,
    http_status INTEGER NOT NULL,
    source_last_modified TIMESTAMP_TZ,
    source_etag TEXT,
    parse_sequence BIGINT DEFAULT PARSE_SEQ.NEXTVAL
    , PRIMARY KEY (parse_sequence)
);
ALTER TABLE sec_raw_object ALTER COLUMN parse_sequence DROP NOT NULL;

CREATE TABLE IF NOT EXISTS sec_subsidiary_evidence (
    accession_number TEXT NOT NULL,
    registrant_cik BIGINT,
    document_name TEXT NOT NULL,
    document_type TEXT,
    row_ordinal INTEGER NOT NULL,
    legal_name TEXT,
    jurisdiction TEXT,
    parent_scope TEXT,
    immediate_parent_known BOOLEAN,
    effective_date DATE,
    row_locator TEXT,
    source_sha256 TEXT,
    parser_version TEXT,
    last_sync_run_id TEXT,
    parse_sequence BIGINT DEFAULT PARSE_SEQ.NEXTVAL
    , PRIMARY KEY (parse_sequence)
);
ALTER TABLE sec_subsidiary_evidence ALTER COLUMN parse_sequence DROP NOT NULL;

CREATE TABLE IF NOT EXISTS sec_thirteenf_filing (
    accession_number TEXT NOT NULL,
    cik BIGINT NOT NULL,
    period_of_report DATE NOT NULL,
    filing_date DATE NOT NULL,
    form TEXT NOT NULL,
    amendment_type TEXT,
    confidential_omission BOOLEAN NOT NULL,
    effective_status TEXT NOT NULL,
    superseded_by_accession TEXT,
    parser_version TEXT NOT NULL,
    ingested_at TIMESTAMP_TZ,
    parse_sequence BIGINT DEFAULT PARSE_SEQ.NEXTVAL
    , PRIMARY KEY (parse_sequence)
);
ALTER TABLE sec_thirteenf_filing ALTER COLUMN parse_sequence DROP NOT NULL;

CREATE TABLE IF NOT EXISTS sec_thirteenf_holding (
    cik BIGINT NOT NULL,
    accession_number TEXT NOT NULL,
    holding_index BIGINT NOT NULL,
    period_of_report DATE NOT NULL,
    cusip TEXT,
    issuer_name TEXT,
    security_title TEXT,
    shares_held DOUBLE,
    market_value DOUBLE,
    security_class TEXT,
    put_call TEXT,
    discretion_type TEXT,
    voting_auth_sole DOUBLE,
    voting_auth_shared DOUBLE,
    voting_auth_none DOUBLE,
    parser_version TEXT,
    ingested_at TIMESTAMP_TZ,
    parse_sequence BIGINT DEFAULT PARSE_SEQ.NEXTVAL
    , PRIMARY KEY (parse_sequence)
);
ALTER TABLE sec_thirteenf_holding ALTER COLUMN parse_sequence DROP NOT NULL;

-- Grant the loader role (the same EDGARTOOLS_PROD_LOADER that already owns
-- gold's 20 dynamic tables, the MDM mirror, and the graph schema -- reused
-- here rather than minting a new role, per silver-snowflake-migration map
-- Ticket 05's decision) SELECT + INSERT only. No UPDATE/DELETE: landing is
-- append-only by design, so granting write-in-place would be a standing
-- capability with no legitimate caller.
GRANT USAGE ON SCHEMA EDGARTOOLS_PROD.EDGARTOOLS_SILVER_LANDING TO ROLE EDGARTOOLS_PROD_LOADER;
GRANT USAGE ON SEQUENCE EDGARTOOLS_PROD.EDGARTOOLS_SILVER_LANDING.PARSE_SEQ TO ROLE EDGARTOOLS_PROD_LOADER;
GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA EDGARTOOLS_PROD.EDGARTOOLS_SILVER_LANDING TO ROLE EDGARTOOLS_PROD_LOADER;
GRANT SELECT, INSERT ON FUTURE TABLES IN SCHEMA EDGARTOOLS_PROD.EDGARTOOLS_SILVER_LANDING TO ROLE EDGARTOOLS_PROD_LOADER;
