"""Generate idempotent Snowflake DDL for the MDM mirror schema.

Root cause this exists to fix: the `EDGARTOOLS_PROD.MDM` mirror schema
(`edgar_warehouse.mdm.export._build_snowflake_mirror_writer`'s target,
documented in docs/prod-mdm-snowflake-graph-first-load.md) was originally
created by a one-off, uncommitted manual shell session on 2026-06-22. When
the platform's Snowflake account was rebuilt as part of the go-live cutover,
every other piece (gold, source, loader role, dashboards, Neo4j app) was
re-provisioned via Terraform/bootstrap SQL, but this step had no script to
re-run -- so the schema came back empty and `mdm publish` failed with
"Object 'EDGARTOOLS_PROD.MDM.MDM_ENTITY' does not exist or not authorized."

This script reflects the authoritative schema straight from
`edgar_warehouse.mdm.database`'s SQLAlchemy models (the same models the
Postgres MDM instance itself is built from) for exactly the tables listed in
`edgar_warehouse.mdm.migrations.runtime.MDM_TABLES`, and emits
`CREATE TABLE IF NOT EXISTS` DDL, additive upgrades for existing mirrors,
plus the DML grants the exporter's runtime
role (`EDGARTOOLS_PROD_LOADER`, not `EDGARTOOLS_PROD_DEPLOYER` -- the
original runbook's role reference is stale, see CLAUDE.md's
"manifest-pipeline ownership" incident for why LOADER is now the mirror's
correct owner-adjacent role) needs. Deliberately does not use
`GRANT OWNERSHIP ... REVOKE CURRENT GRANTS` -- see that same incident for why
that pattern silently strips unrelated grants.

Usage:
    MDM_DATABASE_URL=sqlite:///:memory: uv run python \
        infra/scripts/generate_mdm_mirror_ddl.py > /tmp/mdm_mirror_bootstrap.sql
    snow sql --connection edgartools-prod -f /tmp/mdm_mirror_bootstrap.sql

Safe to re-run: every CREATE/ALTER is guarded and every GRANT is additive
(no REVOKE, no DROP, no OWNERSHIP transfer).
"""
from __future__ import annotations

import os
import re
import sys

os.environ.setdefault("MDM_DATABASE_URL", "sqlite:///:memory:")

from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateTable

from edgar_warehouse.mdm import database as db
from edgar_warehouse.mdm.migrations.runtime import MDM_TABLES

TARGET_DATABASE = "EDGARTOOLS_PROD"
TARGET_SCHEMA = "MDM"
TARGET_ROLE = "EDGARTOOLS_PROD_LOADER"


def generate() -> str:
    dialect = postgresql.dialect()
    wanted = set(MDM_TABLES)
    ordered = [t for t in db.Base.metadata.sorted_tables if t.name in wanted]
    if len(ordered) != len(MDM_TABLES):
        missing = wanted - {t.name for t in ordered}
        raise RuntimeError(f"MDM_TABLES not found in ORM metadata: {sorted(missing)}")

    lines = [
        "-- Auto-generated by infra/scripts/generate_mdm_mirror_ddl.py -- do not hand-edit.",
        "-- Reflects edgar_warehouse.mdm.database's SQLAlchemy models for the",
        "-- Snowflake MDM mirror schema (edgar_warehouse.mdm.migrations.runtime.MDM_TABLES).",
        "-- Idempotent: every schema statement is guarded and every GRANT is additive.",
        "",
        # Ticket 30 (change-propagation map) follow-up, 2026-08-26: this
        # schema is self-contained (nothing here grants on an object outside
        # it), so it runs under the dedicated EDGARTOOLS_PROD_INSTALLER role
        # (infra/snowflake/sql/bootstrap/19_installer_role.sql) instead of
        # ACCOUNTADMIN -- see that file for the scope this role does and
        # does not cover.
        "USE ROLE EDGARTOOLS_PROD_INSTALLER;",
        f"USE DATABASE {TARGET_DATABASE};",
        f"CREATE SCHEMA IF NOT EXISTS {TARGET_SCHEMA};",
        f"USE SCHEMA {TARGET_SCHEMA};",
        "",
    ]

    for table in ordered:
        ddl = str(CreateTable(table).compile(dialect=dialect))
        ddl = ddl.replace("CREATE TABLE ", "CREATE TABLE IF NOT EXISTS ", 1)
        ddl = re.sub(r"\bUUID\b", "VARCHAR(36)", ddl)
        ddl = re.sub(r"\bJSON\b", "VARIANT", ddl)
        ddl = ddl.replace("NOW()", "CURRENT_TIMESTAMP()")
        lines.append(ddl.strip() + ";")
        lines.append("")

    # CREATE TABLE IF NOT EXISTS does not upgrade tables created by an older
    # release, so additive mirror changes also need explicit guarded ALTERs.
    lines.extend(
        [
            "ALTER TABLE mdm_change_log ADD COLUMN IF NOT EXISTS run_id TEXT;",
            "ALTER TABLE mdm_relationship_instance ADD COLUMN IF NOT EXISTS run_id TEXT;",
            "",
        ]
    )

    lines.extend(
        [
            "-- Grant the loader role (the role edgar_warehouse.mdm.export.py's",
            "-- mirror_writer actually authenticates as) DML + future-table access.",
            f"GRANT USAGE ON SCHEMA {TARGET_DATABASE}.{TARGET_SCHEMA} TO ROLE {TARGET_ROLE};",
            f"GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA "
            f"{TARGET_DATABASE}.{TARGET_SCHEMA} TO ROLE {TARGET_ROLE};",
            f"GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA "
            f"{TARGET_DATABASE}.{TARGET_SCHEMA} TO ROLE {TARGET_ROLE};",
            "",
        ]
    )
    return "\n".join(lines)


if __name__ == "__main__":
    sys.stdout.write(generate())
