#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8
ENV_FILE="${ENV_FILE:-.env}"

banner "Atlas Free (M0) Mongo Decision Projection"

# ── Stage 1 ──────────────────────────────────────────────────────────────
stage "Atlas account and project"
say "Create or open the Atlas organization/project that will host v2 (not warehouse ingest)."
open_url "https://cloud.mongodb.com"
step "Sign in or register. Create a project if you do not have one (Project Owner)."
note "Database users are not Atlas UI users. You will create SCRAM users later."
pause "Press Enter when the project Overview is visible."

# ── Stage 2 ──────────────────────────────────────────────────────────────
stage "Create M0 Free cluster"
say "Deploy a Free cluster. Official path: Create → Deploy a cluster → M0."
open_url "https://www.mongodb.com/docs/atlas/tutorial/deploy-free-tier-cluster/"
step "In Atlas: Create → Deploy a cluster (or Build a Database)."
step "Select M0 (Free forever). Provider AWS, region close to you (US_EAST_1 is fine)."
step "Name the cluster something like edgartools-decision. Do not pick a paid tier."
step "Skip loading sample data — this database is a Decision Projection, not movies."
pause "Press Enter when the cluster shows as created (often under 15 seconds)."

# ── Stage 3 ──────────────────────────────────────────────────────────────
stage "IP access list 0.0.0.0/0"
say "Internet agents need the public hostname. Ticket 05: 0.0.0.0/0 + TLS + DB user."
open_url "https://cloud.mongodb.com"
step "Network Access → Add IP Address."
step "Enter 0.0.0.0/0 (Allow Access from Anywhere). Atlas will warn and email; that is expected."
step "Do not leave only 'Add My Current IP Address' — v2 agents are not this laptop."
pause "Press Enter when 0.0.0.0/0 is on the IP Access List."

# ── Stage 4 ──────────────────────────────────────────────────────────────
stage "Publisher write user"
say "Separate SCRAM user with readWrite on database edgartools_decision only."
open_url "https://cloud.mongodb.com"
step "Database Access → Add New Database User."
step "Authentication: Password (SCRAM). Username: edgartools_publisher"
step "Autogenerate a password and copy it now. You will not see it again."
step "Privileges: Built-in Role → readWrite, Specific Privileges database edgartools_decision."
step "Do not grant atlasAdmin."
ask_secret MONGO_PUBLISHER_PASSWORD "Paste the publisher password:"
pause "Press Enter after the publisher user is saved."

# ── Stage 5 ──────────────────────────────────────────────────────────────
stage "Read-only agent user"
say "One read-only SCRAM user for internet agents. Cannot write."
open_url "https://cloud.mongodb.com"
step "Database Access → Add New Database User."
step "Authentication: Password (SCRAM). Username: edgartools_agent"
step "Autogenerate a password and copy it."
step "Privileges: Built-in Role → read on database edgartools_decision only."
ask_secret MONGO_AGENT_PASSWORD "Paste the agent password:"
pause "Press Enter after the agent user is saved."

# ── Stage 6 ──────────────────────────────────────────────────────────────
stage "Connection strings"
say "Copy the mongodb+srv host (TLS is required; do not disable it)."
open_url "https://cloud.mongodb.com"
step "Clusters → Connect → Drivers → Python. Copy the host, e.g. cluster0.xxxxx.mongodb.net"
step "Do not paste passwords into chat. This wizard writes only to local $ENV_FILE (gitignored)."
ask MONGO_SRV_HOST "Paste the SRV host (no mongodb+srv:// prefix):"
_enc() { printf '%s' "$1" | uv run python -c 'import sys,urllib.parse; print(urllib.parse.quote(sys.stdin.read(), safe=""))'; }
PUB_PW_ENC=$(_enc "$MONGO_PUBLISHER_PASSWORD")
AGENT_PW_ENC=$(_enc "$MONGO_AGENT_PASSWORD")
MONGO_PUBLISHER_URI="mongodb+srv://edgartools_publisher:${PUB_PW_ENC}@${MONGO_SRV_HOST}/edgartools_decision?retryWrites=true&w=majority"
MONGO_AGENT_URI="mongodb+srv://edgartools_agent:${AGENT_PW_ENC}@${MONGO_SRV_HOST}/edgartools_decision?retryWrites=true&w=majority"
write_env MONGO_SRV_HOST "$MONGO_SRV_HOST"
write_env MONGO_PUBLISHER_URI "$MONGO_PUBLISHER_URI"
write_env MONGO_AGENT_URI "$MONGO_AGENT_URI"
note "CI must not receive these values. This wizard does not call gh secret set."

# ── Stage 7 ──────────────────────────────────────────────────────────────
stage "Apply \$jsonSchema and indexes"
say "Create database edgartools_decision, both collections, strict \$jsonSchema, generation index."
if confirm "Apply schema now with the publisher URI (needs network + uv)?"; then
  uv run --with pymongo python infra/scripts/apply-mongo-decision-schema.py
else
  SKIPPED+=("apply-mongo-decision-schema.py")
  note "Run later: uv run --with pymongo python infra/scripts/apply-mongo-decision-schema.py"
fi

# ── Stage 8 ──────────────────────────────────────────────────────────────
stage "Smoke publish and read-only find"
say "One READY smoke: publisher upserts; agent find returns agent-grade; agent write is rejected."
if confirm "Run the operator smoke now?"; then
  uv run --with pymongo python infra/scripts/smoke-mongo-decision-projection.py
else
  SKIPPED+=("smoke-mongo-decision-projection.py")
  note "Run later: uv run --with pymongo python infra/scripts/smoke-mongo-decision-projection.py"
fi

finish
note "Keep $ENV_FILE gitignored. Do not add Atlas URIs to GitHub Actions."
