-- Ticket 01: live FINANCIAL_FACTORS bind vs locked 19 As-Of Decision Feature keys.
-- Connection: snow sql --connection edgartools-prod
-- Database: EDGARTOOLS_PROD
-- Read-only.

-- 1. Full column lists.
SELECT 'factors_cols' AS probe, ORDINAL_POSITION, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM EDGARTOOLS_PROD.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_CATALOG = 'EDGARTOOLS_PROD'
  AND TABLE_SCHEMA = 'EDGARTOOLS_GOLD'
  AND TABLE_NAME = 'FINANCIAL_FACTORS'
ORDER BY ORDINAL_POSITION;

SELECT 'derived_cols' AS probe, ORDINAL_POSITION, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM EDGARTOOLS_PROD.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_CATALOG = 'EDGARTOOLS_PROD'
  AND TABLE_SCHEMA = 'EDGARTOOLS_GOLD'
  AND TABLE_NAME = 'FINANCIAL_DERIVED'
ORDER BY ORDINAL_POSITION;

SELECT 'silver_derived_cols' AS probe, ORDINAL_POSITION, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM EDGARTOOLS_PROD.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_CATALOG = 'EDGARTOOLS_PROD'
  AND TABLE_SCHEMA = 'EDGARTOOLS_SILVER'
  AND TABLE_NAME = 'SEC_FINANCIAL_DERIVED'
ORDER BY ORDINAL_POSITION;

-- Named bind-gap columns (factors / derived / silver).
SELECT 'named_bind_cols' AS probe, TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME
FROM EDGARTOOLS_PROD.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_CATALOG = 'EDGARTOOLS_PROD'
  AND (
        (TABLE_SCHEMA = 'EDGARTOOLS_GOLD' AND TABLE_NAME IN ('FINANCIAL_FACTORS', 'FINANCIAL_DERIVED'))
     OR (TABLE_SCHEMA = 'EDGARTOOLS_SILVER' AND TABLE_NAME = 'SEC_FINANCIAL_DERIVED')
  )
  AND COLUMN_NAME IN (
        'EBITDA', 'EPS_DILUTED', 'EBITDA_MARGIN',
        'RETURN_ON_EQUITY', 'RETURN_ON_ASSETS',
        'ROE', 'ROA', 'ROIC',
        'OPERATING_MARGIN',
        'REVENUE', 'GROSS_PROFIT', 'EBIT', 'NET_INCOME',
        'TOTAL_ASSETS', 'TOTAL_LIABILITIES', 'TOTAL_EQUITY',
        'CASH_AND_EQUIVALENTS', 'TOTAL_DEBT',
        'OPERATING_CASH_FLOW', 'FREE_CASH_FLOW',
        'GROSS_MARGIN', 'NET_MARGIN'
  )
ORDER BY TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME;

-- 2. Row counts, distinct CIK, FY mix on FINANCIAL_FACTORS.
SELECT
    'factors_counts' AS probe,
    COUNT(*) AS row_count,
    COUNT(DISTINCT CIK) AS distinct_cik,
    COUNT_IF(UPPER(FISCAL_PERIOD) = 'FY') AS fy_rows,
    COUNT_IF(UPPER(FISCAL_PERIOD) <> 'FY') AS non_fy_rows,
    COUNT(DISTINCT IFF(UPPER(FISCAL_PERIOD) = 'FY', CIK, NULL)) AS fy_ciks,
    COUNT(DISTINCT IFF(UPPER(FISCAL_PERIOD) <> 'FY', CIK, NULL)) AS non_fy_ciks
FROM EDGARTOOLS_PROD.EDGARTOOLS_GOLD.FINANCIAL_FACTORS;

SELECT
    'factors_period_mix' AS probe,
    FISCAL_PERIOD,
    COUNT(*) AS row_count,
    COUNT(DISTINCT CIK) AS distinct_cik
FROM EDGARTOOLS_PROD.EDGARTOOLS_GOLD.FINANCIAL_FACTORS
GROUP BY FISCAL_PERIOD
ORDER BY row_count DESC;

SELECT
    'derived_counts' AS probe,
    COUNT(*) AS row_count,
    COUNT(DISTINCT CIK) AS distinct_cik,
    COUNT_IF(UPPER(FISCAL_PERIOD) = 'FY') AS fy_rows,
    COUNT_IF(UPPER(FISCAL_PERIOD) <> 'FY') AS non_fy_rows
FROM EDGARTOOLS_PROD.EDGARTOOLS_GOLD.FINANCIAL_DERIVED;

SELECT
    'silver_derived_counts' AS probe,
    COUNT(*) AS row_count,
    COUNT(DISTINCT CIK) AS distinct_cik
FROM EDGARTOOLS_PROD.EDGARTOOLS_SILVER.SEC_FINANCIAL_DERIVED;

-- 3. Non-null coverage on FINANCIAL_FACTORS for keys that exist live.
--    Missing live columns (EBITDA, EPS_DILUTED, EBITDA_MARGIN, ROE, ROA) cannot be SELECTed.
SELECT
    'factors_nonnull' AS probe,
    COUNT(*) AS n,
    COUNT_IF(REVENUE IS NOT NULL) AS revenue,
    COUNT_IF(GROSS_PROFIT IS NOT NULL) AS gross_profit,
    COUNT_IF(EBIT IS NOT NULL) AS ebit,
    COUNT_IF(NET_INCOME IS NOT NULL) AS net_income,
    COUNT_IF(TOTAL_ASSETS IS NOT NULL) AS total_assets,
    COUNT_IF(TOTAL_LIABILITIES IS NOT NULL) AS total_liabilities,
    COUNT_IF(TOTAL_EQUITY IS NOT NULL) AS total_equity,
    COUNT_IF(CASH_AND_EQUIVALENTS IS NOT NULL) AS cash_and_equivalents,
    COUNT_IF(TOTAL_DEBT IS NOT NULL) AS total_debt,
    COUNT_IF(OPERATING_CASH_FLOW IS NOT NULL) AS operating_cash_flow,
    COUNT_IF(FREE_CASH_FLOW IS NOT NULL) AS free_cash_flow,
    COUNT_IF(GROSS_MARGIN IS NOT NULL) AS gross_margin,
    COUNT_IF(NET_MARGIN IS NOT NULL) AS net_margin,
    COUNT_IF(RETURN_ON_EQUITY IS NOT NULL) AS return_on_equity,
    COUNT_IF(RETURN_ON_ASSETS IS NOT NULL) AS return_on_assets,
    COUNT_IF(ROIC IS NOT NULL) AS roic,
    COUNT_IF(OPERATING_MARGIN IS NOT NULL) AS operating_margin
FROM EDGARTOOLS_PROD.EDGARTOOLS_GOLD.FINANCIAL_FACTORS;

SELECT
    'factors_fy_nonnull' AS probe,
    COUNT(*) AS n,
    COUNT_IF(REVENUE IS NOT NULL) AS revenue,
    COUNT_IF(GROSS_PROFIT IS NOT NULL) AS gross_profit,
    COUNT_IF(EBIT IS NOT NULL) AS ebit,
    COUNT_IF(NET_INCOME IS NOT NULL) AS net_income,
    COUNT_IF(TOTAL_ASSETS IS NOT NULL) AS total_assets,
    COUNT_IF(TOTAL_LIABILITIES IS NOT NULL) AS total_liabilities,
    COUNT_IF(TOTAL_EQUITY IS NOT NULL) AS total_equity,
    COUNT_IF(CASH_AND_EQUIVALENTS IS NOT NULL) AS cash_and_equivalents,
    COUNT_IF(TOTAL_DEBT IS NOT NULL) AS total_debt,
    COUNT_IF(OPERATING_CASH_FLOW IS NOT NULL) AS operating_cash_flow,
    COUNT_IF(FREE_CASH_FLOW IS NOT NULL) AS free_cash_flow,
    COUNT_IF(GROSS_MARGIN IS NOT NULL) AS gross_margin,
    COUNT_IF(NET_MARGIN IS NOT NULL) AS net_margin,
    COUNT_IF(RETURN_ON_EQUITY IS NOT NULL) AS return_on_equity,
    COUNT_IF(RETURN_ON_ASSETS IS NOT NULL) AS return_on_assets,
    COUNT_IF(ROIC IS NOT NULL) AS roic
FROM EDGARTOOLS_PROD.EDGARTOOLS_GOLD.FINANCIAL_FACTORS
WHERE UPPER(FISCAL_PERIOD) = 'FY';

-- Any of the 16 currently-live contract keys non-null (interim coverage rule).
SELECT
    'factors_any_live_key' AS probe,
    COUNT(*) AS n,
    COUNT_IF(
        REVENUE IS NOT NULL
        OR GROSS_PROFIT IS NOT NULL
        OR EBIT IS NOT NULL
        OR NET_INCOME IS NOT NULL
        OR TOTAL_ASSETS IS NOT NULL
        OR TOTAL_LIABILITIES IS NOT NULL
        OR TOTAL_EQUITY IS NOT NULL
        OR CASH_AND_EQUIVALENTS IS NOT NULL
        OR TOTAL_DEBT IS NOT NULL
        OR OPERATING_CASH_FLOW IS NOT NULL
        OR FREE_CASH_FLOW IS NOT NULL
        OR GROSS_MARGIN IS NOT NULL
        OR NET_MARGIN IS NOT NULL
        OR RETURN_ON_EQUITY IS NOT NULL
        OR RETURN_ON_ASSETS IS NOT NULL
        OR ROIC IS NOT NULL
    ) AS any_of_16_live_keys
FROM EDGARTOOLS_PROD.EDGARTOOLS_GOLD.FINANCIAL_FACTORS;

-- 4. FINANCIAL_DERIVED passthrough sources for the three missing factors columns,
--    plus derived's native ROE/ROA (gold factors recomputes those as RETURN_ON_*).
SELECT
    'derived_passthrough' AS probe,
    COUNT(*) AS n,
    COUNT_IF(EBITDA IS NOT NULL) AS ebitda,
    COUNT_IF(EPS_DILUTED IS NOT NULL) AS eps_diluted,
    COUNT_IF(EBITDA_MARGIN IS NOT NULL) AS ebitda_margin,
    COUNT_IF(ROE IS NOT NULL) AS roe,
    COUNT_IF(ROA IS NOT NULL) AS roa,
    COUNT_IF(ROIC IS NOT NULL) AS roic,
    COUNT_IF(REVENUE IS NOT NULL) AS revenue,
    COUNT_IF(GROSS_PROFIT IS NOT NULL) AS gross_profit,
    COUNT_IF(EBIT IS NOT NULL) AS ebit,
    COUNT_IF(NET_INCOME IS NOT NULL) AS net_income,
    COUNT_IF(TOTAL_ASSETS IS NOT NULL) AS total_assets,
    COUNT_IF(TOTAL_LIABILITIES IS NOT NULL) AS total_liabilities,
    COUNT_IF(TOTAL_EQUITY IS NOT NULL) AS total_equity,
    COUNT_IF(CASH_AND_EQUIVALENTS IS NOT NULL) AS cash_and_equivalents,
    COUNT_IF(TOTAL_DEBT IS NOT NULL) AS total_debt,
    COUNT_IF(OPERATING_CASH_FLOW IS NOT NULL) AS operating_cash_flow,
    COUNT_IF(FREE_CASH_FLOW IS NOT NULL) AS free_cash_flow,
    COUNT_IF(GROSS_MARGIN IS NOT NULL) AS gross_margin,
    COUNT_IF(NET_MARGIN IS NOT NULL) AS net_margin
FROM EDGARTOOLS_PROD.EDGARTOOLS_GOLD.FINANCIAL_DERIVED;

SELECT
    'derived_fy_passthrough' AS probe,
    COUNT(*) AS n,
    COUNT_IF(EBITDA IS NOT NULL) AS ebitda,
    COUNT_IF(EPS_DILUTED IS NOT NULL) AS eps_diluted,
    COUNT_IF(EBITDA_MARGIN IS NOT NULL) AS ebitda_margin,
    COUNT_IF(ROE IS NOT NULL) AS roe,
    COUNT_IF(ROA IS NOT NULL) AS roa
FROM EDGARTOOLS_PROD.EDGARTOOLS_GOLD.FINANCIAL_DERIVED
WHERE UPPER(FISCAL_PERIOD) = 'FY';

-- Silver collapse of the same passthrough columns (upstream of gold derived).
SELECT
    'silver_derived_passthrough' AS probe,
    COUNT(*) AS n,
    COUNT_IF(EBITDA IS NOT NULL) AS ebitda,
    COUNT_IF(EPS_DILUTED IS NOT NULL) AS eps_diluted,
    COUNT_IF(EBITDA_MARGIN IS NOT NULL) AS ebitda_margin,
    COUNT_IF(ROE IS NOT NULL) AS roe,
    COUNT_IF(ROA IS NOT NULL) AS roa,
    COUNT_IF(ROIC IS NOT NULL) AS roic
FROM EDGARTOOLS_PROD.EDGARTOOLS_SILVER.SEC_FINANCIAL_DERIVED;

-- Sample of derived rows that would populate the missing factors columns.
SELECT
    'derived_sample' AS probe,
    CIK,
    ACCESSION_NUMBER,
    FISCAL_YEAR,
    FISCAL_PERIOD,
    PERIOD_END,
    EBITDA,
    EPS_DILUTED,
    EBITDA_MARGIN,
    ROE,
    ROA
FROM EDGARTOOLS_PROD.EDGARTOOLS_GOLD.FINANCIAL_DERIVED
WHERE EBITDA IS NOT NULL
   OR EPS_DILUTED IS NOT NULL
   OR EBITDA_MARGIN IS NOT NULL
ORDER BY PERIOD_END DESC
LIMIT 8;

-- Dynamic-table refresh metadata (do not decide whether to refresh).
SELECT
    'dt_refresh' AS probe,
    NAME,
    SCHEMA_NAME,
    TARGET_LAG,
    REFRESH_MODE,
    LAST_SUCCESSFUL_REFRESH_TIME,
    LAST_COMPLETED_REFRESH_TIME,
    DATA_TIMESTAMP
FROM TABLE(EDGARTOOLS_PROD.INFORMATION_SCHEMA.DYNAMIC_TABLES())
WHERE SCHEMA_NAME = 'EDGARTOOLS_GOLD'
  AND NAME IN ('FINANCIAL_FACTORS', 'FINANCIAL_DERIVED')
ORDER BY NAME;
