-- Follow-up after GROUP BY position error. Read-only.

SELECT SOURCE_ENTITY_TYPE, TARGET_ENTITY_TYPE, COUNT(*) AS n
FROM EDGARTOOLS_PROD.NEO4J_GRAPH_MIGRATION.GRAPH_EDGE_IS_INSIDER
GROUP BY SOURCE_ENTITY_TYPE, TARGET_ENTITY_TYPE
ORDER BY n DESC;

SELECT SOURCE_SYSTEM, COUNT(*) AS n
FROM EDGARTOOLS_PROD.NEO4J_GRAPH_MIGRATION.GRAPH_EDGE_IS_INSIDER
GROUP BY SOURCE_SYSTEM
ORDER BY n DESC;

SELECT
    COUNT(DISTINCT c.PROPERTIES:cik::STRING) AS graph_issuer_ciks,
    COUNT(DISTINCT IFF(LOWER(COALESCE(m.TRACKING_STATUS, '')) = 'active', c.PROPERTIES:cik::STRING, NULL)) AS mdm_active_issuer_ciks
FROM EDGARTOOLS_PROD.NEO4J_GRAPH_MIGRATION.GRAPH_EDGE_IS_INSIDER e
JOIN EDGARTOOLS_PROD.NEO4J_GRAPH_MIGRATION.GRAPH_NODE_COMPANY c
  ON c.NODEID = IFF(e.TARGET_ENTITY_TYPE = 'company', e.TARGETNODEID, e.SOURCENODEID)
LEFT JOIN EDGARTOOLS_PROD.EDGARTOOLS_GOLD.MDM_COMPANY_ENTITY m
  ON LPAD(m.CIK::STRING, 10, '0') = LPAD(c.PROPERTIES:cik::STRING, 10, '0');

SELECT COLUMN_NAME
FROM EDGARTOOLS_PROD.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_CATALOG = 'EDGARTOOLS_PROD'
  AND TABLE_SCHEMA = 'EDGARTOOLS_GOLD'
  AND TABLE_NAME = 'OWNERSHIP_HOLDINGS'
ORDER BY ORDINAL_POSITION;

SELECT COLUMN_NAME
FROM EDGARTOOLS_PROD.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_CATALOG = 'EDGARTOOLS_PROD'
  AND TABLE_SCHEMA = 'EDGARTOOLS_GOLD'
  AND TABLE_NAME = 'OWNERSHIP_ACTIVITY'
  AND (COLUMN_NAME ILIKE '%OWNER%' OR COLUMN_NAME ILIKE '%PERSON%' OR COLUMN_NAME ILIKE '%ACCESSION%' OR COLUMN_NAME ILIKE '%CIK%')
ORDER BY COLUMN_NAME;

SELECT COUNT(*) AS row_count,
       COUNT(DISTINCT COMPANY_KEY) AS distinct_company_key,
       COUNT(DISTINCT ACCESSION_NUMBER) AS distinct_accession
FROM EDGARTOOLS_PROD.EDGARTOOLS_GOLD.OWNERSHIP_HOLDINGS;

SELECT COUNT(*) AS row_count,
       COUNT(DISTINCT COMPANY_KEY) AS distinct_company_key
FROM EDGARTOOLS_PROD.EDGARTOOLS_GOLD.OWNERSHIP_ACTIVITY;

SELECT COLUMN_NAME
FROM EDGARTOOLS_PROD.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_CATALOG = 'EDGARTOOLS_PROD'
  AND TABLE_SCHEMA = 'EDGARTOOLS_SILVER'
  AND TABLE_NAME = 'SEC_OWNERSHIP_REPORTING_OWNER'
ORDER BY ORDINAL_POSITION;

SELECT COUNT(*) AS row_count
FROM EDGARTOOLS_PROD.EDGARTOOLS_SILVER.SEC_OWNERSHIP_REPORTING_OWNER;

SELECT COUNT(*) AS mdm_active
FROM EDGARTOOLS_PROD.EDGARTOOLS_GOLD.MDM_COMPANY_ENTITY
WHERE LOWER(COALESCE(TRACKING_STATUS, '')) = 'active';

SELECT SOURCE_ENTITY_TYPE, TARGET_ENTITY_TYPE, COUNT(*) AS n
FROM EDGARTOOLS_PROD.NEO4J_GRAPH_MIGRATION.GRAPH_EDGE_EMPLOYED_BY
GROUP BY SOURCE_ENTITY_TYPE, TARGET_ENTITY_TYPE
ORDER BY n DESC;

SELECT SOURCE_SYSTEM, COUNT(*) AS n
FROM EDGARTOOLS_PROD.NEO4J_GRAPH_MIGRATION.GRAPH_EDGE_EMPLOYED_BY
GROUP BY SOURCE_SYSTEM
ORDER BY n DESC;

SELECT
    COUNT(DISTINCT c.PROPERTIES:cik::STRING) AS graph_issuer_ciks,
    COUNT(DISTINCT IFF(LOWER(COALESCE(m.TRACKING_STATUS, '')) = 'active', c.PROPERTIES:cik::STRING, NULL)) AS mdm_active_issuer_ciks
FROM EDGARTOOLS_PROD.NEO4J_GRAPH_MIGRATION.GRAPH_EDGE_EMPLOYED_BY e
JOIN EDGARTOOLS_PROD.NEO4J_GRAPH_MIGRATION.GRAPH_NODE_COMPANY c
  ON c.NODEID = IFF(e.TARGET_ENTITY_TYPE = 'company', e.TARGETNODEID, e.SOURCENODEID)
LEFT JOIN EDGARTOOLS_PROD.EDGARTOOLS_GOLD.MDM_COMPANY_ENTITY m
  ON LPAD(m.CIK::STRING, 10, '0') = LPAD(c.PROPERTIES:cik::STRING, 10, '0');

SELECT COLUMN_NAME
FROM EDGARTOOLS_PROD.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_CATALOG = 'EDGARTOOLS_PROD'
  AND TABLE_SCHEMA = 'EDGARTOOLS_SILVER'
  AND TABLE_NAME = 'SEC_EMPLOYMENT_EVENT'
ORDER BY ORDINAL_POSITION;

SELECT COUNT(*) AS row_count
FROM EDGARTOOLS_PROD.EDGARTOOLS_SILVER.SEC_EMPLOYMENT_EVENT;

SELECT COLUMN_NAME
FROM EDGARTOOLS_PROD.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_CATALOG = 'EDGARTOOLS_PROD'
  AND TABLE_SCHEMA = 'EDGARTOOLS_GOLD'
  AND TABLE_NAME = 'EXECUTIVE_RECORDS'
ORDER BY ORDINAL_POSITION;

SELECT COUNT(*) AS row_count,
       COUNT(DISTINCT CIK) AS distinct_cik,
       COUNT(DISTINCT ACCESSION_NUMBER) AS distinct_accession,
       COUNT_IF(TOTAL_COMP IS NOT NULL) AS with_total_comp,
       COUNT_IF(EXEC_NAME IS NOT NULL) AS with_exec_name
FROM EDGARTOOLS_PROD.EDGARTOOLS_GOLD.EXECUTIVE_RECORDS;

SELECT COUNT(DISTINCT e.CIK) AS exec_ciks,
       COUNT(DISTINCT IFF(LOWER(COALESCE(m.TRACKING_STATUS, '')) = 'active', e.CIK, NULL)) AS mdm_active_exec_ciks
FROM EDGARTOOLS_PROD.EDGARTOOLS_GOLD.EXECUTIVE_RECORDS e
LEFT JOIN EDGARTOOLS_PROD.EDGARTOOLS_GOLD.MDM_COMPANY_ENTITY m
  ON LPAD(m.CIK::STRING, 10, '0') = LPAD(e.CIK::STRING, 10, '0');
