-- Ticket 02: live IS_INSIDER input completeness.
-- snow sql --connection edgartools-prod
-- Read-only.

SELECT 'pointer' AS probe,
       p.ACTIVE_GENERATION_ID::VARCHAR AS generation_id,
       p.ACTIVATED_AT::VARCHAR AS activated_at,
       g.NODE_COUNT AS node_count,
       g.EDGE_COUNT AS edge_count
FROM EDGARTOOLS_PROD.NEO4J_GRAPH_MIGRATION.GRAPH_ACTIVE_POINTER p
LEFT JOIN EDGARTOOLS_PROD.NEO4J_GRAPH_MIGRATION.GRAPH_GENERATION g
  ON g.GENERATION_ID = p.ACTIVE_GENERATION_ID
WHERE p.POINTER_ID = 'active';

SELECT 'edge_cols' AS probe, COLUMN_NAME, DATA_TYPE
FROM EDGARTOOLS_PROD.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_CATALOG = 'EDGARTOOLS_PROD'
  AND TABLE_SCHEMA = 'NEO4J_GRAPH_MIGRATION'
  AND TABLE_NAME = 'GRAPH_EDGE_IS_INSIDER'
ORDER BY ORDINAL_POSITION;

SELECT
    'is_insider_counts' AS probe,
    COUNT(*) AS edge_count,
    COUNT(DISTINCT IFF(TARGET_ENTITY_TYPE = 'company', TARGETNODEID, NULL)) AS distinct_company_targets,
    COUNT(DISTINCT IFF(SOURCE_ENTITY_TYPE = 'person', SOURCENODEID, NULL)) AS distinct_person_sources,
    COUNT_IF(SOURCE_ACCESSION IS NOT NULL AND TRIM(SOURCE_ACCESSION) <> '') AS edges_with_accession,
    COUNT_IF(SOURCE_ACCESSION IS NULL OR TRIM(SOURCE_ACCESSION) = '') AS edges_without_accession,
    COUNT_IF(EFFECTIVE_TO IS NULL) AS effective_to_null,
    COUNT_IF(VALID_TO_DATE IS NULL) AS valid_to_null,
    COUNT_IF(EFFECTIVE_TO IS NULL AND SOURCE_ACCESSION IS NOT NULL AND TRIM(SOURCE_ACCESSION) <> '') AS current_with_accession
FROM EDGARTOOLS_PROD.NEO4J_GRAPH_MIGRATION.GRAPH_EDGE_IS_INSIDER;

SELECT 'is_insider_entity_types' AS probe, SOURCE_ENTITY_TYPE, TARGET_ENTITY_TYPE, COUNT(*) AS n
FROM EDGARTOOLS_PROD.NEO4J_GRAPH_MIGRATION.GRAPH_EDGE_IS_INSIDER
GROUP BY 1, 2
ORDER BY n DESC;

SELECT 'is_insider_source_system' AS probe, SOURCE_SYSTEM, COUNT(*) AS n
FROM EDGARTOOLS_PROD.NEO4J_GRAPH_MIGRATION.GRAPH_EDGE_IS_INSIDER
GROUP BY 1
ORDER BY n DESC;

SELECT
    'insider_issuer_overlap' AS probe,
    COUNT(DISTINCT c.PROPERTIES:cik::STRING) AS graph_issuer_ciks,
    COUNT(DISTINCT IFF(LOWER(COALESCE(m.TRACKING_STATUS, '')) = 'active', c.PROPERTIES:cik::STRING, NULL)) AS mdm_active_issuer_ciks
FROM EDGARTOOLS_PROD.NEO4J_GRAPH_MIGRATION.GRAPH_EDGE_IS_INSIDER e
JOIN EDGARTOOLS_PROD.NEO4J_GRAPH_MIGRATION.GRAPH_NODE_COMPANY c
  ON c.NODEID = IFF(e.TARGET_ENTITY_TYPE = 'company', e.TARGETNODEID, e.SOURCENODEID)
LEFT JOIN EDGARTOOLS_PROD.EDGARTOOLS_GOLD.MDM_COMPANY_ENTITY m
  ON LPAD(m.CIK::STRING, 10, '0') = LPAD(c.PROPERTIES:cik::STRING, 10, '0');

SELECT 'oh_cols' AS probe, COLUMN_NAME, DATA_TYPE
FROM EDGARTOOLS_PROD.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_CATALOG = 'EDGARTOOLS_PROD'
  AND TABLE_SCHEMA = 'EDGARTOOLS_GOLD'
  AND TABLE_NAME = 'OWNERSHIP_HOLDINGS'
ORDER BY ORDINAL_POSITION;

SELECT 'oa_owner_cols' AS probe, COLUMN_NAME
FROM EDGARTOOLS_PROD.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_CATALOG = 'EDGARTOOLS_PROD'
  AND TABLE_SCHEMA = 'EDGARTOOLS_GOLD'
  AND TABLE_NAME = 'OWNERSHIP_ACTIVITY'
  AND (COLUMN_NAME ILIKE '%OWNER%' OR COLUMN_NAME ILIKE '%PERSON%' OR COLUMN_NAME ILIKE '%ACCESSION%' OR COLUMN_NAME ILIKE '%CIK%')
ORDER BY COLUMN_NAME;

SELECT
    'oh_counts' AS probe,
    COUNT(*) AS row_count,
    COUNT(DISTINCT COMPANY_KEY) AS distinct_company_key,
    COUNT(DISTINCT ACCESSION_NUMBER) AS distinct_accession
FROM EDGARTOOLS_PROD.EDGARTOOLS_GOLD.OWNERSHIP_HOLDINGS;

SELECT
    'oa_counts' AS probe,
    COUNT(*) AS row_count,
    COUNT(DISTINCT COMPANY_KEY) AS distinct_company_key
FROM EDGARTOOLS_PROD.EDGARTOOLS_GOLD.OWNERSHIP_ACTIVITY;

SELECT 'silver_owner_cols' AS probe, COLUMN_NAME
FROM EDGARTOOLS_PROD.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_CATALOG = 'EDGARTOOLS_PROD'
  AND TABLE_SCHEMA = 'EDGARTOOLS_SILVER'
  AND TABLE_NAME = 'SEC_OWNERSHIP_REPORTING_OWNER'
  AND (COLUMN_NAME ILIKE '%OWNER%' OR COLUMN_NAME ILIKE '%CIK%' OR COLUMN_NAME ILIKE '%NAME%' OR COLUMN_NAME ILIKE '%ACCESSION%' OR COLUMN_NAME ILIKE '%PERSON%')
ORDER BY COLUMN_NAME;

SELECT
    'silver_owner_counts' AS probe,
    COUNT(*) AS row_count,
    COUNT(DISTINCT ACCESSION_NUMBER) AS distinct_accession
FROM EDGARTOOLS_PROD.EDGARTOOLS_SILVER.SEC_OWNERSHIP_REPORTING_OWNER;

SELECT 'mdm_active' AS probe, COUNT(*) AS n
FROM EDGARTOOLS_PROD.EDGARTOOLS_GOLD.MDM_COMPANY_ENTITY
WHERE LOWER(COALESCE(TRACKING_STATUS, '')) = 'active';
