-- Ticket 03: live EMPLOYED_BY input completeness.
-- snow sql --connection edgartools-prod
-- Read-only.

SELECT 'pointer' AS probe,
       p.ACTIVE_GENERATION_ID::VARCHAR AS generation_id,
       p.ACTIVATED_AT::VARCHAR AS activated_at,
       g.NODE_COUNT AS node_count,
       g.EDGE_COUNT AS edge_count
FROM EDGARTOOLS_PROD.NEO4J_GRAPH_MIGRATION.GRAPH_ACTIVE_POINTER p
LEFT JOIN EDGARTOOLS_PROD.NEO4J_GRAPH_MIGRATION.GRAPH_GENERATION g
  ON g.GENERATION_ID = p.ACTIVE_GENERATION_ID
WHERE p.POINTER_ID = 'active';

SELECT 'edge_cols' AS probe, COLUMN_NAME, DATA_TYPE
FROM EDGARTOOLS_PROD.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_CATALOG = 'EDGARTOOLS_PROD'
  AND TABLE_SCHEMA = 'NEO4J_GRAPH_MIGRATION'
  AND TABLE_NAME = 'GRAPH_EDGE_EMPLOYED_BY'
ORDER BY ORDINAL_POSITION;

SELECT
    'employed_by_counts' AS probe,
    COUNT(*) AS edge_count,
    COUNT(DISTINCT IFF(TARGET_ENTITY_TYPE = 'company', TARGETNODEID, NULL)) AS distinct_company_targets,
    COUNT(DISTINCT IFF(SOURCE_ENTITY_TYPE = 'person', SOURCENODEID, NULL)) AS distinct_person_sources,
    COUNT_IF(SOURCE_ACCESSION IS NOT NULL AND TRIM(SOURCE_ACCESSION) <> '') AS edges_with_accession,
    COUNT_IF(EFFECTIVE_TO IS NULL) AS effective_to_null,
    COUNT_IF(VALID_TO_DATE IS NULL) AS valid_to_null
FROM EDGARTOOLS_PROD.NEO4J_GRAPH_MIGRATION.GRAPH_EDGE_EMPLOYED_BY;

SELECT 'employed_by_entity_types' AS probe, SOURCE_ENTITY_TYPE, TARGET_ENTITY_TYPE, COUNT(*) AS n
FROM EDGARTOOLS_PROD.NEO4J_GRAPH_MIGRATION.GRAPH_EDGE_EMPLOYED_BY
GROUP BY 1, 2
ORDER BY n DESC;

SELECT 'employed_by_source_system' AS probe, SOURCE_SYSTEM, COUNT(*) AS n
FROM EDGARTOOLS_PROD.NEO4J_GRAPH_MIGRATION.GRAPH_EDGE_EMPLOYED_BY
GROUP BY 1
ORDER BY n DESC;

SELECT
    'employed_issuer_overlap' AS probe,
    COUNT(DISTINCT c.PROPERTIES:cik::STRING) AS graph_issuer_ciks,
    COUNT(DISTINCT IFF(LOWER(COALESCE(m.TRACKING_STATUS, '')) = 'active', c.PROPERTIES:cik::STRING, NULL)) AS mdm_active_issuer_ciks
FROM EDGARTOOLS_PROD.NEO4J_GRAPH_MIGRATION.GRAPH_EDGE_EMPLOYED_BY e
JOIN EDGARTOOLS_PROD.NEO4J_GRAPH_MIGRATION.GRAPH_NODE_COMPANY c
  ON c.NODEID = IFF(e.TARGET_ENTITY_TYPE = 'company', e.TARGETNODEID, e.SOURCENODEID)
LEFT JOIN EDGARTOOLS_PROD.EDGARTOOLS_GOLD.MDM_COMPANY_ENTITY m
  ON LPAD(m.CIK::STRING, 10, '0') = LPAD(c.PROPERTIES:cik::STRING, 10, '0');

SELECT 'silver_emp_cols' AS probe, COLUMN_NAME, DATA_TYPE
FROM EDGARTOOLS_PROD.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_CATALOG = 'EDGARTOOLS_PROD'
  AND TABLE_SCHEMA = 'EDGARTOOLS_SILVER'
  AND TABLE_NAME = 'SEC_EMPLOYMENT_EVENT'
ORDER BY ORDINAL_POSITION;

SELECT
    'silver_emp_counts' AS probe,
    COUNT(*) AS row_count
FROM EDGARTOOLS_PROD.EDGARTOOLS_SILVER.SEC_EMPLOYMENT_EVENT;

SELECT 'exec_cols' AS probe, COLUMN_NAME, DATA_TYPE
FROM EDGARTOOLS_PROD.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_CATALOG = 'EDGARTOOLS_PROD'
  AND TABLE_SCHEMA = 'EDGARTOOLS_GOLD'
  AND TABLE_NAME = 'EXECUTIVE_RECORDS'
ORDER BY ORDINAL_POSITION;

SELECT
    'exec_counts' AS probe,
    COUNT(*) AS row_count,
    COUNT(DISTINCT CIK) AS distinct_cik,
    COUNT(DISTINCT ACCESSION_NUMBER) AS distinct_accession,
    COUNT_IF(TOTAL_COMP IS NOT NULL) AS with_total_comp,
    COUNT_IF(EXEC_NAME IS NOT NULL) AS with_exec_name
FROM EDGARTOOLS_PROD.EDGARTOOLS_GOLD.EXECUTIVE_RECORDS;

SELECT
    'exec_mdm_active_overlap' AS probe,
    COUNT(DISTINCT e.CIK) AS exec_ciks,
    COUNT(DISTINCT IFF(LOWER(COALESCE(m.TRACKING_STATUS, '')) = 'active', e.CIK, NULL)) AS mdm_active_exec_ciks
FROM EDGARTOOLS_PROD.EDGARTOOLS_GOLD.EXECUTIVE_RECORDS e
LEFT JOIN EDGARTOOLS_PROD.EDGARTOOLS_GOLD.MDM_COMPANY_ENTITY m
  ON LPAD(m.CIK::STRING, 10, '0') = LPAD(e.CIK::STRING, 10, '0');
