-- Ticket 07: first layer that shrinks to 21 CIKs.
-- snow sql --connection edgartools-prod

SELECT 'gold_factors' AS layer, COUNT(*) AS row_count, COUNT(DISTINCT CIK) AS ciks
FROM EDGARTOOLS_PROD.EDGARTOOLS_GOLD.FINANCIAL_FACTORS
UNION ALL
SELECT 'gold_derived', COUNT(*), COUNT(DISTINCT CIK)
FROM EDGARTOOLS_PROD.EDGARTOOLS_GOLD.FINANCIAL_DERIVED
UNION ALL
SELECT 'gold_facts', COUNT(*), COUNT(DISTINCT CIK)
FROM EDGARTOOLS_PROD.EDGARTOOLS_GOLD.FINANCIAL_FACTS
UNION ALL
SELECT 'silver_derived', COUNT(*), COUNT(DISTINCT CIK)
FROM EDGARTOOLS_PROD.EDGARTOOLS_SILVER.SEC_FINANCIAL_DERIVED
UNION ALL
SELECT 'silver_facts', COUNT(*), COUNT(DISTINCT CIK)
FROM EDGARTOOLS_PROD.EDGARTOOLS_SILVER.SEC_FINANCIAL_FACT
UNION ALL
SELECT 'landing_derived', COUNT(*), COUNT(DISTINCT CIK)
FROM EDGARTOOLS_PROD.EDGARTOOLS_SILVER_LANDING.SEC_FINANCIAL_DERIVED
UNION ALL
SELECT 'landing_facts', COUNT(*), COUNT(DISTINCT CIK)
FROM EDGARTOOLS_PROD.EDGARTOOLS_SILVER_LANDING.SEC_FINANCIAL_FACT
UNION ALL
SELECT 'gold_company', COUNT(*), COUNT(DISTINCT CIK)
FROM EDGARTOOLS_PROD.EDGARTOOLS_GOLD.COMPANY
UNION ALL
SELECT 'mdm_active', COUNT(*), COUNT(DISTINCT CIK)
FROM EDGARTOOLS_PROD.EDGARTOOLS_GOLD.MDM_COMPANY_ENTITY
WHERE LOWER(COALESCE(TRACKING_STATUS, '')) = 'active';

SELECT CIK, COUNT(*) AS factor_rows
FROM EDGARTOOLS_PROD.EDGARTOOLS_GOLD.FINANCIAL_FACTORS
GROUP BY CIK
ORDER BY CIK;

SELECT f.CIK, c.ENTITY_NAME
FROM (
    SELECT DISTINCT CIK FROM EDGARTOOLS_PROD.EDGARTOOLS_GOLD.FINANCIAL_FACTORS
) f
LEFT JOIN EDGARTOOLS_PROD.EDGARTOOLS_GOLD.COMPANY c
  ON LPAD(c.CIK::STRING, 10, '0') = LPAD(f.CIK::STRING, 10, '0')
ORDER BY f.CIK;

SELECT
    COUNT(DISTINCT f.CIK) AS fact_ciks_not_in_derived
FROM EDGARTOOLS_PROD.EDGARTOOLS_GOLD.FINANCIAL_FACTS f
WHERE NOT EXISTS (
    SELECT 1
    FROM EDGARTOOLS_PROD.EDGARTOOLS_GOLD.FINANCIAL_DERIVED d
    WHERE LPAD(d.CIK::STRING, 10, '0') = LPAD(f.CIK::STRING, 10, '0')
);

SELECT MIN(INGESTED_AT) AS min_ingested, MAX(INGESTED_AT) AS max_ingested
FROM EDGARTOOLS_PROD.EDGARTOOLS_GOLD.FINANCIAL_DERIVED;

SELECT MIN(INGESTED_AT) AS min_ingested, MAX(INGESTED_AT) AS max_ingested
FROM EDGARTOOLS_PROD.EDGARTOOLS_GOLD.FINANCIAL_FACTS;
