-- Refresh issuer neighborhood live counts after rebase onto origin/main
-- (INSTITUTIONAL_HOLDS backfill + graph rebuild). Counts only.

SELECT 'pointer' AS probe,
       p.POINTER_ID::VARCHAR AS k1,
       p.ACTIVE_GENERATION_ID::VARCHAR AS k2,
       p.ACTIVATED_AT::VARCHAR AS k3,
       g.NODE_COUNT::VARCHAR AS n1,
       g.EDGE_COUNT::VARCHAR AS n2
FROM EDGARTOOLS_PROD.NEO4J_GRAPH_MIGRATION.GRAPH_ACTIVE_POINTER p
LEFT JOIN EDGARTOOLS_PROD.NEO4J_GRAPH_MIGRATION.GRAPH_GENERATION g
  ON g.GENERATION_ID = p.ACTIVE_GENERATION_ID
WHERE p.POINTER_ID = 'active';

SELECT 'edge_is_insider' AS probe, COUNT(*)::VARCHAR AS n1 FROM EDGARTOOLS_PROD.NEO4J_GRAPH_MIGRATION.GRAPH_EDGE_IS_INSIDER;
SELECT 'edge_employed_by' AS probe, COUNT(*)::VARCHAR AS n1 FROM EDGARTOOLS_PROD.NEO4J_GRAPH_MIGRATION.GRAPH_EDGE_EMPLOYED_BY;
SELECT 'edge_institutional_holds' AS probe, COUNT(*)::VARCHAR AS n1 FROM EDGARTOOLS_PROD.NEO4J_GRAPH_MIGRATION.GRAPH_EDGE_INSTITUTIONAL_HOLDS;
SELECT 'edge_audited_by' AS probe, COUNT(*)::VARCHAR AS n1 FROM EDGARTOOLS_PROD.NEO4J_GRAPH_MIGRATION.GRAPH_EDGE_AUDITED_BY;
SELECT 'edge_has_parent' AS probe, COUNT(*)::VARCHAR AS n1 FROM EDGARTOOLS_PROD.NEO4J_GRAPH_MIGRATION.GRAPH_EDGE_HAS_PARENT_COMPANY;
SELECT 'edge_holds' AS probe, COUNT(*)::VARCHAR AS n1 FROM EDGARTOOLS_PROD.NEO4J_GRAPH_MIGRATION.GRAPH_EDGE_HOLDS;
SELECT 'edge_company_holds' AS probe, COUNT(*)::VARCHAR AS n1 FROM EDGARTOOLS_PROD.NEO4J_GRAPH_MIGRATION.GRAPH_EDGE_COMPANY_HOLDS;

SELECT 'gold_institutional_holdings' AS probe, COUNT(*)::VARCHAR AS n1 FROM EDGARTOOLS_PROD.EDGARTOOLS_GOLD.INSTITUTIONAL_HOLDINGS;
SELECT 'gold_ownership_holdings' AS probe, COUNT(*)::VARCHAR AS n1 FROM EDGARTOOLS_PROD.EDGARTOOLS_GOLD.OWNERSHIP_HOLDINGS;
SELECT 'gold_executive_records' AS probe, COUNT(*)::VARCHAR AS n1 FROM EDGARTOOLS_PROD.EDGARTOOLS_GOLD.EXECUTIVE_RECORDS;
SELECT 'gold_financial_factors' AS probe, COUNT(*)::VARCHAR AS n1 FROM EDGARTOOLS_PROD.EDGARTOOLS_GOLD.FINANCIAL_FACTORS;
SELECT 'source_auditor' AS probe, COUNT(*)::VARCHAR AS n1 FROM EDGARTOOLS_PROD.EDGARTOOLS_SOURCE.SEC_AUDITOR_REPORT_EVIDENCE;
SELECT 'silver_auditor' AS probe, COUNT(*)::VARCHAR AS n1 FROM EDGARTOOLS_PROD.EDGARTOOLS_SILVER.SEC_AUDITOR_REPORT_EVIDENCE;
SELECT 'silver_subsidiary' AS probe, COUNT(*)::VARCHAR AS n1 FROM EDGARTOOLS_PROD.EDGARTOOLS_SILVER.SEC_SUBSIDIARY_EVIDENCE;
SELECT 'silver_employment_event' AS probe, COUNT(*)::VARCHAR AS n1 FROM EDGARTOOLS_PROD.EDGARTOOLS_SILVER.SEC_EMPLOYMENT_EVENT;
SELECT 'mdm_company_active' AS probe, COUNT(*)::VARCHAR AS n1
FROM EDGARTOOLS_PROD.EDGARTOOLS_GOLD.MDM_COMPANY_ENTITY
WHERE LOWER(COALESCE(TRACKING_STATUS, '')) = 'active';
SELECT 'gold_company' AS probe, COUNT(*)::VARCHAR AS n1 FROM EDGARTOOLS_PROD.EDGARTOOLS_GOLD.COMPANY;

SELECT 'ih_has_issuer_cik' AS probe, COUNT(*)::VARCHAR AS n1
FROM EDGARTOOLS_PROD.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'EDGARTOOLS_GOLD'
  AND TABLE_NAME = 'INSTITUTIONAL_HOLDINGS'
  AND COLUMN_NAME ILIKE '%ISSUER%CIK%';

SELECT 'oh_owner_cols' AS probe, COLUMN_NAME AS k1
FROM EDGARTOOLS_PROD.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'EDGARTOOLS_GOLD'
  AND TABLE_NAME = 'OWNERSHIP_HOLDINGS'
  AND (COLUMN_NAME ILIKE '%OWNER%' OR COLUMN_NAME ILIKE '%PERSON%' OR COLUMN_NAME ILIKE '%ACCESSION%')
ORDER BY COLUMN_NAME;
