-- Continuation of ticket 13: columns, silver/source, graph nodes, pointer.

SELECT 'pointer' AS probe, p.ACTIVE_GENERATION_ID::VARCHAR AS k1, p.ACTIVATED_AT::VARCHAR AS k2,
       g.NODE_COUNT::VARCHAR AS n1, g.EDGE_COUNT::VARCHAR AS n2
FROM EDGARTOOLS_PROD.NEO4J_GRAPH_MIGRATION.GRAPH_ACTIVE_POINTER p
LEFT JOIN EDGARTOOLS_PROD.NEO4J_GRAPH_MIGRATION.GRAPH_GENERATION g
  ON g.GENERATION_ID = p.ACTIVE_GENERATION_ID
WHERE p.POINTER_ID = 'active';

SELECT 'ff_cols' AS probe, COLUMN_NAME AS k1
FROM EDGARTOOLS_PROD.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'EDGARTOOLS_GOLD' AND TABLE_NAME = 'FINANCIAL_FACTORS'
  AND COLUMN_NAME ILIKE ANY ('EBITDA%','EPS%','ROE','ROA','RETURN_ON%','OPERATING_MARGIN')
ORDER BY COLUMN_NAME;

SELECT 'oh_person_cols' AS probe, COLUMN_NAME AS k1
FROM EDGARTOOLS_PROD.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'EDGARTOOLS_GOLD' AND TABLE_NAME = 'OWNERSHIP_HOLDINGS'
  AND (COLUMN_NAME ILIKE '%OWNER%' OR COLUMN_NAME ILIKE '%PERSON%' OR COLUMN_NAME ILIKE '%ACCESSION%')
ORDER BY COLUMN_NAME;

SELECT 'ih_issuer_cols' AS probe, COLUMN_NAME AS k1
FROM EDGARTOOLS_PROD.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'EDGARTOOLS_GOLD' AND TABLE_NAME = 'INSTITUTIONAL_HOLDINGS'
  AND (COLUMN_NAME ILIKE '%ISSUER%' OR COLUMN_NAME ILIKE '%MANAGER%' OR COLUMN_NAME ILIKE '%CIK%' OR COLUMN_NAME ILIKE '%CUSIP%' OR COLUMN_NAME ILIKE '%SHARE%')
ORDER BY COLUMN_NAME;

SELECT 'graph_nodes' AS probe, ENTITY_TYPE AS k1, COUNT(*)::VARCHAR AS n1
FROM EDGARTOOLS_PROD.NEO4J_GRAPH_MIGRATION.MDM_GRAPH_NODES n
JOIN EDGARTOOLS_PROD.NEO4J_GRAPH_MIGRATION.GRAPH_ACTIVE_POINTER p
  ON p.POINTER_ID = 'active' AND p.ACTIVE_GENERATION_ID = n.GENERATION_ID
GROUP BY ENTITY_TYPE
ORDER BY 1;

SELECT 'silver_auditor' AS probe, COUNT(*)::VARCHAR AS n1 FROM EDGARTOOLS_PROD.EDGARTOOLS_SILVER.SEC_AUDITOR_REPORT_EVIDENCE;
SELECT 'silver_subsidiary' AS probe, COUNT(*)::VARCHAR AS n1 FROM EDGARTOOLS_PROD.EDGARTOOLS_SILVER.SEC_SUBSIDIARY_EVIDENCE;
SELECT 'silver_employment' AS probe, COUNT(*)::VARCHAR AS n1 FROM EDGARTOOLS_PROD.EDGARTOOLS_SILVER.SEC_EMPLOYMENT_EVENT;
SELECT 'silver_thirteenf_filing' AS probe, COUNT(*)::VARCHAR AS n1 FROM EDGARTOOLS_PROD.EDGARTOOLS_SILVER.SEC_THIRTEENF_FILING;
SELECT 'silver_ownership_owner' AS probe, COUNT(*)::VARCHAR AS n1 FROM EDGARTOOLS_PROD.EDGARTOOLS_SILVER.SEC_OWNERSHIP_REPORTING_OWNER;
SELECT 'source_auditor' AS probe, COUNT(*)::VARCHAR AS n1 FROM EDGARTOOLS_PROD.EDGARTOOLS_SOURCE.SEC_AUDITOR_REPORT_EVIDENCE;
SELECT 'source_thirteenf_filing' AS probe, COUNT(*)::VARCHAR AS n1
FROM EDGARTOOLS_PROD.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'EDGARTOOLS_SOURCE' AND TABLE_NAME = 'SEC_THIRTEENF_FILING';

SELECT 'gold_company' AS probe, COUNT(*)::VARCHAR AS n1 FROM EDGARTOOLS_PROD.EDGARTOOLS_GOLD.COMPANY;
SELECT 'mdm_company_entity' AS probe, COUNT(*)::VARCHAR AS n1 FROM EDGARTOOLS_PROD.EDGARTOOLS_GOLD.MDM_COMPANY_ENTITY;
SELECT 'mdm_company_entity_active' AS probe, COUNT(*)::VARCHAR AS n1
FROM EDGARTOOLS_PROD.EDGARTOOLS_GOLD.MDM_COMPANY_ENTITY
WHERE LOWER(COALESCE(TRACKING_STATUS,'')) = 'active';

SELECT 'decision_objects' AS probe, TABLE_NAME AS k1
FROM EDGARTOOLS_PROD.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'EDGARTOOLS_DECISION'
ORDER BY 1;

SELECT 'mdm_schema_tables' AS probe, COUNT(*)::VARCHAR AS n1
FROM EDGARTOOLS_PROD.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'MDM';
