SELECT 'is_person_of' AS probe, COUNT(*)::VARCHAR AS n1
FROM EDGARTOOLS_PROD.NEO4J_GRAPH_MIGRATION.GRAPH_EDGE_IS_PERSON_OF;
SELECT 'node_auditfirm' AS probe, COUNT(*)::VARCHAR AS n1
FROM EDGARTOOLS_PROD.NEO4J_GRAPH_MIGRATION.GRAPH_NODE_AUDITFIRM;
SELECT 'dashboard_objs' AS probe, TABLE_NAME AS k1
FROM EDGARTOOLS_PROD.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA IN ('EDGARTOOLS_DASHBOARD','MDM_GRAPH_REVIEW_DASHBOARD','EDGARTOOLS_DECISION','PUBLIC')
ORDER BY TABLE_SCHEMA, TABLE_NAME;
SHOW STREAMLITS IN DATABASE EDGARTOOLS_PROD;
