-- Full schema inventory: every table/view in prod databases agents might see.

SELECT SCHEMA_NAME
FROM EDGARTOOLS_PROD.INFORMATION_SCHEMA.SCHEMATA
ORDER BY SCHEMA_NAME;

SELECT TABLE_SCHEMA, TABLE_TYPE, TABLE_NAME, ROW_COUNT
FROM EDGARTOOLS_PROD.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA NOT IN ('INFORMATION_SCHEMA')
ORDER BY TABLE_SCHEMA, TABLE_TYPE, TABLE_NAME;

SELECT TABLE_SCHEMA, TABLE_NAME
FROM EDGARTOOLS_PROD.INFORMATION_SCHEMA.VIEWS
WHERE TABLE_SCHEMA NOT IN ('INFORMATION_SCHEMA')
ORDER BY TABLE_SCHEMA, TABLE_NAME;
