#!/usr/bin/env bash
# Stage 4 — Composite-key MERGE semantics smoke test (REQUIRES Snowflake creds).
#
# Verifies the new LOAD_FUNDAMENTALS_EXPORTS_FOR_RUN proc's composite-key MERGE
# actually upserts (not duplicates) by direct INSERT+SELECT against the source
# tables.  Tests:
#   - Idempotency: insert same row twice, COUNT = 1
#   - Update on conflict: change a non-key column, observe the change
#   - NOT NULL enforcement: NULL PK column rejected by Snowflake
#
# This is a DIRECT-INSERT smoke test — it does NOT exercise the full Parquet
# COPY INTO + MERGE path (that requires PR-2's warehouse export to land a real
# Parquet file in S3).  Stage 5 covers the full roundtrip.

# shellcheck disable=SC1091
source "$(dirname "${BASH_SOURCE[0]}")/00_lib.sh"

step "Stage 4 — Composite-key MERGE semantics smoke test"

require_command snowsql
require_env SNOWFLAKE_DATABASE

SOURCE_SCHEMA="${SNOWFLAKE_SOURCE_SCHEMA:-EDGARTOOLS_SOURCE}"
TEST_CIK="999999991"  # synthetic CIK, no real company uses this
TEST_ACCESSION="0000-pr1-verify-${TEST_CIK}"

# Track whether the test ran (skip teardown if setup failed)
TEST_STARTED=false

snowsql_run() {
    snowsql -q "$1" \
        -o output_format=plain -o header=false -o friendly=false -o quiet=true 2>/dev/null \
        | tr -d ' \r\n'
}

cleanup() {
    if $TEST_STARTED; then
        log "Cleaning up test rows for CIK=${TEST_CIK}"
        snowsql -q "
            DELETE FROM ${SNOWFLAKE_DATABASE}.${SOURCE_SCHEMA}.SEC_FINANCIAL_FACT WHERE CIK=${TEST_CIK};
        " -o quiet=true -o friendly=false 2>/dev/null || true
    fi
}
trap cleanup EXIT

# ── 1. Idempotency: INSERT twice, expect COUNT=1 (composite key upserts) ──
log "Test 1 — composite-key idempotency"
TEST_STARTED=true

snowsql -q "
    INSERT INTO ${SNOWFLAKE_DATABASE}.${SOURCE_SCHEMA}.SEC_FINANCIAL_FACT
        (CIK, ACCESSION_NUMBER, CONCEPT, FISCAL_PERIOD, SEGMENT, VALUE, PARSER_VERSION)
    VALUES
        (${TEST_CIK}, '${TEST_ACCESSION}', 'Revenues', 'FY', 'consolidated', 100.0, 'pr1-verify');
" -o quiet=true -o friendly=false >/dev/null 2>&1 \
    && ok "first INSERT succeeded" \
    || { fail_check "first INSERT FAILED"; print_summary "4 merge-proc-smoke"; exit 1; }

# Re-INSERT the same row.  Direct INSERT does NOT MERGE — it would create a
# duplicate.  But since the table is the SOURCE table that the load proc will
# MERGE INTO from a temp table, the test that matters is: does the MERGE
# generated by the proc correctly use the composite key?
#
# We simulate that by manually invoking the same MERGE the proc would emit:
log "  (simulating proc's MERGE via a temp table to test idempotency)"

snowsql -q "
    CREATE OR REPLACE TEMPORARY TABLE TMP_PR1_VERIFY LIKE ${SNOWFLAKE_DATABASE}.${SOURCE_SCHEMA}.SEC_FINANCIAL_FACT;
    INSERT INTO TMP_PR1_VERIFY
        (CIK, ACCESSION_NUMBER, CONCEPT, FISCAL_PERIOD, SEGMENT, VALUE, PARSER_VERSION)
    VALUES
        (${TEST_CIK}, '${TEST_ACCESSION}', 'Revenues', 'FY', 'consolidated', 200.0, 'pr1-verify-v2');

    MERGE INTO ${SNOWFLAKE_DATABASE}.${SOURCE_SCHEMA}.SEC_FINANCIAL_FACT AS target
    USING TMP_PR1_VERIFY AS source
    ON target.CIK = source.CIK
       AND target.ACCESSION_NUMBER = source.ACCESSION_NUMBER
       AND target.CONCEPT = source.CONCEPT
       AND target.FISCAL_PERIOD = source.FISCAL_PERIOD
       AND target.SEGMENT = source.SEGMENT
    WHEN MATCHED THEN UPDATE SET
        VALUE = source.VALUE,
        PARSER_VERSION = source.PARSER_VERSION
    WHEN NOT MATCHED THEN INSERT (CIK, ACCESSION_NUMBER, CONCEPT, FISCAL_PERIOD, SEGMENT, VALUE, PARSER_VERSION)
        VALUES (source.CIK, source.ACCESSION_NUMBER, source.CONCEPT, source.FISCAL_PERIOD, source.SEGMENT, source.VALUE, source.PARSER_VERSION);
" -o quiet=true -o friendly=false >/dev/null 2>&1 \
    && ok "MERGE upsert succeeded" \
    || fail_check "MERGE upsert FAILED"

# After insert + merge: should be exactly 1 row, value should be the new value
count=$(snowsql_run "SELECT COUNT(*) FROM ${SNOWFLAKE_DATABASE}.${SOURCE_SCHEMA}.SEC_FINANCIAL_FACT WHERE CIK=${TEST_CIK};")
if [[ "$count" == "1" ]]; then
    ok "composite-key MERGE is idempotent (COUNT=1 after INSERT+MERGE)"
else
    fail_check "composite-key MERGE NOT idempotent — expected COUNT=1, got ${count}"
fi

value=$(snowsql_run "SELECT VALUE FROM ${SNOWFLAKE_DATABASE}.${SOURCE_SCHEMA}.SEC_FINANCIAL_FACT WHERE CIK=${TEST_CIK};")
if [[ "$value" == "200" ]] || [[ "$value" == "200.0" ]]; then
    ok "MERGE updated non-key column (VALUE: 100.0 → 200.0)"
else
    fail_check "MERGE did NOT update non-key column — expected 200.0, got ${value}"
fi

# ── 2. NOT NULL enforcement on PK columns ──────────────────────────
log "Test 2 — NOT NULL enforcement on PK columns (Q5-C)"

# Try INSERT with NULL CIK (PK column) — should fail
if snowsql -q "
    INSERT INTO ${SNOWFLAKE_DATABASE}.${SOURCE_SCHEMA}.SEC_FINANCIAL_FACT
        (CIK, ACCESSION_NUMBER, CONCEPT, FISCAL_PERIOD, SEGMENT, VALUE)
    VALUES (NULL, 'bad', 'Revenues', 'FY', 'consolidated', 1.0);
" -o quiet=true -o friendly=false >/dev/null 2>&1; then
    fail_check "NULL CIK INSERT was ACCEPTED (NOT NULL constraint not enforced!)"
else
    ok "NULL CIK INSERT was REJECTED (NOT NULL constraint enforced)"
fi

# Try INSERT with NULL CONCEPT (composite PK part) — should fail
if snowsql -q "
    INSERT INTO ${SNOWFLAKE_DATABASE}.${SOURCE_SCHEMA}.SEC_FINANCIAL_FACT
        (CIK, ACCESSION_NUMBER, CONCEPT, FISCAL_PERIOD, SEGMENT, VALUE)
    VALUES (${TEST_CIK}, 'bad', NULL, 'FY', 'consolidated', 1.0);
" -o quiet=true -o friendly=false >/dev/null 2>&1; then
    fail_check "NULL CONCEPT INSERT was ACCEPTED (NOT NULL on composite PK part not enforced!)"
else
    ok "NULL CONCEPT INSERT was REJECTED (composite-PK NOT NULL enforced)"
fi

# ── 3. Procedure invocation smoke (proc exists and parses) ─────────
log "Test 3 — invoke LOAD_FUNDAMENTALS_EXPORTS_FOR_RUN with a fake run id"

# Should fail with "No run manifest found" — that proves the proc parses and
# runs to its first SELECT.  It should NOT raise an "unknown procedure" error.
result=$(snowsql -q "CALL ${SNOWFLAKE_DATABASE}.${SOURCE_SCHEMA}.LOAD_FUNDAMENTALS_EXPORTS_FOR_RUN('pr1-verify-workflow', 'pr1-verify-${TEST_CIK}');" \
    -o output_format=plain -o friendly=false 2>&1 || true)

if echo "$result" | grep -qE "No run manifest|manifest" ; then
    ok "proc invocation parses and runs (expected 'No run manifest' error received)"
elif echo "$result" | grep -qiE "does not exist|unknown procedure"; then
    fail_check "proc does NOT exist in Snowflake — re-run stage 3"
else
    warn "unexpected proc response: $(echo "$result" | head -1)"
fi

print_summary "4 merge-proc-smoke"
