-- Neo4j Graph Analytics Native App grants for EdgarTools dev graph verification.
--
-- Run with ACCOUNTADMIN or a delegated Snowflake platform role that can manage
-- Native App grants, database roles, and application-role grants.
--
-- Scope:
--   App:      Neo4j_Graph_Analytics
--   Database: EDGARTOOLS_DEV
--   Schema:   EDGARTOOLS_DEV.NEO4J_GRAPH_MIGRATION
--
-- This script grants only the graph schema access required for Phase 3
-- `edgar-warehouse mdm verify-graph` Native App smoke checks. CREATE TABLE is
-- included because Neo4j Graph Analytics algorithms write bounded result tables
-- into the governed graph schema.

USE DATABASE EDGARTOOLS_DEV;

SHOW APPLICATIONS LIKE 'Neo4j_Graph_Analytics';

CREATE DATABASE ROLE IF NOT EXISTS NEO4J_GRAPH_ANALYTICS_MIGRATION_ROLE;

GRANT USAGE ON DATABASE EDGARTOOLS_DEV
  TO DATABASE ROLE NEO4J_GRAPH_ANALYTICS_MIGRATION_ROLE;
GRANT USAGE ON SCHEMA EDGARTOOLS_DEV.NEO4J_GRAPH_MIGRATION
  TO DATABASE ROLE NEO4J_GRAPH_ANALYTICS_MIGRATION_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA EDGARTOOLS_DEV.NEO4J_GRAPH_MIGRATION
  TO DATABASE ROLE NEO4J_GRAPH_ANALYTICS_MIGRATION_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA EDGARTOOLS_DEV.NEO4J_GRAPH_MIGRATION
  TO DATABASE ROLE NEO4J_GRAPH_ANALYTICS_MIGRATION_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA EDGARTOOLS_DEV.NEO4J_GRAPH_MIGRATION
  TO DATABASE ROLE NEO4J_GRAPH_ANALYTICS_MIGRATION_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA EDGARTOOLS_DEV.NEO4J_GRAPH_MIGRATION
  TO DATABASE ROLE NEO4J_GRAPH_ANALYTICS_MIGRATION_ROLE;

GRANT CREATE TABLE ON SCHEMA EDGARTOOLS_DEV.NEO4J_GRAPH_MIGRATION
  TO DATABASE ROLE NEO4J_GRAPH_ANALYTICS_MIGRATION_ROLE;

GRANT DATABASE ROLE NEO4J_GRAPH_ANALYTICS_MIGRATION_ROLE
  TO APPLICATION Neo4j_Graph_Analytics;

CREATE ROLE IF NOT EXISTS EDGARTOOLS_GRAPH_APP_USER;
CREATE ROLE IF NOT EXISTS EDGARTOOLS_GRAPH_APP_ADMIN;

GRANT APPLICATION ROLE Neo4j_Graph_Analytics.app_user
  TO ROLE EDGARTOOLS_GRAPH_APP_USER;
GRANT APPLICATION ROLE Neo4j_Graph_Analytics.app_admin
  TO ROLE EDGARTOOLS_GRAPH_APP_ADMIN;

GRANT USAGE ON DATABASE EDGARTOOLS_DEV
  TO ROLE EDGARTOOLS_GRAPH_APP_USER;
GRANT USAGE ON SCHEMA EDGARTOOLS_DEV.NEO4J_GRAPH_MIGRATION
  TO ROLE EDGARTOOLS_GRAPH_APP_USER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA EDGARTOOLS_DEV.NEO4J_GRAPH_MIGRATION
  TO ROLE EDGARTOOLS_GRAPH_APP_USER;

SHOW GRANTS TO APPLICATION Neo4j_Graph_Analytics;
SHOW GRANTS OF APPLICATION ROLE Neo4j_Graph_Analytics.app_user;
SHOW GRANTS OF APPLICATION ROLE Neo4j_Graph_Analytics.app_admin;
CALL Neo4j_Graph_Analytics.graph.show_available_compute_pools();
