"""Regenerate edgar_warehouse/silver_schema.py from a live in-memory SilverDatabase.

silver-merge-engine-migration Ticket 13. The snapshot is the DuckDB-free
source of each landing table's column order and NOT NULL set, which
`_record_landing_passthrough` and the in-run lookup used to read from
DuckDB's information_schema. Generated from a live connection, not from a
parse of `_DDL`: the live schema is `_DDL` plus `_schema_migrations()`.

Run: uv run python scripts/dev/regenerate_silver_schema.py
Deleted with the DuckDB engine (Ticket 17); the snapshot is then edited by
hand alongside infra/snowflake/sql/bootstrap/11_silver_landing_schema.sql.
"""

from __future__ import annotations

import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
TARGET = REPO_ROOT / "edgar_warehouse" / "silver_schema.py"
LANDING_SQL = REPO_ROOT / "infra" / "snowflake" / "sql" / "bootstrap" / "11_silver_landing_schema.sql"

HEADER = '''"""Silver landing tables: column order and NOT NULL set, without DuckDB.

silver-merge-engine-migration Ticket 13. GENERATED by
scripts/dev/regenerate_silver_schema.py from a live in-memory SilverDatabase
(its `_DDL` plus every `_schema_migrations()` ALTER); do not edit by hand
while that generator exists. `_record_landing_passthrough` raises on a row
missing a REQUIRED column, and the in-run lookup (ADR 0011) returns rows
shaped by COLUMNS. Scope: the tables that go through the passthrough, which
is also the set infra/snowflake/sql/bootstrap/11_silver_landing_schema.sql
creates (tests/unit/test_silver_schema_snapshot.py holds the two together).
"""

from __future__ import annotations

from types import MappingProxyType

'''


def landing_tables() -> list[str]:
    names = re.findall(r"CREATE TABLE IF NOT EXISTS (\w+) \(", LANDING_SQL.read_text())
    return sorted(name.lower() for name in names)


def snapshot(tables: list[str]) -> dict[str, tuple[tuple[str, ...], tuple[str, ...]]]:
    from edgar_warehouse.silver_store import SilverDatabase

    db = SilverDatabase(":memory:")
    try:
        out = {}
        for table in tables:
            rows = db._conn.execute(
                "SELECT column_name, is_nullable FROM information_schema.columns "
                "WHERE table_schema = 'main' AND table_name = ? ORDER BY ordinal_position",
                [table],
            ).fetchall()
            if not rows:
                raise SystemExit(f"{table}: not in the DuckDB DDL")
            out[table] = (
                tuple(c for c, _ in rows),
                tuple(c for c, nullable in rows if nullable == "NO"),
            )
        return out
    finally:
        db.close()


def render(snap: dict[str, tuple[tuple[str, ...], tuple[str, ...]]]) -> str:
    def tup(items: tuple[str, ...]) -> str:
        body = "".join(f"        {item!r},\n" for item in items)
        return f"(\n{body}    )"

    lines = [HEADER, "COLUMNS: MappingProxyType[str, tuple[str, ...]] = MappingProxyType({\n"]
    for table, (columns, _) in snap.items():
        lines.append(f"    {table!r}: {tup(columns)},\n")
    lines.append("})\n\nREQUIRED: MappingProxyType[str, tuple[str, ...]] = MappingProxyType({\n")
    for table, (_, required) in snap.items():
        lines.append(f"    {table!r}: {tup(required)},\n")
    lines.append("})\n")
    return "".join(lines)


if __name__ == "__main__":
    TARGET.write_text(render(snapshot(landing_tables())))
    print(f"wrote {TARGET.relative_to(REPO_ROOT)}")
