-- GH-246: published, fail-closed Decision Contract objects for Agent View.
--
-- Apply only after the gold and graph generations named in
-- DECISION_CONTRACT_PUBLICATION have passed their independent full-chain
-- verification.  The publication row is an immutable release assertion; the
-- public views below return zero rows if the active graph pointer moves, the
-- assertion is not READY, or its coverage/alignment gates are not satisfied.
--
-- Template variables:
--   database: EDGARTOOLS_DEV or EDGARTOOLS_PROD

CREATE SCHEMA IF NOT EXISTS {{ database }}.EDGARTOOLS_DECISION;

CREATE TABLE IF NOT EXISTS {{ database }}.EDGARTOOLS_DECISION.DECISION_CONTRACT_PUBLICATION (
  DECISION_WATERMARK STRING NOT NULL,
  DECISION_CONTRACT_VERSION STRING NOT NULL,
  BUSINESS_DATE DATE NOT NULL,
  GOLD_UPDATED_AT TIMESTAMP_TZ NOT NULL,
  GRAPH_GENERATION_ID STRING NOT NULL,
  COVERAGE_STATE STRING NOT NULL,
  ALIGNMENT_STATUS STRING NOT NULL,
  PUBLICATION_STATUS STRING NOT NULL,
  PUBLISHED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PUBLISHED_BY STRING NOT NULL DEFAULT CURRENT_USER(),
  PRIMARY KEY (DECISION_WATERMARK)
);

CREATE OR REPLACE VIEW {{ database }}.EDGARTOOLS_DECISION.DECISION_CONTRACT_STATUS AS
SELECT
  p.DECISION_CONTRACT_VERSION,
  p.DECISION_WATERMARK,
  p.BUSINESS_DATE,
  p.GOLD_UPDATED_AT,
  p.GRAPH_GENERATION_ID,
  ptr.ACTIVATED_AT AS GRAPH_ACTIVATED_AT,
  p.COVERAGE_STATE,
  p.ALIGNMENT_STATUS,
  p.PUBLISHED_AT
FROM {{ database }}.EDGARTOOLS_DECISION.DECISION_CONTRACT_PUBLICATION p
JOIN {{ database }}.NEO4J_GRAPH_MIGRATION.GRAPH_ACTIVE_POINTER ptr
  ON ptr.POINTER_ID = 'active'
 AND ptr.ACTIVE_GENERATION_ID = p.GRAPH_GENERATION_ID
WHERE p.PUBLICATION_STATUS = 'ready'
  AND p.ALIGNMENT_STATUS = 'aligned'
  AND p.COVERAGE_STATE IN ('complete', 'partial')
QUALIFY ROW_NUMBER() OVER (
  ORDER BY p.BUSINESS_DATE DESC, p.PUBLISHED_AT DESC
) = 1;

-- Contract subject index and issuer bundle.  Identity is published through
-- this contract object, never looked up from unrestricted gold in Agent View.
-- COMPANY is already enriched from the MDM export; active tracking is required.
CREATE OR REPLACE VIEW {{ database }}.EDGARTOOLS_DECISION.SUBJECT_BUNDLE_READ_ISSUER AS
WITH contract AS (
  SELECT * FROM {{ database }}.EDGARTOOLS_DECISION.DECISION_CONTRACT_STATUS
),
tracked AS (
  SELECT
    c.CIK,
    c.ENTITY_ID,
    COALESCE(c.DISPLAY_NAME, c.ENTITY_NAME) AS ENTITY_NAME,
    c.ENTITY_TYPE,
    c.SIC,
    c.SIC_DESCRIPTION,
    c.STATE_OF_INCORPORATION,
    c.FISCAL_YEAR_END,
    LISTAGG(DISTINCT t.TICKER, ', ')
      WITHIN GROUP (ORDER BY t.TICKER) AS TICKERS
  FROM {{ database }}.EDGARTOOLS_GOLD.COMPANY c
  LEFT JOIN {{ database }}.EDGARTOOLS_GOLD.TICKER_REFERENCE t
    ON t.CIK = c.CIK
  WHERE LOWER(COALESCE(c.TRACKING_STATUS, '')) = 'active'
  GROUP BY
    c.CIK, c.ENTITY_ID, COALESCE(c.DISPLAY_NAME, c.ENTITY_NAME),
    c.ENTITY_TYPE, c.SIC, c.SIC_DESCRIPTION,
    c.STATE_OF_INCORPORATION, c.FISCAL_YEAR_END
),
active_graph_subject AS (
  SELECT n.NODEID
  FROM {{ database }}.NEO4J_GRAPH_MIGRATION.MDM_GRAPH_NODES n
  JOIN {{ database }}.NEO4J_GRAPH_MIGRATION.GRAPH_ACTIVE_POINTER ptr
    ON ptr.POINTER_ID = 'active'
   AND ptr.ACTIVE_GENERATION_ID = n.GENERATION_ID
  WHERE n.ENTITY_TYPE = 'company'
)
SELECT
  t.CIK,
  t.ENTITY_ID,
  t.ENTITY_NAME,
  t.ENTITY_TYPE,
  t.TICKERS,
  t.SIC,
  t.SIC_DESCRIPTION,
  t.STATE_OF_INCORPORATION,
  t.FISCAL_YEAR_END,
  f.FY_PERIOD_END,
  f.FY_FISCAL_YEAR,
  f.FY_ACCESSION_NUMBER,
  f.FY_REVENUE,
  f.FY_NET_INCOME,
  f.FY_TOTAL_ASSETS,
  f.FY_TOTAL_EQUITY,
  f.FY_FREE_CASH_FLOW,
  f.FY_ROE,
  f.FY_FEATURES_COVERAGE,
  f.INTERIM_PERIOD_END,
  f.INTERIM_FISCAL_PERIOD,
  f.INTERIM_ACCESSION_NUMBER,
  f.INTERIM_REVENUE,
  f.INTERIM_NET_INCOME,
  f.INTERIM_FEATURES_COVERAGE,
  c.DECISION_CONTRACT_VERSION,
  c.DECISION_WATERMARK,
  c.BUSINESS_DATE,
  c.GOLD_UPDATED_AT,
  c.GRAPH_GENERATION_ID,
  c.GRAPH_ACTIVATED_AT,
  c.COVERAGE_STATE,
  c.ALIGNMENT_STATUS
FROM tracked t
JOIN active_graph_subject g ON g.NODEID = t.ENTITY_ID
JOIN {{ database }}.EDGARTOOLS_DECISION.SUBJECT_FEATURE_SCREEN f
  ON f.CIK = t.CIK
CROSS JOIN contract c;

CREATE OR REPLACE VIEW {{ database }}.EDGARTOOLS_DECISION.SUBJECT_BUNDLE_READ AS
SELECT * FROM {{ database }}.EDGARTOOLS_DECISION.SUBJECT_BUNDLE_READ_ISSUER;

-- Reader access is explicit.  Substitute the environment reader role at apply
-- time; no raw publication table or graph table access is granted here.
GRANT USAGE ON SCHEMA {{ database }}.EDGARTOOLS_DECISION
  TO ROLE IDENTIFIER('{{ reader_role }}');
GRANT SELECT ON VIEW {{ database }}.EDGARTOOLS_DECISION.DECISION_CONTRACT_STATUS
  TO ROLE IDENTIFIER('{{ reader_role }}');
GRANT SELECT ON VIEW {{ database }}.EDGARTOOLS_DECISION.SUBJECT_BUNDLE_READ
  TO ROLE IDENTIFIER('{{ reader_role }}');
GRANT SELECT ON VIEW {{ database }}.EDGARTOOLS_DECISION.SUBJECT_BUNDLE_READ_ISSUER
  TO ROLE IDENTIFIER('{{ reader_role }}');
